### ISSUE TITLE
Create an image for Cayenne

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1015]
https://github.com/Heuro-labs/cayenne

**Comment by jonrkarr** [comment]
We should prioritize more popular simulators first

**Comment by jonrkarr** [comment]
Once we are really ready to share, we can message other developers to encourage them to create containerized simulation tools. We can put together a list when we get to that point. Ion and I assembled some names for the purpose of inviting people to breakout. We can build from that list.

**Comment by jonrkarr** [comment]
Closing. This should be handled by the Cayenne developers.
