### ISSUE TITLE
Minor bugs to fix

### ISSUE THREAD

**Issue by gmarupilla** [reproducible-biomedical-modeling/CRBM-Viz#1023]
TODO:
- [ ]  Scale dispatch service in HPC.
     - [ ]  show the status,
     - [ ]  stop simulation,
     - [ ]  user updates.
     - [ ]  Queue status
- [ ] Dispatch logging in frontend
- [ ] Fix directory structure on NFS to fetch the results

**BUGS**

1. [ dispatch-service ] Results in API twice to get JSON
2. UI getting struck after deploying simulations and changing between tabs
3. Cannot see the title of the tab in the blue title bar for home and dispatch
4. Plots are not getting repainted on tab switch

**Comment by bilalshaikh42** [comment]
@gmarupilla have these been changed since the last pull? Lets seperate out the issues so we can keep track of whats left and what is to be done in the future (such as 6)

**Comment by gmarupilla** [comment]
Some bugs are fixed. I'll separate the issues that we can keep track.
