### ISSUE TITLE
Setup biosimulations.github.io

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1047]
github.io needs to be setup after the organization renaming
e.g., https://biosimulations.github.io/biosimulations/

**Comment by bilalshaikh42** [comment]
I dont remember what we had hosted there. Do we still need the deployment? I recall using it to host before netlify

**Comment by jonrkarr** [comment]
There's a link to there for API documentation. I'm not aware of any documentation that needs to be hosted there. I'll delete this link.
