### ISSUE TITLE
Send email notification upon completion of a simulation in the dispatch app

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1067]
In #1066 I added an input box to optionally collect an email address from the user. If this is provider, the dispatch service should send the user an email upon completion of the simulation.

In #1066 I also styled the form, added validation, added error messages, and switched the form to use ReactiveForm (which makes implementing the form simpler).

**Comment by gmarupilla** [comment]
@jonrkarr @bilalshaikh42 Do we have any dedicated email (or SMTP server) that we can use for this task? Because even though we will get the recipient email from UI, we still need an email on `biosimulations.org` domain. I think we already have `info@biosimulations.org` are we going to use that only?

Also, below is the email template that I'm thinking of using. Any modifications?
```
Subject: Simulation <STATUS> | <UUID>

Body: 
Greetings Guest user,

Your simulation with UUID <UUID> has <STATUS>.

if <STATUS> = FAILED:
Try these steps to troubleshoot the issue:
1. Try dispatching the simulation again.
2. Try dispatching with another omex, it might be the case that the omex you're using is corrupted.
3. Try checking the logs.
4. If you face "Server Error" try dispatching after few minutes.

if <STATUS> = PASSED:
The results and visualizations are ready for analysis.
You can check the visualization for simulation results using the URL below:
https://submit.biosimulations.dev/results/<UUID>


Regards,
Biosimulations Team
```

**Comment by jonrkarr** [comment]
## Email server
@bilalshaikh42 did you have a plan for sending email?

## Template
The template looks good. Nice idea providing a list of suggestions for trouble shooting! Here's minor edits to the template.

I think it would be helpful to have a separate name for the dispatch app so we have one name for the "platform" and a different name for this app. How about "runBioSimulations"?

```
Subject: runBioSimulations <STATUS> | <UUID>

Body: 
Greetings runBioSimulations user,

Your simulation with id <UUID> has <STATUS>.

if <STATUS> = FAILED:
We recommend trying these steps to troubleshoot your simulation(s):
1. View the error log.
2. If you the error log indicates a "Server Error", submit the COMBINE/OMEX archive to runBioSimulations again.
3. Check that your file is a valid COMBINE/OMEX archive.
4. Try submitting an alternative COMBINE/OMEX archive.

if <STATUS> = PASSED:
The results of your simulation(s) are ready for you.
You can access and visualize the simulation results at the URL below:
https://submit.biosimulations.org/simulations/<UUID>

Thank you for using runBioSimulations!

Regards,
Biosimulations Team
https://biosimulations.org
```

**Comment by gmarupilla** [comment]
`runBioSimulations` looks appropriate to me

**Comment by gmarupilla** [comment]
So if we are going to change the `dispatch` app to `runBioSimulations`, are we going to change `dispatch-api`, `dispatch-service` to `runBioSimulations-API`, `runBioSimulations-Service` respectively?

**Comment by jonrkarr** [comment]
We can keep those names internally. Externally, I think we should use a name that we be more meaningful to users. E.g.
- subdomain name
- page title
- logo

The only thing that needs to be changed is the subdomain name. Actually, submit is pretty good. "run" would be shorter and mesh with "runBioSimulations", which I think it s a good name for this. "submitBioSimulations" or "dispatchBiosimulations" doesn't seem quite right for users.

**Comment by jonrkarr** [comment]
Another small edit to use the user-supplied name of the simulation

```
Subject: runBioSimulations <STATUS> | <NAME> (#<UUID>)

Body: 
Greetings runBioSimulations user,

Your simulation with has <STATUS>.
* Id: <UUID>
* Name: <NAME>
* Date: <DATE_SUMITTED>

if <STATUS> = FAILED:
We recommend trying these steps to troubleshoot your simulation(s):
1. View the error log.
2. If you the error log indicates a "Server Error", submit the COMBINE/OMEX archive to runBioSimulations again.
3. Check that your file is a valid COMBINE/OMEX archive.
4. Try submitting an alternative COMBINE/OMEX archive.

if <STATUS> = PASSED:
The results of your simulation(s) are ready for you. You can access and visualize the simulation results at the URL below. Your simulation and its results will be available for six months.
https://submit.biosimulations.org/simulations/<UUID>

Thank you for using runBioSimulations!

Regards,
Biosimulations Team
https://biosimulations.org
```

**Comment by jonrkarr** [comment]
Is email working? If so, we can re-enable the email input in the submission form.

**Comment by bilalshaikh42** [comment]
No this is not working currently.
