### ISSUE TITLE
Make height of dispatch visualization responsive to page height

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1068]
This must be set programmatically because plotly ignores percent heights. A JavaScript method needs to be written which sets the height based on the height of its parent.

**Comment by gmarupilla** [comment]
@jonrkarr Fixed in the commit 5caf5092ee4d921acd7586e79b825ed41b1efae6 of PR #1459 , but is there a way to fix with making changes in libs? I tried with :host CSS selector, it didn't work.

**Comment by jonrkarr** [comment]
I simplified the resizing in PR #1660. @gmarupilla does this address your comment?

**Comment by gmarupilla** [comment]
Yes, PR #1660 solves this issue, and I approved the PR. Thanks.
