### ISSUE TITLE
Should the dispatch app save and display 2dplot and 3dplots generated by simulation tools?

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1073]
I want to bring up a point for discussion.

SED-ML files can specify two kinds of outputs:
- Results files (e.g., CSV)
- 2d and 3d plots (e.g., one PDF per plot)

Currently, the dispatch app focuses on results -- retrieving them and visualizing them with Plotly. Ideally, BioSimulations would also save any plot files generated by the simulators and let users access these files.

From the perspective of focusing on the most essential functionality, I don't think this its essential to save this plot files. I think its even less essential to provide UI components for viewing these plots. If we are saving these files, users could simply retrieve them via the download link for simulation results (e.g., a .zip archive that includes all files generated from a COMBINE archive).

Thoughts?

**Comment by gmarupilla** [comment]
For individual chart saving, Plotly out of the box gives the ability to save the graph. 
Archiving seems to be a great idea, and also, users can download all the data related to a single simulation in one go (i.e., SBML, SED-ML, result CSV file, plot files)

**Comment by jonrkarr** [comment]
I'm referring to charts that are specified in SED-ML. These are separate from what you've setup with Plotly. tellurium, for example, will generate 2d and 3d plots and save them to PDF files. Since, at least some, simulation tools generate plot files, ideally we would save these files and let users download them.

To clarify, Plotly is and should continue to be separate from the plots in SED-ML files. We don't need to make any changes to the use of Plotly.

**Comment by gmarupilla** [comment]
Now I got it, I totally misunderstood, I noticed those as `<listOfOutputs>` element in SED-ML. IMO, we can permit User for downloading the PDF(example tellurium) from UI.

**Comment by jonrkarr** [comment]
Yes, I'm referring to `<listOfOutputs>`. Links to download the individual files or a link to a .zip/.tar.gz with all of the files would be perfect!

**Comment by jonrkarr** [comment]
This can be merged with #1071
