### ISSUE TITLE
Add link to dispatch form to download an example COMBINE/OMEX archive

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1075]
Add to hint below the COMBINE/OMEX file input box.

**Comment by gmarupilla** [comment]
We have 3 options to do that:
1. We can place the sample OMEX to GitHub repo and provide a downloadable link to UI.
2. We can place it on VCELL webserver(https://vcell.org/webstart/pipeline_files/) and provide a downloadable link to UI.
3. We can request dispatch API to send an OMEX file in response for real as octet-stream (or in some other way possible).

In my opinion, option 2 is better than other two. What do you think @jonrkarr ?

**Comment by jonrkarr** [comment]
Because many people are not familiar with the OMEX format, I think its helpful to provide an explicit example. I was thinking of providing a hyperlink to an example. I see two main possibilities:
- Point to an file in our test suite, e.g. https://github.com/biosimulations/Biosimulations_COMBINE_archive_test_suite/raw/master/Biosimulations_combine_archive_test_suite/BIOMD0000000823.omex
- Copy the file to `Biosimulations/biosimulations/libs/shared/assets/src/assets/` so Netlify can serve it. Then it would have a URL like `https://biosimulations.dev/assets/examples/BIOMD0000000823.omex`

In the interest of promoting the test suite, the first option seems simple to me.

**Comment by jonrkarr** [comment]
I added a link to an example in the test suite (in GitHub)
