### ISSUE TITLE
Rename model and simulation URLs to be more semantically meaningful

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#108]
- Models
  - Browse: `/files` --> `/models`
  - Upload new: `/models/new`
- Simulations
   - Browse: `/data` --> `/simulations`
   - Status: `/simulations/status`
   - Schedule new: `/simulations/new`
- Visualizations
  - Browse: `/visualize` --> `/visualizations`

**Comment by bilalshaikh42** [comment]
Fixed in #123
