### ISSUE TITLE
Save additional information with each simulation submitted to the dispatch app

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1088]
In addition to the id, OMEX file and results, the database should save the following information. This information will help users recall what each simulation means and when it was submitted.
- [x] Name of the simulation (string, does not need to be unique)
- [x] Email address of submitter (string, optional)
- [x] Time simulation was submitted (date)
- [x] Time status was last updated (date)
- [x] Current status: queued, running, succeeded, failed (enum)
- [x] Run time in seconds (number)

**Comment by jonrkarr** [comment]
I added a field to capture a name and email to the dispatch form. 

Still todo
- [x] Save the above information to the database and retrieve it (`biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts`)
- [x] Display this information in the simulations table (`biosimulations/apps/dispatch/src/app/components/simulatons/browse/browse.html`) and in the individual simulation pages (`biosimulations/apps/dispatch/src/app/components/simulatons/view/view.html`)

**Comment by gmarupilla** [comment]
In sync with #1124 because status updates cannot return into DB until #1124 gets fixed
