### ISSUE TITLE
Status monitoring for Jobs

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1124]
A proposed approach for monitoring jobs: 

The jobs are run on the HPC as following: 

1. The sbatch template creates a file called STARTED in the directory, which contains some basic info about the job
2. The job runs as normal, outputting to the directory
3. If there is an error in the simulation it is output into a file called ERROR
4. When the job completes, the sbatch template outputs a file called DONE with some basic timing info

The jobs are monitored as following: 
1. The dispatch service maintains an intenal state of the simulation that starts in "QUEUED" stated.
2. It then  uses the [ file system watch method](https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener) to watch the directory for the presence of the STARTED, ERROR, and DONE files
3. Upon any change to those files, it uses the callback to update its internal state.
4.  When the state is updated, it sends a message to the message system that alerts the system that the results can then be processed by other apps (for example, this is how the results can be generated)

**Comment by bilalshaikh42** [comment]
1. If the user explicitly wants to check the status of the job, we can use a route that can manually ssh into the hpc and use the SLURM status. But this would only need to happen once, not on  loop

**Comment by jonrkarr** [comment]
This looks like a good plan.

A few comments
- Externally, I would call the started state "Running"
- Explicitly checking the status could be useful to us as the developers. Unless simulation tools output status information, this likely wouldn't be much help to users. Perhaps in a version 2.0 of BioSimulators we could encourage simulation tools to support a simple logging protocol. This would open the possibility of enabling users to see the status of their simulations in real time. For these reasons, I'd like us to focus on more critical functionality first.
- To display a log to users, it would be good to combine STDOUT and STDERR into one log as users typically see on their console. Ideally, we save a HTML representation of the log that enables us to color-code status and error messages, similar to CI tools such as GitHub actions. This isn't critical. We can focus on more critical things first.

In the interest of outlining potential alternatives, I think its also possible to get all of this information, except the STDOUT/ERR logs from SLURM. I think SLRUM also has hooks that could be used to trigger status update events. The above approach seems a little simpler and independent from SLURM.

**Comment by bilalshaikh42** [comment]
The issue that we were having was the slurm would be running on the HPC, and thus we would need an ssh connection. The creation of the ssh connection and then using slurm to monitor the status was creating a blocking loop, and essentially meant the service could only start jobs when the first was done. Since we have mounted the output drive to the service, we dont need to ssh into the hpc, as all the monitoring can be done locally.

**Comment by jonrkarr** [comment]
This strategy makes sense as a way to avoid SSH
