### ISSUE TITLE
Register biosimulations.org domain or whichever other domain we decide on

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#114]

**Comment by bilalshaikh42** [comment]
@mpw6  Is there any update on this? Is the procurment process complete?

**Comment by jonrkarr** [comment]
UConn is working on this
- BioSimulations.org
- BioSimulations.io

**Comment by bilalshaikh42** [comment]
Done

**Comment by jonrkarr** [comment]
When the domain is up, the URLs in the README and documentation should be udpated from Heroku to biosimulations.org/io
