### ISSUE TITLE
How long should we commit to store simulation results for the dispatch app?

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1149]
@bilalshaikh42 @mpw6 @moraru @gmarupilla 6 months? 6 months since last access?

**Comment by gmarupilla** [comment]
IMO, We can store the results file and data for six months, and a simple cron job can delete the six months older data from NFS

**Comment by moraru** [comment]
I would say forever.  Quite doable given current storage resources.  We have done this for VCell and currently storing 20 years worth of user data: 600,277 simulation result sets from 7,132 different users.  We won’t be anytime soon having to deal with numbers larger than that at biosimulations, , and note that many of the VCell simulation results are spatial and orders of magnitude larger than the average dataset for the majority of expected biosimulations runs.

What we dio need to do, though, is to make sure that once a simulation is being deleted by the user from the database, the results are being removed from the storage backend.  Also, we can plan for a periodic archival, but this is not urgent (in VCell we move simulations older than 1 year to a cheaper, archival storage – they are still directly and immediately accessible, just they don’t clutter the main working NAS).

**Comment by jonrkarr** [comment]
A few additional points
- I agree forever should be the policy for the public BioSimulations platform.
- I intended for this discussion to be about the webservice (https://submit.biosimulations.org). Given that there's no user accounts, people will likely loose track of their simulations. For this reason, it seems unnecessary to keep simulation results for forever.
- For the webservice, I think we should post a note in the documentation about the minimum duration that we commit to store results for. We could could advertise something, say 6 months. In practice, we could still keep everything until it becomes too expensive for us (if that ever happens).

**Comment by moraru** [comment]
I agree: data from authenticated users kept forever, data from anonymous access cleaned periodically (if necessary).

**Comment by jonrkarr** [comment]
I added documentation of these policies to the platform and dispatch apps. I added an issue #1157 to create a chron job to delete results of simulations submitted anonymously through the dispatch (runBioSimulations) app.
