### ISSUE TITLE
Table of Contents overlaps page content at various resolutions

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1186]
**Please describe the bug**
At some resolutions, the table of contents overlaps the main page contents

**Please describe how to reproduce the bug**
1. Go to ' https://www.biosimulators.org/simulators/vcell'
2. Change resolution to half/partial width of screen
3. Text overlaps and is not legible

**Screenshots**
![image](https://user-images.githubusercontent.com/32490144/93268123-b13f2e00-f77a-11ea-9f78-89ebacd2c488.png)

![image](https://user-images.githubusercontent.com/32490144/93268353-0713d600-f77b-11ea-9282-7e43edf8f0ff.png)

**Environment (please complete the following information):**
 - Type of device: Desktop
 - OS:  Windows 10
 - Browser Chrome
 - Version latest

**Additional context**

**Comment by jonrkarr** [comment]
Fixed in new branch. This appears to be related to media matching. I switched to a breakpoint observer.
