### ISSUE TITLE
Allow (at least some) cross-domain access to simulators API

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1193]
- Necessary for submit.biosimulations.org
- Necessary for local development

A better way to limit access is via API tokens.

**Comment by bilalshaikh42** [comment]
localhost:4200 and 127.0.0.1:4200 are both allowed already. 
I just added submit.biosimulations.dev, should deploy soon

**Comment by jonrkarr** [comment]
We need to allow additional ports. While developing multiple apps, it's necessary to use multiple ports simultaneously.

**Comment by jonrkarr** [comment]
fixed in #1209
