### ISSUE TITLE
Deploy old demo (from Feb 2020) to BioSimulations.org

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1203]
With demo models and simulations to we can illustrate what the tables of resources and views of individual resources will look like

**Comment by bilalshaikh42** [comment]
I have deployed the feb 2020 version, to biosimulations.org, but this depended on the old API, which is not running. I can look into older demos that contained the example data within the app itself, but those will not have much of the front page changes

**Comment by jonrkarr** [comment]
I was thinking of going back further when the models and simulations were hard-coded. Maybe this commit from December 2019 c68385794258d092ef3b74d6adfcde596dc592c1. I forgot that this did use the API for user account information.

I don't want to spend a lot of time setting this up.  Alternatively, run this commit locally, comment out any code for the API or auth0, and save a few screenshots to show during a presentation.
