### ISSUE TITLE
Table of contents does not update when used within a components with onPush strategy

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1230]
**Please describe the bug**

When using a responsive table, the table of contents are not generated at the same breakpoint

**Please describe how to reproduce the bug**

Go to biosimulators.org/copasi/

1. resize the window until the mobile table appears
2. contents will not be generated
3. continue to shrink the window, contents will appear

**How should BioSimulations have behaved**

Contents should be generated at the same breakpoint as the switch to mobile table

**Comment by jonrkarr** [comment]
Fixed in #1232. Just needed to remove push change detection.
