### ISSUE TITLE
Simulator view does not reset to main tab on version change

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1234]
**Please describe the bug**

On the view simulators page, selecting a different version does not reset the tab group to the main tab

**Please describe how to reproduce the bug**

1. Go to www.biosimulators.org/simulators/copasi
2. Click on versions
3. Select a version other than the lates
4. While the data does update, the versions tab is still selected

**How should BioSimulations have behaved**

The view should switch to the main tab

**Additional context**

This is probably a problem with the biosimulations-tab group wrapper. Since the url parameter change is detected at a containing component, it must not be getting passed down. The component might need to include a listener for url changes. expose the underlying mat-tab group to allow for the index to be changed manually.

**Comment by bilalshaikh42** [comment]
This might be caused by the nested routes. I think that creating a container component with a router outlet might fix the problem

**Comment by jonrkarr** [comment]
Addressed in dev-simulators branch.

I tried adding a router outlet, but couldn't figure out how to make it work. Anyway, I don't think this would result in the tab changing to the first tab when changing from one specific version to another.

Instead, I listened to changes to the route, and changed the selected tab on route changes.
