### ISSUE TITLE
TocSectionsContainer breaks if page has not loaded due to pending observable

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1256]
If the template has not yet rendered due to a pending observable, the set toc method is still called, causing an error that blocks further rendering.

**Comment by bilalshaikh42** [comment]
@jonrkarr  Is there a way to change the time for when this is triggered?

**Comment by jonrkarr** [comment]
Unfortunately, I couldn't find any packages to use to implement a toc. The toc is inspired by this package: https://www.npmjs.com/package/angular-contents. 

The toc container is very simple. It just has a list of sections. You could try turning the list of sections into an observable, or triggering and listening to events to hack the updating you need.

**Comment by jonrkarr** [comment]
Addressed in dev-toc / #1350 branch with observables.

**Comment by jonrkarr** [comment]
@bilalshaikh42 please the problem that you're still seeing.
