### ISSUE TITLE
Add feedback for button clicks in UI

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1288]
**Is your feature request related to a problem? Please describe.**
On the simulators homepage, when clicking on the simulators button, the application appears to be unresponsive before navigating.  See #1289
**Please describe the solution you'd like**

When I click the button, it should provide feedback that the click was registered.  Reintroducing the ripple effect for navigation buttons might be a good way to approach it

**Please describe alternatives you've considered**
As mentioned in #1289  we can fix this  particular problem by ensuring that the simulator page is preloaded. But this is a more general problem of not having sufficient feedback on button clicks that may have a delay in response. Button should generally include feedback. 

@jonrkarr  thoughts on re-enabling the ripple?

**Comment by jonrkarr** [comment]
Personally, I don't like ripples. For one, they require extra padding, forcing larger components.

Ripples aren't necessary to indicate a button was pressed. This can also be done by changing the color and/or adding a box shadow.

**Comment by bilalshaikh42** [comment]
We dont need to use the ripple. I thought it would be the simplest change since we could just remove the option to turn it off. I did not realize it caused issued with the padding. 

We can use some other feedback

**Comment by jonrkarr** [comment]
Addressed in dev-simulators branch
