### ISSUE TITLE
Simulators module is very large

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1290]
The simulators module on the simulators app is 4.6 mb uncompressed. There may be an erroneous import causing this.

**Comment by bilalshaikh42** [comment]
This seemed to be a local only issue. The deployed version seems fine.

**Comment by jonrkarr** [comment]
Seems ok on my browser even after clearing the cache

**Comment by bilalshaikh42** [comment]
This was caused by the large size of the Font Awesome icons. Icons are now imported individually, rather than the entire library. Also have added preloading to prevent this from being noticeable.
