### ISSUE TITLE
Add a link to download sample combine archive on runBiosimulations

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1292]
This would allow users to test the functionality without needing to construct an archive

**Comment by gmarupilla** [comment]
We can find sample OMEX/COMBINE Archive from [here](https://run.biosimulations.org/run)

![image](https://user-images.githubusercontent.com/53095348/95028239-e00b3e80-066c-11eb-898b-d2cf7d3de98b.png)

**Comment by jonrkarr** [comment]
This overlaps with a closed issue. This can also be closed.

**Comment by bilalshaikh42** [comment]
@gmarupilla It seems the link is broken. Could you make a pr to fix the link?

**Comment by jonrkarr** [comment]
The link needs to be updated to
https://github.com/biosimulators/Biosimulators_test_suite/raw/master/Biosimulators_test_suite/BIOMD0000000297.omex

**Comment by gmarupilla** [comment]
Yes I fixed in #1255 before changes. But raised new PR #1297
