### ISSUE TITLE
What is the best place for community discussion about expanding/refining the ontologies used by BioSimulations/BioSimulators?

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1306]
There is a need to expand many of the community ontologies to better include simulation algorithms, frameworks, features. 

We can encourage adoption of [Ontolobridge](https://www.bioontology.org/missing-a-term-bioportal-speaks-ontolobridge/) to encourage simulator contributors to add terms.

**Comment by jonrkarr** [comment]
The "community" ontologies already have processes and infrastructure for accepting proposals for new terms. Their infrastructure is generally connected to the repos (most frequently GitHub) they use to manage the ontologies. In my opinion, these repos provides many more features for collaboration than BioPortal. We will have to embrace the infrastructure that each ontology already uses to manage new terms and edits to existing terms. I have already used this to get new terms added to EDAM and KiSAO. Ontologies managed by Git repos also open the possibility of contributing/editing many terms through forking and pull requests.

- EDAM: [GitHub issues](https://github.com/edamontology/edamontology/issues/new/choose)
- KiSAO: [SourceForge issues](https://sourceforge.net/p/kisao/feature-requests/new/)
- SBO: [SourceForge issues](https://sourceforge.net/p/sbo/term-request/)
- SPDX: [Web form](https://tools.spdx.org/app/submit_new_license/) which generates a GitHub issue

**Comment by jonrkarr** [comment]
I'm closing this because each of the ontologies we're working with already has a process in place. I don't think we should encourage Ontolobridge for these ontologies because this could generate confusion with the existing processes for these ontologies.
