### ISSUE TITLE
Add url attribute to Identifier interface in BioSimulators API

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1310]
This needs to be added to fix the citations -- related to #1299

**Comment by jonrkarr** [comment]
The current data model is actually fine for citations.
- Articles with DOIs or ISBNs can use `namespace: {'doi' | 'isbn'}, id: {doi}`. The code can compute a URL.
- Articles with PubMed ids can use `namespace: pubmed, id: {pubmed-id}`. The URL can be resolved with identifiers.org
- Articles without DOIs or PubMed ids can use `namespace: url, id: {url}`

In general, it would be good to separate the `id` attribute from the `url` attribute. This will allow us to keep track of identifiers in namespaces that we don't know how to resolve URLs for, and store their URLs.

**Comment by bilalshaikh42** [comment]
Could you clarify what the needed change is?  Is this just a database update?

**Comment by jonrkarr** [comment]
Tasks
- [ ] Add `url` attribute to the `Identifier` interface -- for citations which don't have DOIs (e.g., books)
- [x] Add `url` fields to `properties.json` files
- [x] Update metadata in simulators data -- use the revised `properties.json` files 

Its not clear which classes define the data model for the API. It looks like a `url` attribute is missing from this `Identifier` interface
`biosimulations/libs/shared/datamodel/src/lib/common/ontology.ts`. It look like a `url` attribute needs to be added here. I also don't see a `url` field in the swagger page of the simulators API: https://api.biosimulators.org/.

I have added `url` fields to the `properties.json` files in the simulator repos for citations which don't have DOIs (e.g., books, journals which don't register DOIs, white papers that can only be referenced with URLs).

**Comment by jonrkarr** [comment]
`url` attribute still needs to be added to the `Identifier` interface

**Comment by jonrkarr** [comment]
`url` attribute still needs to be added to the `Identifier` interface.

api.biosimulators.org shows

```
Identifier{
  namespace*	string
  id*	string
}
```

`url` is missing.

**Comment by jonrkarr** [comment]
This looks to be done.
