### ISSUE TITLE
Add validation to API set methods

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1312]
The simulators database has data which is not consistent with the data model for the API. One example is the identifiers for citations (#1311). Input should be validated to prevent issues like this and quickly alert us to issues that need to be addressed.

**Comment by jonrkarr** [comment]
Ideally, this would validate that valid ontology terms are referenced. This would have identified the issue in #1313 where the database has some invalid ids for algorithm parameters.

**Comment by bilalshaikh42** [comment]
The validation was added in #1277. The entries were added before, but the same error should be caught now.
