### ISSUE TITLE
Provide human-readable API conflict messages

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1329]
When POST requests are rejected because a simulator/version is already present in the database, a more informative error message should be provided than below
```
{
  "statusCode": 409,
  "message": "Conflict",
  "error": "Database Error"
}
```

**Comment by bilalshaikh42** [comment]
This should be happening already. If the production version is not giving that error, it may just be out of date and need to be redeployed. 
I have not yet included more specific errors for an incorrect schema, but will update that soon
