### ISSUE TITLE
Automate committing of simulation tools to database within submission GitHub action workflow

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1359]
I outlined an issue-based workflow for accepting contributions of simulation tools.

Committing the simulation tool to the database needs to be incorporated here: https://github.com/biosimulations/Biosimulations_utils/blob/align-with-api/Biosimulations_utils/ci_actions/validate_commit_simulator.py

Tasks
- [x] Pull image and push copy to GitHub container repo under biosimulators organization
   - [x] URL pattern: `ghcr.io/biosimulators/{simulator-id}:{simulator-version}-{biosimulators-schemaVersion}-{imageVersion}`
   - [x] Set short tag when image is the latest copy of the version of the simulator (`ghcr.io/biosimulators/{simulator-id}:{simulator-version}`)
   - [x] Set latest tag when image is the latest pushed version(`ghcr.io/biosimulators/{simulator-id}:latest`)
- [x] Replace the image URL in the specs with the URL for the copy in the GitHub container repo
- [x] Add a secret for the BioSimulators API to the `biosimulators/Biosimulators` repository
- [x] Use this secret in Biosimulations_utils/ci_actions/validate_commit_simulator.py to post to the BioSimulators API. See `TODO` note in Python code

**Comment by jonrkarr** [comment]
I added secrets to the GitHub repo for the "GitHub Simulators Actions" Auth0 app
- `BIOSIMULATORS_API_CLIENT_ID`
- `BIOSIMULATORS_API_CLIENT_SECRET`

I added code to use the secret to get an auth token to the BioSimulators API.

I added code to use the auth token to POST/PUT to the BioSimulators API. There seems to be an issue with the authorization. See #1402.

**Comment by bilalshaikh42** [comment]
can this be closed when #1402 is?

**Comment by jonrkarr** [comment]
I just incorporated this into the `align-with-api` branch of `Biosimulations_utils`.
