### ISSUE TITLE
Redirect https://run.biosimulations.org/api to https://run.biosimulations.org/api/ (add trailing slash)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1374]
https://run.biosimulations.org/api doesn't return anything. This should be re-directed to https://run.biosimulations.org/api/.

**Comment by gmarupilla** [comment]
We can redirect to  https://dispatch.biosimulations.dev/

**Comment by jonrkarr** [comment]
The issue isn't re-directing to `.dev`. The issue is that the API URL should accept both with and without the trailing slash:
- https://run.biosimulations.org/api
- https://run.biosimulations.org/api/

**Comment by bilalshaikh42** [comment]
This is using the netlify proxy system to proxy the /api path from the front end. I can take a look at why it is requiring a forward slash. Not sure if the issue is with the proxy or the api itself.

**Comment by bilalshaikh42** [comment]
I see the issue. The [_redirects file](https://github.com/biosimulations/Biosimulations/blob/dev/biosimulations/libs/shared/assets/src/_redirects) is designed to proxy request to the api, so looks for the value after the forward slash. It is only configured to redirect to the main biosimulations api for the platform however, not to the correct API for submitting jobs. 
The reason it does this was so that the load balancer/Ingress at the kubernetes cluster could then handle path based routing as discussed in #1051. 
Is there a current use for the /api path? It is not documented anywhere, so it should not be encountered by users

**Comment by jonrkarr** [comment]
I think we should use https://run.biosimulations.org/api rather than the current https://submit.biosimulations.org/. I raised this issue before in #1051. This would clarify the relationship between runBioSimulations and its API -- its not obvious that submit.biosimulations is the API for runBioSimulations.

We need the `/api/` (and `/api`) path for the API for runBioSimulations. BioSimulators and BioSimulators can use `api.biosimulators.info`, but runBioSimulations isn't using this address pattern.

Since we have `/api/`, `/api` should point to the same resource -- users shouldn't have to be concerned with whether the trailing slash is required or not. Right now `/api` just generates a blank page.

**Comment by bilalshaikh42** [comment]
Right, so the current proxy will only be working for the platform-api the way it is currently set (through the netlify proxy). Nelify will proxy all requests across all apps to "/api" to "api.biosimulations.org".  
We can change the behavior by including the _redirects file for each app separately.  But this will be adding a routing pattern that does not exists in the DNS records or the kubernetes config. 
My plan for this was to have the "/api" always redirect to the api.biosimulations.org. The run route would then be something like api.biosimulations.org/run. Or, if using the proxy, run.biosimulations.org/api/run

**Comment by jonrkarr** [comment]
I think we're talking about different things.

Anyway, PR #1376 addresses the issue I brought up -- since `run.biosimulations.org/api/` is a route, `run.biosimulations.org/api` should also re-direct to the API.
