### ISSUE TITLE
Share privileges to Google search console properties

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1382]
@bilalshaikh42 can you please grant me access?

**Comment by bilalshaikh42** [comment]
Done

**Comment by jonrkarr** [comment]
I got access to biosimulators.org. Access to the domain is the same as access to the search console tools.

Can you share access to the biosimulators.com domain?

How did you setup Google search console for biosimulations.org? If you used Google Analytics, you can share access through Google Analytics.

**Comment by bilalshaikh42** [comment]
For biosimulations.org, since the domain is registered via uconn I had to use DNS verification. I did add you as an owner on the search console but cannot change the domain settings.

**Comment by jonrkarr** [comment]
Thanks.
