### ISSUE TITLE
Stricter simulator specifications validation

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1391]
Currently the validation seems to allow extra keys at any point in the schema. While this flexibility may be helpful for us as developers, I think this could give the community the false impression that BioSimulators can use such keys. 

- [x] We need to make the validation stricter. The one part of the schema would come remain more flexible is the `biosimulators` field. I believe this is addressed in #1421.
- [x] ~~If you want to allow the community to contribute additional information that is opaque to the BioSimulators schema/tools, there could be a specific field for such information e.g., `annotation`. This field should be optional and the type of its value should be any. This is roughly how SBML handles extra user-specific data. I don't think we have a need for this now.~~
- [x] ~~the update endpoint (PUT `/simulators/{}/{}`) currently ignores the simulator and version parameters. These should be removed or validated that they match the id and version in the specification (body of the PUT). This is ok as is. As is, this allows renaming of simulators or their versions.~~

**Comment by bilalshaikh42** [comment]
done in #1435
