### ISSUE TITLE
Unable to use BioSimulators API with tokens for "GitHub Simulators Actions" application

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1402]
I'm trying to use this workflow to get tokens to POST/PUT simulators to the BioSimulators api.
1. Use client id/secret for "GitHub Simulators Actions" application to get an auth token
2. Use token with POST/PUT methods of BioSimulators api

(1) seems to work fine. 

(2) Fails with 500 Server Error. Do additional permissions need to be granted to the "GitHub Simulators Actions" application?

## Get token to access BioSimulators API
- Endpoint: https://auth.biosimulations.org/oauth/token
- Method: `POST`
- Client id: `<client id for Github Simulator Action application>`
- Client secret: `<client secret for Github Simulator Action application>`
- Audience: `api.biosimulations.org`
- Grant type: `client_credentials`

```python
import requests
response = requests.post(auth-endpoint, json={
    'client_id': client_id,
    'client_secret': client_secret,
    'audience': audience,
    "grant_type": "client_credentials",
})
response.raise_for_status()
response_data = response.json()
auth_headers = {'Authorization': response_data['token_type'] + ' ' + response_data['access_token']}
```

## POST/PUT to BioSimulators API
- Endpoint: https://api.biosimulators.org/simulators/{simulator-id}/{simulator-version}
- Method: `PUT`
- Headers:
  - `Authorization`: `Bearer <token>`
  - `Content-Type`: `application/json`
- data: `<simulator-specifications>`

```python
import json
with open('../Biosimulators_tellurium/biosimulators.json', 'r') as file: 
    specs = json.load(file)

endpoint = 'https://api.biosimulators.org/simulators/tellurium/2.1.6'
response = requests.put(endpoint, headers=auth_headers, json=specs)
response.raise_for_status()
```

**Comment by jonrkarr** [comment]
POST/PUT works fine if I copy tokens from the BioSimulators API Swagger app.

**Comment by jonrkarr** [comment]
The auth tokens still don't work. They get a 403 error (forbidden). @bilalshaikh42 is there something about the configuration below that needs to changed?

```python
import requests
import json

response = requests.post('https://auth.biosimulations.org/oauth/token', json={
    'client_id': 'F33xsG2LydT57smqu8asfMZ410SJ0IHP',
    'client_secret': '***',
    'audience': 'api.biosimulations.org',
    "grant_type": "client_credentials",
})
response.raise_for_status()
response_data = response.json()
auth_headers = {'Authorization': response_data['token_type'] + ' ' + response_data['access_token']}

with open('biosimulators.json') as file:
    specs = json.load(file)

endpoint = 'https://api.biosimulators.org/simulators/tellurium/2.1.6'
response = requests.put(endpoint, headers=auth_headers, json=specs)
response.raise_for_status()
```

The above currently produces a 403 error:
```
HTTPError: 403 Client Error: Forbidden for url: https://api.biosimulators.org/simulators/tellurium/2.1.6
```

**Comment by bilalshaikh42** [comment]
Could you email me the access token that you received? I need to decode and see what the granted permissions are for the token.

**Comment by bilalshaikh42** [comment]
Can you paste the token that you get back into [jwt.io](https://jwt.io)? 
It should have a payload that contains `"https://biosimulations.org/permissions": [
    "write:Simulators"
  ],`
Is the field there?

**Comment by jonrkarr** [comment]
This is payload. The permissions are there.

```json
{
  "https://biosimulations.org/permissions": [
    "write:Simulators"
  ],
  "iss": "https://auth.biosimulations.org/",
  "sub": "F33xsG2LydT57smqu8asfMZ410SJ0IHP@clients",
  "aud": "api.biosimulations.org",
  "iat": 1604602304,
  "exp": 1604688704,
  "azp": "F33xsG2LydT57smqu8asfMZ410SJ0IHP",
  "scope": "read:Simulations write:Models write:Files write:Simulations read:Files read:Models read:Profile write:Profile read:Visualization write:Visualization read:Projects write:Projects",
  "gty": "client-credentials"
}
```

**Comment by jonrkarr** [comment]
This looks reasonable to me. I'm convinced that the issue relates to authorization because the code sample I sent with when I use an auth token copied from the swagger app.

For comparison here's the payload for the token generated by the swagger app. Nothing sticks out to me as a potential source of the issue.
```json
{
  "https://biosimulations.org/app_metadata": {
    "admin": true,
    "registered": true,
    "termsAcceptedOn": 1592319814539,
    "roles": [
      "admin"
    ]
  },
  "https://biosimulations.org/user_metadata": {
    "username": "jonrkarr"
  },
  "https://biosimulations.org/permissions": [
    "write:simulators",
    "test:permissions"
  ],
  "https://biosimulations.org/roles": [
    "admin"
  ],
  "iss": "https://auth.biosimulations.org/",
  "sub": "google-oauth2|117531641976036181573",
  "aud": "api.biosimulations.org",
  "iat": 1604600517,
  "exp": 1604607717,
  "azp": "mfZoukkw1NCTdltQ0KhWMn9KXVNq7gfT",
  "scope": ""
}
```

**Comment by bilalshaikh42** [comment]
Im rolling out a new version now. The issue was a capitalization typo. 🤦🏾

**Comment by jonrkarr** [comment]
I've been there. 30 minutes isn't too bad. Could have been worse.

**Comment by bilalshaikh42** [comment]
The currently deployed version is working as expected with the script. 
#1440 contains the full fix

**Comment by jonrkarr** [comment]
Works for me. Thanks!
