### ISSUE TITLE
Only import languages needed for syntax highlighting

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1405]
See instructions: https://www.npmjs.com/package/ngx-highlightjs

I tried to follow the instructions. The issue is the lack of typescript types for the individual languages. It would take me some time to figure out how to deal with this. I tried to follow the discussion [here](https://github.com/MurhafSousli/ngx-highlightjs/issues/115), but couldn't get it to work.

**Comment by bilalshaikh42** [comment]
Is json the only language needed currently?

**Comment by jonrkarr** [comment]
We're currently using just two:
- `json`
- `dockerfile`
