### ISSUE TITLE
Add additional enumerations to AlgorithmParameter.type for KiSAO ids and any

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1417]
The current types are `boolean`, `number`, and `string`. 

We need to add a couple of types
- `kisaoId`: needed to capture nested algorithms. e.g., an option of the CMBPy FBA algorithm is the simplex method (KISAO_0000550) 
- `any`: needed to capture values that are more complex datatypes such as a list of strings (e.g., list of reactions to calculate bounds for for flux variability analysis) or a dictionary (e.g., weighted probabilities of transitions in asynchronous logical simulation)

**Comment by bilalshaikh42** [comment]
closed in #1435
