### ISSUE TITLE
Build images in GitHub actions and move images to GitHub container registry

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1426]
To simplify the management of the images, we should push the images to ghcr.io rather than Docker Hub. In addition, Docker Hub often has long queues to build images -- recently, we've experienced queues as long as 1.5 days. Rather than building images in Docker Hub, they should be build in Git Hub actions (which is currently the case) and pushed to ghcr.io (and temporarily to docker.io until Kubernetes is changed to pull from gchr.io).

- [x] Tag all generated images (docker build commands) to the ghcr.io registry
- [x] Add login to ghcr.io
- [x] Push images to ghcr.io
- [x] Pull images from ghcr in Kubernetes

**Comment by gmarupilla** [comment]
I’m trying to use CLI to push latest VCell image to ghcr.io but needs authentication to setup up docker login so temporarily I pushed to docker hub.

**Comment by jonrkarr** [comment]
You can use your same GitHub username/password to push to ghcr.io: `docker login ghcr.io`

GitHub actions automatically have tokens `${{ github.token }}` which I think have enough permissions to push images to the container repo.

**Comment by jonrkarr** [comment]
For now, let's just aim to push the simulator Docker images to GHCR. This gets around the storage and pull limits of Docker Hub and consolidates the management of the ownership of these images to GitHub where we have a good setup for teams.

Moving the images for the platform from Docker Hub is GHCR is lower priority. These images aren't relevant to the community.
