### ISSUE TITLE
Improve action button for simulators app

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1436]
I am not sure if the new action button is clear enough to direct users to the correct page, or indicate that it is a button. I think the old one worked better. 
@jonrkarr  thoughts on this?

**Comment by jonrkarr** [comment]
Previously the home page didn't mention runBioSimulations or BioSimulations.

I agree chevrons look less like buttons, but they emphasize the hierarchy of tools.

**Comment by bilalshaikh42** [comment]
I think mentioning the other apps on the front page does the opposite of the intention of #1430. The `@appname` at each chevron does not make it clear that the apps are separate IMO. If anything, it seems to more tightly integrate the apps, at which point it makes more sense to keep a consistent color theme.

**Comment by jonrkarr** [comment]
Please provide more concrete suggestions.

We're trying to achieve a balance of both (a) creating distinct applications which users believe they can use separately and (b) advertising other parts of the ecosystem which are either easier entry points for users, provide more information for users, or which direct developers to how they can contribute to different aspects of the ecosystem.

The different color schemes aim to create the impression that the applications are distinct, while the similar styles aim to create the impression that they are related. As an example, Vega/Vega-lite use the same approach.

The similarities in styling are only perceptible to users if they look at multiple sites close in time. In addition to similar styling, we need to explicitly describe the relationships among the tools. This should be prominent so users don't have to discover the relationships in the documentation. Vega/Vega-Lite doesn't do a good job of this. The chevron buttons are one attempt to communicate this.

**Comment by jonrkarr** [comment]
I think we need feedback from some one more distant from the project. When we are ready to share a draft publication with co-authors, that will be a good time to ask for feedback.

**Comment by jonrkarr** [comment]
Closing until we get feedback from others.
