### ISSUE TITLE
Remove simulator Docker images from Docker Hub

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1490]
@gmarupilla I want to move the simulator images to the GitHub Container Registry. Can we remove the simulator images from Docker Hub?

**Comment by gmarupilla** [comment]
Yes, you can move, and all the latest singularity images were already identified on HPC. Also, I'll remove API, which fetches all the containers list with their versions from `dispatch-api`. As far as I know, these are the reliances per my familiarity.

**Comment by gmarupilla** [comment]
Heads up, this will break runBioSimulations until the plugin happens in this #1263 as discussed here #1480

**Comment by jonrkarr** [comment]
I removed the Docker images for the simulators from the the biosimulators Docker Hub account to avoid confusion with the new location in the GitHub Container Registry.

For now, the images for the application (e.g., simulations-api, account-api, etc.) are still in the biosimulations Docker Hub account. This is not a priority to move since the community doesn't need to access these images.

**Comment by gmarupilla** [comment]
@jonrkarr I can see new images for tellurium and CobraPy, which have URL `docker pull ghcr.io/biosimulators/<Image_name>:<Image_Version>` , But the packages of VCell and COPASI have something like this `docker pull docker.pkg.github.com/biosimulators/biosimulators_copasi/copasi:latest.` Can I create a new release to make it consistent with all others?

**Comment by jonrkarr** [comment]
I'm using two types of images:
- (Public) "Registry" images: id/tag pattern ` ghcr.io/biosimulators/<Image_name>`
- (Private) "Development" images: id/tag pattern ` ghcr.io/biosimulators/biosimulators_<image_name>/<Image_name>`

I'm using "registry" images to keep a copy of all submitted images. When other people create images, they will first push them to their own Docker Hub or GitHub accounts. The simulator submission workflow will then copy them to our account with the tag pattern ` ghcr.io/biosimulators/<Image_name>`. These images will be public.

For images that we are building, we will first push them to our own account with the tag pattern ` ghcr.io/biosimulators/biosimulators_<image_name>/<Image_name>`. These images can remain private so that the external community doesn't see them and get confused by them. When we submit them to the simulator submission workflow, the workflow will add the tag ` ghcr.io/biosimulators/<Image_name>`.

The dispatch application should use the "registry" images with the tag pattern ` ghcr.io/biosimulators/<Image_name>`.
