### ISSUE TITLE
Should runBioSimulations generate UUIDs or use MongoIDs

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1491]
Currently we are generating 128-bit UUIDs for each simulations. Having the UUID is sufficient to retrieve the results of each simulation. 
MongoDB is already assigning  96-bit ids for each document. The MongoID is slightly more guessable, [discussion here](https://stackoverflow.com/questions/11577450/are-mongodb-ids-guessable), but neither method provides absolute protection from guessing (and arguably is not needed for runBiosimulations). 

Using the MongoID for the simulation results can simplify some of the logic. 

@jonrkarr  
1. Do you think this would be okay for the purposes of the web server issue? 

2. Would this be sufficient for BioSimulations as well? That is, if a private model on BioSimulations is run, it will be sent to the runBioSimulations API as if it were submitted from the runBioSimulations frontend. This means that anyone that can guess the MongoID of the run will be able to retrieve the results. This can be remedied by including a parameter/flag for runs that originate from the BioSimulations Platform and not returning the results without authentication for those runs.  

@gmarupilla  Would using the MongoID be any different in terms of the HPC file structure?

**Comment by jonrkarr** [comment]
I think the 96-bit UUID is sufficient. The 128-bit UUIDs we're generating would be fine too. Of course any password can be guessed, but guess won't be easy.

**Comment by gmarupilla** [comment]
@bilalshaikh42 For HPC structure, it won't change anything.

**Comment by bilalshaikh42** [comment]
#1484  will be using the default MongoID to refer to simulation runs

**Comment by bilalshaikh42** [comment]
@jonrkarr
