### ISSUE TITLE
Change Authentication Audience for GitHub Actions

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1502]
The Simulators API has been changed to use its own authentication system. The "API audience" field in the authentication flow should be updated to "api.biosimulators.org"  instead of the previous "api.biosimulations.org". All the other fields and methods should stay the same. 

When running the Simulators API the value of the API_AUDIENCE in the config.env should also be changed to "api.biosimulators.org"

@jonrkarr let me know if you run into any issues, and feel free to close this if everything works.

**Comment by jonrkarr** [comment]
Thanks for letting me know. I updated Biosimulations_utils.
