### ISSUE TITLE
Show simulator name in runbiosimulations table

### ISSUE THREAD

**Issue by gmarupilla** [reproducible-biomedical-modeling/CRBM-Viz#1538]
Save the simulator and simulator version into DB

**Comment by bilalshaikh42** [comment]
This is already being done in #1520

**Comment by gmarupilla** [comment]
On the `Your Simulations` page as Ion suggested we need to fetch the Simulator name to display in the table.

**Comment by bilalshaikh42** [comment]
I see, my comment was in response to "Save the simulator and simulator version into DB." That part is being handled by the PR. 

The front end does need to be updated

**Comment by jonrkarr** [comment]
I have added the simulator to the "Your simulations" table in #1606
