### ISSUE TITLE
Docker images should not be pushed for PRs and dev branches

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1576]
- [ ] Docker images should be built for all branches to ensure that they are working 
- [ ] Docker images should only be pushed for Dev, Stage, and Deploy.
- [ ] Docker images should be pushed for Tags
- [ ] Tools script should be replaced a matrix in the GitHub actions.

**Comment by jonrkarr** [comment]
- The images are being built for all branches. 
- The images are also being pushed for those branches (and all others). This can be limited to those branches with an if statement in the tools script. Alternatively, a matrix strategy could be used to accomplish the same thing. GitHub actions support a more sophisticated matrix strategy which allows you to outline each task and the properties of each task. This could be used to describe which branches images should be built for (all) and which branches images should be pushed for (just dev, stage, and deploy). This can also be read from JSON.
- Not sure what the last two tasks mean. I assume these are notes for yourself.

**Comment by bilalshaikh42** [comment]
> * The images are also being pushed for those branches (and all others). This can be limited to those branches with an if statement in the tools script. Alternatively, a matrix strategy could be used to accomplish the same thing. GitHub actions support a more sophisticated matrix strategy which allows you to outline each task and the properties of each task. This could be used to describe which branches images should be built for (all) and which branches images should be pushed for (just dev, stage, and deploy). This can also be read from JSON.

This is exactly what was intended by the first two points. We should only push the images for the dev stage and deploy branches

For point three, a tag on the repository should also create and push the image

Point four was that we should implement this in the actions workflow itself so that we can add the customization based on the environment. There is no need to call the bash script from the action when we can just use the Run command. I had made the bash script to allow for piping the output of nx commands, but since that is handled with the matrix, it is not needed now.

3 and 4 can be done later. I can work on the first 2 or if you have a solution in mind that would work.

**Comment by jonrkarr** [comment]
Refactor the build as you like.

It took me a little bit to figure out exactly how dynamically control matrix strategies. I'm sharing this to avoid also needing to dig through examples.

You can use the alternative format of the matrix strategy to exert control over which libraries and apps are linted, tested, built, push, deployed, etc. This can be accomplished by first using any code to build a data structure such as below which captures the tasks you want executed. Each element of the `include` array corresponds to a run that you want executed.

```json
{
  "include": [
    {
      "target": "simulators", 
      "buildImage": true, 
      "pushImage": false 
    },
    {
      "target": "simulators-api", 
      "buildImage": true, 
      "pushImage": false 
    }
  ]
}
```

Next, you can use the `set-output` command to record this value to a variable which can then be attached to the `matrix.strategy` property of another job. Here's a sketch of how to put it together.
```yml
determineAffectedLibsAndApps:
  steps:
    - run: |
        echo "::set-output name=libsApps::{\"include\": [{\"target\": \"simulators\", \"buildImage\": true, \"pushImage\": false }]}"

build:
  strategy;
    matrix: ${{ fromJson(needs.getAffectedLibrariesApps.outputs.libsApps) }}
  steps:
    - if: matrix.buildImage
      run: |
        build --target matrix.target
```
