### ISSUE TITLE
Collect other types of simulation execution errors and include them in simulation error log

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1593]

**Comment by gmarupilla** [comment]
Can you please provide a sample OMEX simulation of which throws additional errors that are not yet being logged in the simulation logs?

**Comment by jonrkarr** [comment]
For example, yesterday the example simulation wasn't executing and the logs were empty. Whatever the error was, some minimal information needs to be communicated to the user.

https://github.com/biosimulators/Biosimulators_test_suite/raw/dev/biosimulators_test_suite/BIOMD0000000297.omex
