### ISSUE TITLE
Build breaks  when updating  mongoose

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1625]
It seems that the latest update of mongoose has added native typescript definitions, which are more accurate than the @types/mongoose definitions used previously. This causes some of the definition to break, mostly around some of the null validation methods added in #1550 .

There is also a mismatch between the API input and the Database input for the simulators.

I will be working to fix this in #1618

**Comment by jonrkarr** [comment]
Lets set aside the updating of mongoose for later. We need to focus on getting minimal functionality working before 12/20.

I've been trying to minimize the mismatch between the API and database. We really need to implement a test that checks this. What is the mismatch between the API and database?

**Comment by bilalshaikh42** [comment]
Agreed. I skipped the update, but did fix some of the typing issues in #1628

**Comment by bilalshaikh42** [comment]
The update revealed some type issues that were not being checked in the previous version

**Comment by jonrkarr** [comment]
The number of new type issues isn't that big. I don't seen anything that appears to be related to the changes that I made with the handling of null. The issues are related to type casting and only having some attributes defined in some places (e.g., `meta` of `BiosimulatorsMeta`).

A good test of the APIs would be to upload a document to the API, have the database save it, retrieve the document from the API and check that the documents are the same (up to `ApiResponseProperty` properties). This would help identify any unintended type casting that Mongoose is doing.

**Comment by bilalshaikh42** [comment]
Yup, I was able to fix the changes with the validators. There was a field that was spelled incorrectly, and a method that explicitly needed undefined passed to it to satisfy the compiler. The other type issues seems to be a case of the compiler being less sure of the type than  we are. That will probably just need to be cast.
