### ISSUE TITLE
Ensure that all errors in the runBioSimulations frontend are appropriately handled

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1627]
runBioSimulations was catching some errors and only displaying error messages under `development` and `test` modes. I removed this. Instead, errors should be caught by the global error handler that I setup. When errors are caught, this should provide users a generic error message.

Please check that all errors are being appropriately handled.

**Comment by jonrkarr** [comment]
`ErrorHandler` just needs to uncommented in `biosimulations/apps/dispatch/src/app/app.module.ts`

**Comment by bilalshaikh42** [comment]
This was done in #1709
