### ISSUE TITLE
Delete GitHub releases and git tags

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1632]
The GitHub releases and tags are old from before the current organization of the repo. Can they be deleted?

**Comment by bilalshaikh42** [comment]
Should be done? Can you confirm? I have removed them locally, but git by default is strange about pushing tags

**Comment by bilalshaikh42** [comment]
nevermind, still there

**Comment by bilalshaikh42** [comment]
I can run `git tag  -d [tag]` just fine locally. When I try `git push --tags` the terminal hangs. Not sure why it won't push the deleted tags, but might be a github policy?

**Comment by bilalshaikh42** [comment]
Hanging was an unrelated issue. Done

**Comment by jonrkarr** [comment]
I used `git push --delete origin tagname`
