### ISSUE TITLE
Service should update the API when checking job status

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1640]
The service runs a cron job to check the status of the job. It then sends a message to share the results. Instead, it should make a patch request to the API. 

@gmarupilla Would you want to work on this?

**Comment by bilalshaikh42** [comment]
The service will need to authenticate to the API. The backend configuration has been set up already. Here are the steps for authenticating: 
`curl --request POST \
  --url https://crbm.auth0.com/oauth/token \
  --header 'content-type: application/json' \
  --data '{"client_id":"CLENTID","client_secret":"CLIENTSECRET","audience":"dispatch.biosimulations.org","grant_type":"client_credentials"}'`
This will return a token that can be used to call the patch method for the dispatch api

**Comment by gmarupilla** [comment]
Started working on this in #1637
