### ISSUE TITLE
## do we need this wrapper?

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1668]
## do we need this wrapper?

@jonrkarr What is the intention of this wrapper around the hpc service?

---

https://github.com/biosimulations/Biosimulations/blob/69fffff23a5734bdd7d714da244db1fcd773e6e8/biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.ts#L9-L14

---

###### This comment was generated by [todo](https://todo.jasonet.co) based on a `todo` comment in 69fffff23a5734bdd7d714da244db1fcd773e6e8 in #1637. cc @biosimulations.

_Originally posted by @todo[bot] in https://github.com/biosimulations/Biosimulations/issues/1637#issuecomment-740876978_

**Comment by jonrkarr** [comment]
No. @gmarupilla set this up.

**Comment by gmarupilla** [comment]
I had a few more methods in mind to add before refactoring of code that is being done right now. So creating a new service made sense at that time, but we won't need it now. We can remove this.
