### ISSUE TITLE
Switch report format to HDF5

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1669]
## For now
No, for now lets keep our goal of runBioSimulations using CSV. For now, lets focus on the singularity containers that Akhil manually created.

## Next steps
I've written methods in Biosimulators-utils for the containers to produce reports in CSV and HDF5 formats. For now, I can have the simulators save to both CSV and HDF5. When we're ready, I can turn off the output to CSV (and re-build the containers). Today, I updated the documentation to reflect that reports will be stored using HDF5.

The one change I have made to the CSV is to flip the row/column dimension (i.e. transpose the tables). Given how SED-ML works, I think the primary axis of tables (rows) should be the datasets (recorded variables). Because HDF5 uses row-major order, this has the additional advantage of storing the trajectory of each variable in a contiguous block of storage.

Todo
- [x] Edit dispatch API for CSV files with transposed results
- [x] When we're ready to switch to HDF5, edit dispatch API to read results from HDF5 instead of CSV. We may consider implementing this in Python (with pandas and PyTables).

**Comment by jonrkarr** [comment]
This could be changed once VCell outputs HDF. All other simulators now output HDF.

**Comment by bilalshaikh42** [comment]
Done
