### ISSUE TITLE
Potentially rename names/routes of main sections

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#168]
- Models/Modeling projects/Projects
- Simulate/Simulations
- Visualize/Visualizations

**Comment by bilalshaikh42** [comment]
I'm in favor of changing models to model to emphasize the workflow.

**Comment by jonrkarr** [comment]
I like display verbs in the navigation. Its shorter and feels more active.

For routes, I think nouns might more sense. E.g.
- `/simulations/new`
- `/simulations/mine`
- `/simulations/001`

Verb routes seem a bit awkward. E.g.,
- `/simulate/mine`
- `/simulate/001`

**Comment by jonrkarr** [comment]
Renamed as proposed above
