### ISSUE TITLE
Simulation runtime should be the walltime required to execute the COMBINE archive

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1695]
Simulation runtime is currently set to the time from (a) when the simulation was submitted to (b) the latest update of the status of the simulation. This reflects the multiple things including how long the simulation is queued before beginning execution. The runtime can be obtained from the job scheduler.

Incorrect code in `biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts`
```
model.runtime = Date.now() - model.submitted.getTime();
```

**Comment by jonrkarr** [comment]
This is not critical to fix now.

**Comment by bilalshaikh42** [comment]
I think we should keep the runtime field as is to keep a record of the time that the end user needed to wait for results. 
We can add another field for the walltime as well. This way, we can break down the queue, walltime and runtime for the user. 

  Dockerhub for example lets the user know how long was spent in the queue and how long actually running.

**Comment by bilalshaikh42** [comment]
I propose we label this as an enhancement, and keep the current implementation/remove the bug tag.  Please revert if you disagree

**Comment by jonrkarr** [comment]
I agree its useful to have both pieces of information -- queue time and execution walltime. But I think it the sum could generate confusion. Users are likely to think its because the execution wall time is long when the queue time is dominating. I think we should wait to display this until we can display the individual times.

**Comment by jonrkarr** [comment]
This can now be handled by #1733

**Comment by jonrkarr** [comment]
#1733 basically handles this. If we're happy with this, and don't want to address this issue, then the duration could be removed from both 
- the simulations summary table and 
- the simulation overview tab.

**Comment by bilalshaikh42** [comment]
I would propose displaying the information, but sourcing it from the logs rather than the database entry for the simulation run

**Comment by jonrkarr** [comment]
Yes, use the `duration` from the logs.

**Comment by jonrkarr** [comment]
Done in #2267. 
- Simulations table
- Individual simulations view

Note, this requires the simulations table component to get the structured log for each simulation.

**Comment by jonrkarr** [comment]
I ended up removing runtime from the simulations table because this require logs which aren't necessarily available when the simulation first reaches non-running status.
