### ISSUE TITLE
Potentially rename "My" to "Your" models/simulations/visualizations

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#170]

**Comment by bilalshaikh42** [comment]
I prefer my as it seems consistent with other sites. I have not really seen "your" to describe customized resources much. My seems much clearer

**Comment by jonrkarr** [comment]
I'm bringing this up for discussion.

The app currently displays "My". The route for simulations is "/simulate/mine".

As a point of reference, GitHub uses "Your" -- "Your projects", "Your stars", "Your profile", etc.

**Comment by jonrkarr** [comment]
Renamed to "Your ..."
