### ISSUE TITLE
Dispatch API not returning simulation results

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1701]
Example 500 errors:
- https://dispatch.biosimulations.dev/result/5fd33217105d253d925990ab?chart=true&sedml=simulation_1&report=simulation_1
- https://dispatch.biosimulations.dev/download/result/5fd33217105d253d925990ab

**Comment by bilalshaikh42** [comment]
In progress in #1709
