### ISSUE TITLE
Replace GH_TOKEN in secrets

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1713]
The current GHCR_TOKEN in the secrets is tied to @jonrkarr 's account. This should be replaced with @biosimulations-daemon

**Comment by jonrkarr** [comment]
Yes, I didn't have the password for that account. You can replace the user name and token.

`GHCR_USERNAME` should be set to `biosimulations-daemon`.

The token needs `repo` (and child scopes) and write:packages` scopes (and child scopes)

**Comment by bilalshaikh42** [comment]
This is done, but with a caveat. 
The gh_token in still tied to @jonrkarr.
I have added token from the daemon account, but have removed the daemon accounts admin permission. 

This is because the branch protection rules are not enforced for admins, and any action with the admin token can bypass checks. This causes the branches to be merged in even if tests are failing. 

I moved over the actions that were using old token to the new one. I added push permissions for the daemon. It might make sense to add a "admin-daemon" later if that is needed.

**Comment by jonrkarr** [comment]
I don't quite understand this:
> The gh_token in still tied to @jonrkarr.

It looks like you updated the organization `GHCR_USERNAME` and `GHCR_TOKEN` secrets. This means that the GitHub actions on the biosimulations repo will no longer use the token I create previously from my account. (i.e., the token that the actions use is no longer linked to my account). Thus, I can delete the old token, ensuring it can no longer be used anywhere.

**Comment by bilalshaikh42** [comment]
It seems like you had a couple of tokens. One was for pushing images, but
there is still one that was being used by some actions. For example some of
the automated commits would be credited to you account, since it was your
token being used. I have changed those actions to use the daemon account.
There is still a token registered to you account, but I am working on
changing the actions that use that one.

**Comment by jonrkarr** [comment]
My account only had 1 token. I don't believe this is stored in any secrets anymore. I just deleted this one token. We can now be sure that token is no longer being used. 

Some of the steps may be setup to run as the user who pushed the commits (or labels). This uses the `$github.actor`/`$GITHUB_ACTOR` variable.
