### ISSUE TITLE
Move dispatch VisualizationComponent to shared library

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1717]
Move `biosimulations/apps/dispatch/src/app/components/simulations/view/visualization` to `biosimulations/libs/shared/ui/src/lib/`.

**Comment by bilalshaikh42** [comment]
If the visualization component relies on knowledge of a data model, it should not be in the shared UI library, as that should not have any dependencies to the datamodel. 

Lets create a new library called presentation or view that can be used to have shared components (across scopes) that have dependencies on the shared datamodel.

I think there are a few current UI components that also depend on the datamodel. We can move those out as well when we do this.

**Comment by jonrkarr** [comment]
The UI components do involve data models, but these are data models that are specific to the components. Their data models are different from the data models for our APIs.

For example, the data model for visualizations is the data model for Plotly. This is different than the data model for SED-ML reports.

**Comment by jonrkarr** [comment]
As talking, I understand Bilal suggestion better know:
- [ ] Move the data models for the more complex shared UI components (e.g., table, visualization, table of contents) to a separate shared library
- [ ] Change the apps to import the data models from this shared UI component data model library rather than from the shared UI component library

This would provide more separation of (a) data models from (b) the logic for rendering data encoded into these data models.

**Comment by jonrkarr** [comment]
Done
