### ISSUE TITLE
Integrate the typescript definitions for the dispatch api and frontend

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1725]
@jonrkarr will connect the front end to the API when addressing #1719 and #1721. 
#1709 contains definitions for the return type of the api in the dispatch/api-models library. These should eventually be imported into the front end to ensure typing is correct.

**Comment by jonrkarr** [comment]
Let me know when I should get started on this. Anticipating this, I also started to explicitly define a data model. This should be quick to merge.
