### ISSUE TITLE
Provide an example list of simulation ids to import

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1726]
To demonstrate the capabilities of the application to reviewers/users we should create an exported file of simulations ids. 
These simulations can have various combinations of files and simulators to represent successful and failed simulations demonstrating the feature of visibility into the failures and the role of specifying the correct simulator for given formats/algorithms.

Examples: 
1) Bionetgen reading smbl
2) Vcell running unsported algorithm
3) Same long running Omex archive on multiple simulators

**Comment by jonrkarr** [comment]
This is the idea for the test suite. For now, I'll copy omex archives I use to test the individual simulators over to the test suite. I'll organize this later this week.

Note, BioNetGen only supports the BNGL language. This will need to be used with different images from the other simulators.

**Comment by bilalshaikh42** [comment]
To clarify, for this I meant a simulations.json file exported from the front end. This could be used to demonstrate the features of various cases. A simulation run in which bionetgen was used to run an omex file with SBML would show an example of a failed simulation, with the error logs providing the explanation (unsupported language). 

It would be simpler for a reviewer to import a simulations.json file into the front end than to run various different omex files with various options themselves

**Comment by jonrkarr** [comment]
What's a simulations.json file?

**Comment by bilalshaikh42** [comment]
The file that can be exported from https://run.biosimulations.org/simulations

**Comment by jonrkarr** [comment]
Ah. I see. This is a good idea. I can add a UI element to "Import sample simulations" without the user even having to download + upload a JSON file.

I can create a JSON file within the repo for the same simulations. This can be imported as a JSON module.

**Comment by bilalshaikh42** [comment]
That would certainly work better. Is a json file even needed? Is a list of ids sufficient to load in the information?

**Comment by jonrkarr** [comment]
The file could look like this:
```
[
  {"id:" "<sim-id-1>"},
  {"id:" "<sim-id-2>"},
  ...
]
```

The simulation service is already set up to use the API to load the other attributes of each simulation. This might require a slight edit to the simulation service which manages the local storage and simulations table to accept `undefined` for the value of every other attribute.

**Comment by jonrkarr** [comment]
I can take care of making the UI work with this.

**Comment by jonrkarr** [comment]
PR #1761 adds a UI element with a button to try loading existing simulations.

The list of example simulations are stored here `apps/dispatch/src/app/components/simulations/browse/example-simulations.json`. The only attribute that's needed is the `id` attribute. I kept the others so we can easily see what each example corresponds to.

@moraru, to generate the list of example simulations
1. Clear your list of saved simulations by deleting the local IndexedDB for runBioSimulatons. Can be done from Chome developers tools (Application tab).
2. Use the submit simulations page to load simulations
3. Use the export button on the view simulations page to output the list of examples to a file.

**Comment by jonrkarr** [comment]
Implemented by `apps/dispatch/src/app/components/simulations/browse/example-simulations.json`
