### ISSUE TITLE
Refactor Dispatch component

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1740]
The dispatch view component is connected to the API in a very adhoc way. The data is directly parsed from the http response and then fed to the components. 

The app should maintain its internal state with the information about each simulations, and the results for that simulation. It should then use this information to populate the chart. 

This would also be a good time to include #1725

**Comment by jonrkarr** [comment]
Yes, this logic could be factored out into a service as its the case for the simulators app. I've started to move in this direction. The computations to get and transform the data could be moved to a service. The outputs of the methods of the service could be hooked up to a subset of the attributes:
  - `formattedSimulation$`, `statusRunning$`: basic info about the simulation
  - `logs$`
  - `dataSets`, `sedmlLocations$`, `reportIds$`: information about reports

**Comment by bilalshaikh42** [comment]
This is largely done. More specific cases have their own todos
