### ISSUE TITLE
Automate checking that Docker images can be converted to singularity as non-root user

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1754]
To enable #1602, we need to automate the generation of singularity images. There's multiple possibilities including 

- Integrating this into the workflow for accepting simulators into the registry: convert image and save image to a repository
- Make pulling the Docker image and conversion to singularity (if necessary) part of running a simulation

**Comment by gmarupilla** [comment]
In the first approach, we need to set up the GH actions container to convert docker to singularity and then use any singularity registry to save the built singularity images.

In the second approach, if we build a singularity image on every simulation, it'll take a lot of time to start a simulation unless we use some cache to cache the previously built image.

I think the first approach is way cleaner and more manageable in the long term.

**Comment by jonrkarr** [comment]
Either way, there should be a local cache of Singularity images so images don't need to be pulled for each simulation. It the cache gets too big, we can use a LRU policy and start deleting images that haven't been used recently.

I could incorporate generation of Singularity images into the [register simulator workflow](https://github.com/biosimulators/Biosimulators/blob/dev/.github/workflows/commitSimulator.yml) and push the images to SingularityHub. This has the additional advantage of making the Singularity images publicly accessible.

@bilalshaikh42 preference?

**Comment by bilalshaikh42** [comment]
I like the idea of posting to singularity hub. Then, the simulators database can include an additional format in the images section of the metadata. 
The dispatch job can then use the singularity hub URL for each simulation run.  I assume that singularity, like docker, will keep a local cache automatically and will not re download the singularity images that it does not need to.

**Comment by bilalshaikh42** [comment]
Though, I think it would be better to have a separate action to build the singularity images that is triggered by an update to the container registry. This would account for any rebuilds that we might do, as well as test tags that we need to push

**Comment by bilalshaikh42** [comment]
Singularity Hub seems to a be an academic project that could fit our needs. It would be especially important that we use a local cache however 
https://singularityhub.github.io/singularityhub-docs/2019/security-release/

**Comment by jonrkarr** [comment]
I can set this up as an action on pushing containers to GHCR. That's better than what I suggested.

**Comment by bilalshaikh42** [comment]
So looking into it more, I don't think singularity hub would work. It seems to require connection to git repo with recipe files, and does not have a way to push built images.

**Comment by bilalshaikh42** [comment]
Looking at this documentation here, I think it might actually be sufficient to just run the singularity pull command from the GHCR.

Doing something such as  singularity pull docker://ghcr.io/biosimulators/gillespy2:1.5.6 should create the image for us, and cache it. We might just be able to add this to the sbatch script. I can look into this. 

https://singularity.lbl.gov/docs-docker

**Comment by bilalshaikh42** [comment]
I did just try this, and it seemed to have worked. Rather than point singularity to a precreated image on the cluster, I pointed it to the dockerhub container registry URL.  The image was downloaded, converted, cached, and then run. This took longer than the usual simulations, but hopefully the next run will be faster.

**Comment by bilalshaikh42** [comment]
I would like to run this by @mpw6 and @moraru, but it seems that we can just change our script slightly, and not worry about building the images at all

**Comment by jonrkarr** [comment]
Looking more, Singularity Hub might be tough. Overall, it seems to be an academic project that's still a bit immature. In addition, to what Bilal suggested, it has a bunch of limits on number of builds, pulls, etc. I don't think it was designed with the intention of someone using this to build a domain-specific container registry. I think we'd need to reach out to them to allow our account to bypass their limits.

Given this and what Bilal noted, I think we should ignore Singularity Hub. I couldn't find any other public Singularity Hub. I don't think we should try to run our own version of Singularity Hub.

**Comment by bilalshaikh42** [comment]
The image was created and cached the same way that it would have been if done manually 
`INFO:    Creating SIF file...
INFO:    Build complete: /home/FCAM/crbmapi/.singularity/cache/oci-tmp/4674a8025b15e1dde4113e0b15b426af6aa93f456345b0dcef022f58609af161/gillespy2_latest.sif
INFO:    Image cached as SIF at /home/FCAM/crbmapi/.singularity/cache/oci-tmp/4674a8025b15e1dde4113e0b15b426af6aa93f456345b0dcef022f58609af161/gillespy2_latest.sif
`

**Comment by bilalshaikh42** [comment]
I can confirm that the image did not need to be built the second time, it proceeded straight to running it. There was no output however, but actually an error. The docker image is able to produce the correct output. @jonrkarr is the gillespy2:latest tag up to date?
 XPaths must reference unique objects. The following XPaths do not match any objects:
  - /sbml:sbml/sbml:model/sbml:listOfSpecies/sbml:species[@id="BUD"]

**Comment by jonrkarr** [comment]
This looks good to me. The simulation correctly generated an error because the SED-ML references an target (XPATH) that doesn't exist in the SBML file. In this case, BUD is a variable, not a species. The SED-ML file in BioModels is actually invalid.

The target should have been this:
```
/sbml:sbml/sbml:model/sbml:listOfVariable/sbml:variable[@id="BUD"]
```

Note, I haven't yet had time to cleanup the examples collated into biosimulators_test_suite. Some of the these are invalid. We didn't notice earlier when we were saving all predictions rather than those requested by SED-ML.

**Comment by bilalshaikh42** [comment]
Huh. It seems then that the gillespy2 image did not update yesterday as I had thought. The current singularity image does produce the output, like it use to before the fix

**Comment by bilalshaikh42** [comment]
I was able to confirm with the tellurium image, that a direct pull from dockerhub will work. I will confirm that this is okay with mike and ion and then update the service

**Comment by bilalshaikh42** [comment]
https://sylabs.io/guides/3.7/user-guide/singularity_and_docker.html#best-practices
@jonrkarr  This link provides some documentation into the constraints that the docker image must satisfy to be compatible with this approach. I dont see us running into any issues, but we should pin this to the documentation to ensure that all containers built for simulators are following these priciples

**Comment by bilalshaikh42** [comment]
This seems to be a registry where we can upload singularity containers independently of running them on the hpc
https://cloud.sylabs.io/library

The @biosimulators-daemon account has been connected to the biosimulators username on syslabs.

**Comment by bilalshaikh42** [comment]
Here is an example container pushed  to the registry, https://cloud.sylabs.io/library/biosimulators/default/gillespy2
 I was able to use the online builders that are provided. It is also possible to use the cli

**Comment by jonrkarr** [comment]
I created biosimulators/Biosimulators#24 to build workflow for generating and pushing Singularity images to Syslab

**Comment by jonrkarr** [comment]
Since Docker images can easily be converted to Singularity, we have decided not to push images to Syslabs, at least until we can get a larger quoata.

Todo
- [x] Add Singularity conversion to image validation workflow
- [x] Add notes about compatibility with Singularity to BioSimulators tutorial and image standards
- [ ] Add documentation about how to use images with Singularity to BioSimulators tutorial

**Comment by jonrkarr** [comment]
Done except merging docs in dev branch
