### ISSUE TITLE
Update version of VCell image in ghcr.io

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1791]
The [Villar example](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Vilar-PNAS-2002-minimal-circardian-clock.omex) doesn't work with the version of VCell at `ghcr.io/biosimulators/vcell:latest`. The OMEX file does work with runBioSimulations. I believe the image need to be pushed to `ghcr.io`.

**Comment by gmarupilla** [comment]
I merged the latest changes in [Biosimulators_vcell](https://github.com/biosimulators/Biosimulators_VCell) from [vcell](https://github.com/virtualcell/vcell) and pushed the docker image to ghcr.io, and built singularity on HPC with version `7.3.0.1p`. The [OMEX](https://github.com/biosimulators/Biosimulators_test_suite/blob/dev/examples/sbml-core/Vilar-PNAS-2002-minimal-circardian-clock.omex) file should work now. To enable this from UI, we need to add the `7.3.0.1p` version to VCell in runBioSimulations. When #1798 is merged and deployed, the Vilar example will work.

**Comment by moraru** [comment]
@gmarupilla the patch branch is the wrong one to use for images as it does not have any of the omex and sedml fixes in it, please pull back ASAP.  You must merge from the trunk until I tell you to make a new reference tag.

**Comment by moraru** [comment]
@gmarupilla commit [c3f834](https://github.com/virtualcell/vcell/commit/c3f834cd0e89ea2e76497bd4c8bff2c6887e51e7) is vcell repo ready
Please:
- [x] create new tag 7.3.0.07
- [x] deploy vcell alpha
- [x] merge source on biosim repo
- [x] make new image
- [ ] update runbiosimulations and docker repository with new image

**Comment by gmarupilla** [comment]
I created a tag with [7.3.0.07](https://github.com/biosimulators/Biosimulators_VCell/releases/tag/7.3.0.07), with the latest changes on [Biosimulators_vcell](https://github.com/biosimulators/Biosimulators_VCell), but I'm having a hard time pushing the image to the ghcr.io using the [CD pipeline](https://github.com/biosimulators/Biosimulators_VCell/runs/1590240398?check_suite_focus=true). I can build a singularity image on HPC after a successful push to ghcr.io. I asked @bilalshaikh42 for help to fix it because I don't have enough access permissions for making the image public.

**Comment by jonrkarr** [comment]
The CD pipeline is rerunning.

I'm working toward changing the pipeline NOT to push to the top-level container namespace (`ghcr.io/biosimulators`). Simulator repos should NOT push here. The validation workflow will push containers to that namespace. This allows us to separate between the images we're building for simulation tools and all images received by BioSimulators. Simulator repos should push to other namespaces such as  (`ghcr.io/biosimulators/biosimulators_vcell`)

**Comment by bilalshaikh42** [comment]
Just seeing this now. Akhil were you able to push the image?

**Comment by jonrkarr** [comment]
Its now tagged with `ghcr.io/biosimulators/vcell:7.3.0.07` and `ghcr.io/biosimulators/vcell:latest`

**Comment by moraru** [comment]
I don't see 07 in the version list on the run page.  Refreshing browser did not help.

**Comment by gmarupilla** [comment]
#1798 has the required change.
