### ISSUE TITLE
Pull latest versions of AMICI, COPASI, and GillesPy2 images into runBioSimulations simulation service

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1792]
These versions fix the `sedml.variable.modelReference` issue that Ion raise yesterday.

- `ghcr.io/biosimulators/amici:0.11.11`
- `ghcr.io/biosimulators/copasi:4.30.233`
- `ghcr.io/biosimulators/copasi:4.29.227`
- `ghcr.io/biosimulators/copasi:4.28.226`
- `ghcr.io/biosimulators/gillespy2:1.5.6`
- `ghcr.io/biosimulators/gillespy2:1.5.5`
- `ghcr.io/biosimulators/gillespy2:1.5.4`

**Comment by bilalshaikh42** [comment]
Done.
