### ISSUE TITLE
sim results from cvode solver in vcell seem to be missing

### ISSUE THREAD

**Issue by moraru** [reproducible-biomedical-modeling/CRBM-Viz#1796]
multiple sim run with vcell shows only 4 out of 6 sims:
https://run.biosimulations.org/simulations/5fdda8358b0da07b332ffa5a
both missing sims are the two cvode alg ones

running edited omex with single sim using cvode produces error 500 on viz attempt (presumably no results found)

this is reproduced with two different single sim models:
https://run.biosimulations.org/simulations/5fdf02f5391352356026ec99
https://run.biosimulations.org/simulations/5fdf08f0391352059f26ecb9

**Comment by bilalshaikh42** [comment]
Does this look correct for the output?

```
-bash-4.2$ tree
.
├── ___example_biosim_vilar
│   ├── ___example_biosim_vilar_ODE_stochastic_0.stochInput
│   ├── ___example_biosim_vilar_ODE_stochastic.stochInput
│   ├── tsk_0_0.csv
│   ├── tsk_0_1.csv
│   ├── tsk_0_2.csv
│   ├── tsk_0_3.csv
│   ├── tsk_1_0.csv
│   └── tsk_1_1.csv
├── job.error
└── job.output

1 directory, 10 files

```

**Comment by moraru** [comment]
Yes, correct.
- the 0_0 and 0_1 files are the ones that aren't showing up in the viz selector
- also, the .stochinput files should be ignored and are harmless - litter due to Akhil forgetting to put the cleanup routine for intermediate files in one of the solver handlers (Gibson); and they'll go away after we update the VC image

**Comment by bilalshaikh42** [comment]
This seems to be the same root issue as #1790 
Does this contain the correct output? 
https://run.biosimulations.org/simulations/5fdf1065f10d6881fa393b44#tab=design-viz

**Comment by moraru** [comment]
yes, yay!
