### ISSUE TITLE
Some successful simulation runs do not show log or results

### ISSUE THREAD

**Issue by moraru** [reproducible-biomedical-modeling/CRBM-Viz#1797]
single sim run with tellurium succeeds, but two links seem broken

the job is:
```json
  {
    "id": "5fdf1c4ff10d68cf08393b54",
    "name": "tl-vilar1",
    "email": null,
    "simulator": "tellurium",
    "simulatorVersion": "2.1.6",
    "submittedLocally": true,
    "status": "SUCCEEDED",
    "runtime": 8501,
    "submitted": "2020-12-20T09:41:35.335Z",
    "updated": "2020-12-20T09:41:43.844Z",
    "resultsSize": 28050,
    "projectSize": 9058
  }
```

clicking on either log or viz produces error 500 empty page

clicking on download works, returning a zip file containing logs and a pdf file of results report which looks ok

**Comment by jonrkarr** [comment]
I suspect this is related to the simulation service, rather than the tellurium image. The tellurium image has no role in whether logs are saved, retrieved, or displayed.

**Comment by moraru** [comment]
i have same problem running with vcell image - it runs succesfully, download button works, viz and log links show error 500

https://run.biosimulations.org/simulations/5fdf08f0391352059f26ecb9

**Comment by jonrkarr** [comment]
In this instance, the problem is because the results API returns a 404 error
https://run.api.biosimulations.org/results/5fdf08f0391352059f26ecb9?sparse=true

The UI is just passing along this error to the user

**Comment by moraru** [comment]
> In this instance, the problem is because the results API returns a 404 error
> https://run.api.biosimulations.org/results/5fdf08f0391352059f26ecb9?sparse=true
> 
> The UI is just passing along this error to the user

but why is the download button working?  are there different API calls to fetch the results, some which work and some which do not?

**Comment by jonrkarr** [comment]
They're different endpoints. 
- 1 endpoint retrieves a zip archive of CSV files which is produced when the simulation results are first saved. 
- A second endpoint retrieves the results as a JSON data structure.

**Comment by moraru** [comment]
It actually is specific to tellurium, and it actually depends on the omex file.
This happens when tellurium produced PDF instead of CSV.
The API is correct as it is being asked for CSV but there is none.

**Comment by jonrkarr** [comment]
To help us debug, please post the OMEX files associated with each error.

Whether or not a CSV file is produced depends on whether a `report` is defined in the SED-ML file. tellurium not generating a CSV file is not a tellurium error.

This sound like a problem with the simulation results service. The service should not fail when the simulator correctly did not produce CSV files.

**Comment by moraru** [comment]
1. I think the service is correct with regard to CSV.  It has no way of knowing whether there should be or not a CSV output, it just says there isn't one.

It is the UIs job to populate the links depending on the outcome and handle the absence of the CSV file. If there is no CSV data, thus nothing to visualize, the link for visualization should not be there.

2. For the log files, I am not sure whether the service or the UI needs fixing.  The log files are there (retrievable by download) and the link to logs should work whether or not the job produced a CSV file or not.  They should *always* be retrievable, and in fact, they are retrievable in case of job failure.

Link to log files not working is definitely a bug.

**Comment by jonrkarr** [comment]
This requires more discussion. Right now, I don't think that the API response is distinguishing between (a) results were not generated (i.e. not results were requested) and (b) results could be returned. The UI needs the API to return two different responses for these scenarios because the latter is an error that needs to be communicated to users. Until this is the case, we cannot complete the UI.

For now, I have changed the UI to assumed that the errors are due to the former.

**Comment by moraru** [comment]
Something went wrong with the change in UI.  The viz column disappeared completely and clicking on any of the actual runs has the viz part grayed out, even for the runs that do have CSV results.

**Comment by moraru** [comment]
on the other hand, viewing the logs now works on all runs, no longer returns the error 500 on any of them

**Comment by bilalshaikh42** [comment]
Is this resolved? 
#1851 should provide more details on the available outputs
