### ISSUE TITLE
What error code does the results API return when the simulation run correctly didn't generate a report?

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1801]
Ion raised an issue about runBioSimulations incorrectly handling the case when a simulation run doesn't request a report (no `sedml:report` element), and therefore the simulator doesn't generate any reports.

In this scenario, does the results API return an error? If so, what is the code/message? and is this a distinct error code/message distinct from that of other responses such that the frontend can correctly handle this case?

**Comment by bilalshaikh42** [comment]
I am having a bit of trouble following the discussion across the issues, so excuse any repetitive discussion. 

Essentially, the results endpoint will return the results if they are available and return a 404 if they are not. It is not aware whether or not the results were supposed to be generated by the sedml. All it know is whether or not the results exist in the database. 

The results are added to the database after the simulation run successfully finishes. This is done by scanning the output directory for any and all csv files, and uploading them one at a time to the API.  If there are no files output, then there will not be any results that are uploaded.

The run endpoint contains information about the simulation run. Assuming it has succeeded,  the status will reflect that it is successful, regardless of the presence of the results. This status is determined by the state of the job on the HPC.

**Comment by bilalshaikh42** [comment]
I see the problem now, which is that the front end will enable the chart tab upon the simulation run being successful rather than based on the presence of the results. The quickest fix to this would be to change the conditional to check if there are results reported before giving the option to view the visualization.

**Comment by jonrkarr** [comment]
No need to try and fix this right now. We can discuss when we meet. I'm adding issue to help track what needs to be done.
