### ISSUE TITLE
Add information about whether reports were generated to `/run/{id}` dispatch API

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1802]
Similar to #1801, we need to distinguish between cases where 

- A simulation run correctly generated no reports (because the SED-ML didn't include a `report` element). In which case, there is no simulation data which can be visualized.
- API could not returned the outputted simulation results.

In the former case, even we a simulation succeeds, we don't want to display a button in the simulations table to visualize results that were never generated. Currently, the simulations table relies on the `/run/{id}` endpoint. Information about reports, is available from a different endpoint. Because the simulations table isn't currently receiving enough information to know whether to display a "Viz" results button, I've commented out that button.

To restore the button, we need to do one of the following:
- Have the simulations table also get information from the results structure endpoint
- Return information about whether at least one report was generated with the `/run/{id}` endpoint. 

From the UI standpoint, the latter would be easier.

**Comment by bilalshaikh42** [comment]
The results structure endpoint was the older endpoint used when retrieving the results was a two step process. I am not sure if it still works/provides correct information and was planning to remove it

The run/id endpoint does not return any information if there was no results generated. It would simply return a 404 if it is unable to find any results.

**Comment by bilalshaikh42** [comment]
#1931 now sets status as "processing" when running and "completed" when results have been produced. If  a run is "completed" but there is  a 404 on the reports, then there was no report produced.
I actually need to run a couple of examples to test that assertion. Its possible that the API might not be able to handle an empty report

**Comment by bilalshaikh42** [comment]
This is handled by the logs
