### ISSUE TITLE
Some simulations remain in running state and never complete

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1804]
Example: https://run.biosimulations.org/simulations/5fe02efd174a537213e9d9ae
[OMEX](https://github.com/biosimulators/Biosimulators_test_suite/raw/dev/examples/sbml-core/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint.omex), although I don't think this is related to the specific OMEX file

**Comment by jonrkarr** [comment]
This eventually failed, but it took much longer than it should have

**Comment by bilalshaikh42** [comment]
Based on the logs, this seems to be an issue with the HPC and not the current codebase. We are switching over the host for the jobs to a dedicated node, which would help us debug this. 
I'll close and we can create a new issue if we run into further issues

**Comment by jonrkarr** [comment]
Here's another example of a simulation that was in the CREATED state for a while
https://run.biosimulations.dev/simulations/5ff0e1a589a8e747380ad097

**Comment by bilalshaikh42** [comment]
This is caused by the ssh connection to the HPC not responding. I am planning to work on handling the error in #1869
