### ISSUE TITLE
How are static routes generated for the sitemap?

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1823]
Are static routes generated manually? If so, would adding them to the python script and then outputting all the routes to the same                   sitemap.xml file be equivalent?

**Comment by jonrkarr** [comment]
Short answer: yes.

The static routes are generated by hand. They're saved to an XML file.

There's no reason why the sitemap has to be divided into 2 files. I just chose to do it that way. Equivalently, all of the URLs could be in on file.

Yes, alternatively the Python script could produce a single sitemap XML file with all of the "static" and dynamic (those which depend on the content in the database) paths.

**Comment by bilalshaikh42** [comment]
Great. I made a change to the generation in #1824  and also added the routes for the simulator standards. 
Let me know if there are any issues.

**Comment by jonrkarr** [comment]
I glanced. It looks good. Google will complain if it isn't.

Thanks for including the routes for the standards pages.

Ideally, the whole sitemap would be dynamically generated from the application. I couldn't figure out a way to do it. With enough effort I'm sure we could figure out a way, but with relatively little effort we can get 95% of the way to automating the sitemap. The static routes just have to be manually updated.
