### ISSUE TITLE
Dispatch app is polling simulation runs that have been completed

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1881]
On run.biosimulations.org, loading the example simulations causes the app to poll for their status, even though all are marked as completed.

**Comment by jonrkarr** [comment]
This might be related to the local storage issue #1882. If the state can't be saved, it could keep polling.

**Comment by jonrkarr** [comment]
The status will be polled while either of these conditions are true:
- The status of a simulation is `CREATED`, `QUEUED`, or `RUNNING`
- The status of a simulation `SUCCEEDED` and `resultsSize` is `undefined`

(a) The `resultsSize` attribute is undefined for the previously run "example" simulations. This will cause the polling for status to repeat forever. The "example" simulations need to be re-run, which I did in #1894 . @bilalshaikh42 do you see this problem when "your simulations" only includes simulations that you've run recently? My browser doesn't keep polling for status if I only have newer simulations.

(b) The reason that the polling checks for `resultsSize` is that it needs `resultsSize` to determine whether to display a download button. It look like the `resultsSize` is updated after status is set to SUCCEEDED. @bilalshaikh42 is that correct?

**Comment by jonrkarr** [comment]
@bilalshaikh42 do you still see this issue?

**Comment by bilalshaikh42** [comment]
Nope, seems to be resolved
