### ISSUE TITLE
Polling in dispatch app causes simulations to be repeated in table of contents

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1883]
The "mobile table" is repeating the simulations on every poll. This causes the list of simulations to get longer and longer
![RepeatedList](https://user-images.githubusercontent.com/32490144/103684943-60865780-4f5a-11eb-9b3e-d91b570e092b.png)

**Comment by jonrkarr** [comment]
This is fixed in #1894. Elements weren't unregistered themselves from the TOC upon their destruction. This is fixed for all components that use the TOC.
