### ISSUE TITLE
Image building is very slow

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1942]
Building the singularity image on each run is very slow. Even though the layers are cached, the image is still rebuilt for simulators that already exist.
We can remove the singularity pull command on each run. This will lead to the problem that images will not be updated if a change is made for a new tag. A simple API endpoint should be sufficient to provide an automated way to update images

**Comment by jonrkarr** [comment]
I think this could be done by breaking down the pulling of the Docker image and building of the Singularity image into separate steps:
1. Use Docker to check if there's a new version and pull the version if needed. This will rely more directly on Docker's cache.
2. Inspect Docker's output to detect whether Docker pulled a new version.
3. Build a singularity image only if Docker pulled a new version.

```bash
IMAGE_UP_TO_DATE_MESSAGE="Image is up to date"
simulator_docker_image=ghcr.io/biosimulators/{simulator-id}:{simulator-version}
dockerLog=$(docker pull $simulator_docker_image)
if [[ "$dockerLog" != *"$IMAGE_UP_TO_DATE_MESSAGE"* ]]; then
    singularity build {simulator-id}.sif docker://$simulator_docker_image
fi
```

I think this would work on my local machine. Would this work in UConn's HPC environment?

**Comment by bilalshaikh42** [comment]
No, we do not have the ability to use docker on the HPC

**Comment by jonrkarr** [comment]
I see. That removes one option.

**Comment by bilalshaikh42** [comment]
The api endpoint would actually be rather simple. We already have all the code for making a ssh connection and running a command. I can get a PR up shortly

**Comment by jonrkarr** [comment]
I know that Docker can't be used to execute images in the HPC environment, but can Docker be used to pull images?

**Comment by bilalshaikh42** [comment]
No, docker is not present on the environment at all.

**Comment by jonrkarr** [comment]
I think you're right about needing to build a service for this. I can't see a way to do this with Singularity alone. I checked the Singularity API as well. I don't see anything that I think would help with this.
