### ISSUE TITLE
Dispatch app "crashes" after long period of inactivity

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#1950]
if the network disconnects during an update, the error handler catches the error and displays an error page. This should be handled at the network call level rather than globally, so that network calls that timeout or fail to connect can be repeated after some time. 

This is done on the backend services when communicating with the api

**Comment by bilalshaikh42** [comment]
#1631  is where the errors need to be caught

**Comment by jonrkarr** [comment]
Yes, the error handler is setup to catch all otherwise uncaught exceptions. As you point out, not all exceptions should be treated as errors. Where relevant, individual errors should be caught.

**Comment by bilalshaikh42** [comment]
This seems to be resolved for most cases
