### ISSUE TITLE
https://biosimulators.org/standards/simulation-reports creates RunTimeError

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1976]
Transferred from biosimulators/Biosimulators#104

**Please describe the bug**
Opening
https://biosimulators.org/standards/simulation-reports
creates a RunTimeError

**Please describe how to reproduce the bug**
Open https://biosimulators.org/standards/simulation-reports in Firefox

**How should BioSimulators have behaved**
No RunTimeError.

**Screenshots**
![image](https://user-images.githubusercontent.com/900538/104593433-febba100-566f-11eb-9b84-bab4de63466c.png)

**Environment (please complete the following information):**
Browser Firefox 84.0.2 (64-bit) on Linux Ubuntu

**Comment by jonrkarr** [comment]
I can't replicate this issue under Windows or Linux with Chrome or Firefox. I even used the same version of Firefox in Ubuntu.

@bilalshaikh42 is error logging now integrated into the UI apps?

**Comment by bilalshaikh42** [comment]
Yes, it is but only on the dev branch so far. So any errors on .org won't be reported untill a new deployment

**Comment by bilalshaikh42** [comment]
I see that the issue was created from outside the team. This may just be bad timing when the server was down/being changed.

**Comment by jonrkarr** [comment]
I think this issue can be closed. I can't see a reason why this would cause an error, and we have no log to inspect. Once Bilal's logging system is deployed, such errors will be logged and we'll be able to debug them much more easily.
