### ISSUE TITLE
Add alternative mechanism to input COMBINE archives to dispatch app by URLs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2015]
- [ ] Add input box for URL to webform
- [ ] Change validation to accept 1 of (a) a URL or (b) an uploaded file
- [ ] Allow URL input to be populated from a URL query argument
- [ ] Update function that calls dispatch API to submit simulation

**Comment by jonrkarr** [comment]
Can be done after Bilal's todos in the [project](https://github.com/biosimulations/Biosimulations/projects/18)

**Comment by bilalshaikh42** [comment]
This is ready to be implemented on the front end
