### ISSUE TITLE
Make Open API Schema valid

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2025]
There are a few errors in the open api schemas. For example, the simulator api as some errors that can be seen with SwaggerHub: 

https://app.swaggerhub.com/apis/bilalshaikh42/bio-simulators_api/0.1

**Comment by jonrkarr** [comment]
That's surprising. I assumed that the library would only be able to create valid schemas.

**Comment by bilalshaikh42** [comment]
It seem that we provided some additional fields in some cases where they are not applicable. I also have not bothered to add the security scopes which is the other problem

**Comment by bilalshaikh42** [comment]
The security issue should be covered by #1949 
The other issue seems to be providing "examples" for enums. The examples are just defined as valid enumerations, so should not be provided separately.

**Comment by jonrkarr** [comment]
To avoid accumulating errors, here's a tool that could be incorporated into the CI workflows, either as a unit test or as a separate step.
https://github.com/IBM/openapi-validator

**Comment by jonrkarr** [comment]
I fixed a few of the issues found by SwaggerHub.

I tried the IBM validator. This identifiers many, many more issues. This looks for more more issues beyond SwaggerHub including best practices such as capitalization of enumerated values.

**Comment by jonrkarr** [comment]
Checked APIs with Swagger. Corrected errors
- API: Handling `null` type for `DescribedIndentifier`
- Simulators API: Documented of scopes
- COMBINE API: Removed unused schema

Remaining warnings
- COMBINE API: ignored descriptions of attributes typed by references

**Comment by jonrkarr** [comment]
Added build to test API specs
