### ISSUE TITLE
Return to top button does not account for #tab in url

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2034]
**Please describe the bug**
When clicking the return to top button on the list of algorithms in biosimulators, rather than scrolling to the top, the page switches to the first tab

**Please describe how to reproduce the bug**
1. Go to https://biosimulators.dev/simulators/tellurium/latest#tab=algorithms
2. Scroll down
3. Click the return to top button
4. See the tab switched to the overview page

**How should BioSimulations have behaved**
Scrolled to the top of the page

**Additional context**
I assume this is happening because the button assumes that the # is followed by an anchor. This likely extends to other pages as well

**Comment by jonrkarr** [comment]
My browser don't switch to a different tab. It scrolls to the top, but not quite all the way up. I fixed (PR #2082) how far it scrolls up so it scrolls all the way to the top.
