### ISSUE TITLE
Save table state to local storage

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2059]

**Comment by jonrkarr** [comment]
Do you mean the sorting and active filters?

**Comment by bilalshaikh42** [comment]
yup, this would be more convenient when looking at multiple entries sequentially

**Comment by jonrkarr** [comment]
That's similar to what I've tried to do with URL fragments.

**Comment by bilalshaikh42** [comment]
I see, I didn't notice that this was already being done for the filters.
The sorting information is not saved however, which is what I was noticing
when noting the issue

**Comment by jonrkarr** [comment]
Sorting could be added. 

I felt we should manage such application state in a way that's compatible with the browsers forward/backward navigation, and ideally which can be decoded/encoded into URLs to users can directly navigate to a state. Integration with forward/backward could be achieved with a queue. Working with URLs requires encoding/decoding state into query arguments or fragments. This allows us to use the browser to keep track of history; we don't need to implement a separate queue.

I choose to encode state into URL fragments. Basically, I'm using fragments in the same way that query arguments are usually used with fragments (i.e., key/value pairs). I should see whether query arguments would work equally well.

To handle URL fragments better, I think we need an application state service that manages this.
