### ISSUE TITLE
Simulators API permissions are broken

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2159]
The "GitHub Simulators Actions" Auth0 application can't make changes to the database. The application does have the permissions that Auth0 complains about below. I can't make change using the Swagger app either.

URL: https://api.biosimulators.org/simulators/copasi/4.30.233

Error:
```
  "error": [
    {
      "status": "403",
      "title": "Forbidden",
      "detail": "You do not have the needed permissions: write:Simulators"
    }
  ]
```

**Comment by jonrkarr** [comment]
This is what I get from `/auth/permissions`. 

One difference I see is the capitalization of the scopes (`write:simulators` vs `write:Simulators`).

```json
{
  "https://biosimulations.org/app_metadata": {
    "admin": true,
    "registered": true,
    "roles": [
      "admin"
    ],
    "termsAcceptedOn": 1592319814539
  },
  "https://biosimulations.org/permissions": [
    "write:simulators",
    "write:SimulationRun",
    "test:permissions"
  ],
  "https://biosimulations.org/roles": [
    "admin"
  ],
  "https://biosimulations.org/user_metadata": {
    "username": "jonrkarr"
  },
  "iss": "https://auth.biosimulations.org/",
  "sub": "google-oauth2|XXXXXXXXX",
  "aud": "api.biosimulators.org",
  "iat": 1613257141,
  "exp": 1613264341,
  "azp": "XXXXXXXXXX",
  "scope": ""
}
```

**Comment by jonrkarr** [comment]
I fixed the issue with the "GitHub Simulators Actions" Auth0 application.

**Comment by bilalshaikh42** [comment]
Taking a look at the auth0 settings now. How did you fix the issue? I  see that the role based auth was turned off, which should  not be the case. Did you use a workaround?

**Comment by jonrkarr** [comment]
The issue was with something else unrelated.

The user permissions haven't been working for some time. I posted another
issue about this a few weeks ago.

**Comment by bilalshaikh42** [comment]
I re-enabled the RBAC, and made sure that the proper permissions are granted to the github actions as well as the admin role. Both should be working now.

**Comment by bilalshaikh42** [comment]
@jonrkarr Could you confirm if this is resolved? I can take another look if not

**Comment by jonrkarr** [comment]
Its working again.

I saw RBAC was off, but wasn't sure if this should have been on.

Also, I added permissions to the simulators scopes to the superuser role.
