### ISSUE TITLE
Simulators API fails for larger documents (triggered by new test cases)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2160]
This example (111.2 kb) fails with 500 error: [specs.json.zip](https://github.com/biosimulations/Biosimulations/files/5976972/specs.json.zip)

Now that the test site has more test cases, results for 3 of 8 simulation tools couldn't be uploaded to the registry.

Temporarily, I manually worked around this by setting some of the logs for passed test cases to `''`. With that one change, the API accepts the results. Other changes that reduce the total size of the document also enable the API to accept the payload.

**Comment by bilalshaikh42** [comment]
The default upload limit is set to 100kb, though I am not sure why. I updated the limits for the other applications as we ran into the limit, but have not yet for the simulators api. I'll make sure to update it.
