### ISSUE TITLE
Enable strict template checking

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2185]
At some point during configuring the workspace, strict template checking was turned off. This has led to the compiler missing a large number of potential errors in the HTML templates of the frontend apps and these errors have accumulated. The checking needs to be re enabled and the errors corrected. 

- [x] Dispatch
- [x] Platform
- [x] Account
- [x] Simulators

**Comment by bilalshaikh42** [comment]
- [ ] Dispatch
- [ ] Platform
- [ ] Account
- [ ] Simulators

**Comment by jonrkarr** [comment]
I addressed a bunch of issues in #2267.

There's a modest number of issues left with the platform app
