### ISSUE TITLE
Several dependencies should be moved from devDependencies to regular dependencies

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2213]
I believe several dependencies required to build the applications should be moved from devDependencies to regular dependencies in `package.json`

Examples
- plotly
- npnslider
- fortawesome
- flexlayout
- forms
- ionic/storage
- ngx-highlight
- mongoose

**Comment by bilalshaikh42** [comment]
So this was a optimization I made to keep the docker images small. Angular
is essentially compiled and linked via webpack which bundles all the
scripts into a single/module of javascript files. When serving this to a
user, we are just presenting static files, and not actually installing the
package described by the package.json.

This means all of the runtime libraries for the front end are only needed
to build the front end. Including them in the dev dependencies allows the
front end to be built,  while keeping the back end docker images small.
This reduced their size by nearly a gig in some cases.

The backend apps actually need to have their dependencies installed. So
those are the only ones included in the dependencies section.

**Comment by jonrkarr** [comment]
That make sense.
