### ISSUE TITLE
Vcell example combine archive fails to run

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2244]
This is the namespace issue discussed previously

**Comment by jonrkarr** [comment]
I fixed the namespace of the Vilar example. I confirmed that VCell 7.3.0.07 runs the corrected file. I also confirmed it works through the dispatch app.

Note, VCell 7.3.0.13 appears to have other issues that prevent it from running this and other examples. See /biosimulators/Biosimulators_VCell#60.
