### ISSUE TITLE
resultsSize missing from some simulation runs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2272]
`resultsSize` is missing from this simulation run even though results were saved. The simulations table is using that attribute to determine whether visualization and export buttons should be displayed.
https://run.api.biosimulations.dev/run/6037ee3b6e279f120495462c

If this has already been fixed and this example was run before the fix, this can be closed.

**Comment by bilalshaikh42** [comment]
I see am seeing the issue. it seems to be happening intermittently. I'll investigate it and check the logs. I didn't write this part of the code, so not sure what could be happening.
