### ISSUE TITLE
Zip file is empty for some simulation runs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2301]
Example
http://run.biosimulations.dev/simulations/6043193db540fd9bc85b90a6

**Comment by bilalshaikh42** [comment]
I have not seen this happening on the org deployment. Can you confirm that?

**Comment by bilalshaikh42** [comment]
Oops, I see the error. Silly mistake in the paths of the files. I'll put up a patch shortly

**Comment by bilalshaikh42** [comment]
What should we include in the output folder? Now that we are producing an HDF5 output, the files present in the output directory are 

1. The HDF5 File 
2. Log.yml
3. plots.zip
4. Sbatch Script
5. stdout/stderr
6. omex archive

Should all of these be included? Or should we just provide the HDF file?

**Comment by jonrkarr** [comment]
The only things that seem essential are
- reports.h5
- plots.zip

In case log.yml > 16 MB, I guess that can be included too. Same with stdout/error.

The OMEX archive doesn't seem critical to include with the outputs since its available separately.

The SBATCH provides some transparency about exactly what runBioSimulations does, but its reusability is a little limited because its somewhat specific to our setup. Instead of including an SBATCH script in each output archive, we could display the SBATCH template in the documentation (e.g., run.biosimulations.org/help/faq).
