### ISSUE TITLE
Support for null array values is broken

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2336]
The BioSimulators API no longer accepts submissions with null algorithm parameters:
```json
{
  "algorithms": {
    "parameters": null
  }
}
```

`null` is intended to mean that the parameters haven't been annotated. This distinct from empty array (`[]`) which indicates that the algorithm don't have any parameters.

**Comment by bilalshaikh42** [comment]
Do you know when this started? I can't think of any changes recently that would have caused this.

**Comment by jonrkarr** [comment]
Not sure. the simulators API file hasn't been changed recently nor has the `addValidationForNullableAttributes` method.

**Comment by jonrkarr** [comment]
Fixed in 3ac80f8435b78c169ad37934478fac3ebf47e4af. The problem was with the custom validation function I wrote.
