### ISSUE TITLE
Create vega files from the sedml plots

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2337]
Parse sedml to create vega files that can be presented as default visualization options on runBiosimulations

**Comment by jonrkarr** [comment]
Use sbmlsim if possible

**Comment by jonrkarr** [comment]
@matthiaskoenig we're thinking of converting SED-ML plots to Vega as a way to render SED-ML plots online with runBioSimulations. Is this possible with sbmlsim?

**Comment by matthiaskoenig** [comment]
At the moment this is not possible. This is on the top of my list after finishing the SED-ML L1V4 plotting support. 
See https://github.com/matthiaskoenig/sbmlsim/issues/27 to track the issue.

Currently I only provide rendering of plots via matplotlib, but this could easily be extended to provide D3 web output via mpld3. See https://github.com/matthiaskoenig/sbmlsim/issues/102 to track the issue

I also want urgently interactive web graphics for reports from my simulation experiments. So this will be implemented sooner then later. After finishing the SED-ML L1V4 plotting I wanted to register `sbmlsim` in biosimulators. It would be great if you could provide links to the presentations/slides from HARMONY.

**Comment by jonrkarr** [comment]
This would work nicely with runBioSimulations. The main immediate motivation is to provide interactive versions of the plots in the SED-ML files in BioModels. We'll create this another way.

Here's the video and slides. We'll add links to this from https://biosimulators.org.
https://www.youtube.com/watch?v=h0SCn0ZDqq8
https://drive.google.com/file/d/1Q0X6GNQlT5PfZOcBNVu1B92SSAxJWrnS/view?usp=sharing

**Comment by matthiaskoenig** [comment]
This should be easily doable. Especially the subset of SED-ML used by biomodels is very limited. I.e. it should be sufficient to render line plots in vega. You are talking about the SED-ML files in the curated branch in the COMBINE archives? If this is the use case this should be very easy to implement (because I would not need to have everything of SED-ML L1V4 for the subset).

**Comment by jonrkarr** [comment]
The curated subset of BioModels is trivial -- just 2d line plots. The plotting widget in runBioSimulations already supports the same options as SED-ML. We just need to connect the displayed curves to the sets of curves in SED-ML plots. To make multiple plots visible at once, we could tile plots together.
