### ISSUE TITLE
Strange Clipping in Vega Visualization

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2372]
**Please describe the bug**
There is a strange clipping effect when the vega figure is panned

**Please describe how to reproduce the bug**
1. Go to https://run.biosimulations.dev/simulations/60650c6ca7398bdfac3203a8#tab=viz
2. Click and hold the map. Move map around
3. Note trail of letters left when map is moved (see example photo)

**Screenshots**

![image](https://user-images.githubusercontent.com/32490144/113225478-c03f8680-925b-11eb-8c6c-98b04aba902d.png)

**Environment (please complete the following information):**
 - Type of device:  Desktop 
 - OS:  Windows 10, linux
 - Browser Chrome
 - Version: Stable, Beta, Dev

**Comment by jonrkarr** [comment]
I've seen this. Andrew has too. It's not specifically related to this diagram. Its a bug in Vega or more likely in the canvas package that Vega uses for rendering. Its probably exacerbated with the complexity of the diagram. In either case, there's not much we can do except file a bug report. The other thing we could do is switch to the SVG renderer. But, the performance would likely be significantly slower.
