### ISSUE TITLE
BoolNet Container Logs are not compatible with json endpoint

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2410]
- COMBINE archive: https://run.api.biosimulations.dev/run/607093329bb7309709d0ecd1/download
  Simulator: BoolNet

- COMBINE archive: https://run.api.biosimulations.dev/run/607094329bb73048d2d0ecd6/download
  Simulator: BoolNet

- COMBINE archive: https://run.api.biosimulations.dev/run/6070a3ca9bb730760cd0ece0/download
  Simulator: BoolNet

**Comment by bilalshaikh42** [comment]
The listed simulations ran correctly, so there must be some other issue.

**Comment by bilalshaikh42** [comment]
This is being caused by the log output of the simulation run. The following structure is not able to be converted to json for uploading to the API.


```
- algorithm: KISAO_0000449
    duration: 0.319784
    exception: null
    id: task_del_Cln2
    output: ''
    simulatorDetails:
    - key: method
      value: BoolNet::generateTimeSeries
    - key: arguments
      value:
        numMeasurements: 101
        numSeries: 1
        perturbations: 0
        type: &id002 !!python/object/new:rpy2.robjects.vectors.StrVector
          state: !!python/tuple
          - !!binary |
            WAoAAAACAAMFAgACAwAAAAAQAAAAAQAEAAkAAAALc3luY2hyb25vdXM=
          - ro: !!python/object:rpy2.robjects.vectors.VectorOperationsDelegator
              _parent: *id002
            rx: !!python/object:rpy2.robjects.vectors.ExtractDelegator
              _parent: *id002
            rx2: !!python/object:rpy2.robjects.vectors.DoubleExtractDelegator
              _parent: *id002
```

Here is the error from the parser

```
Nest] 1   - 04/09/2021, 8:58:07 PM   [LogService] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property 'state' -> object with constructor 'Array'
    |     index 1 -> object with constructor 'Object'
    |     property 'ro' -> object with constructor 'Object'
    --- property '_parent' closes the circle +443ms
```

**Comment by bilalshaikh42** [comment]
Attached is the full simulation ouput
[6070bd64a3fde934863fadbf.zip](https://github.com/biosimulations/Biosimulations/files/6288560/6070bd64a3fde934863fadbf.zip)

**Comment by jonrkarr** [comment]
I see the issue now. This straightforward to fix.:
- [x] Change simulator details for BoolNet to use plain Python types (rather than R types) which serialize nicely to JSON
- [x] Push new version to BioSimulators

This strange. Other archives work fine with BoolNet.

**Comment by jonrkarr** [comment]
Fixed in Biosimulators_BoolNet 0.1.8. This should be pushed through to BioSimulators soon.

Todo
- [ ] Check that runBioSimulations can now correctly simulate the COMBINE archive for the above failures.

**Comment by jonrkarr** [comment]
I made a few additional changes to BoolNet that will be pushed once the new version BioSimulators-utils is pushed through to PyPi in a few minutes:
- Used libSBML for stricter model validation
- Fixed typo in error message
- Fixed handing of namespaces in attribute references in target XPATHs in BioSimulators-utils

**Comment by jonrkarr** [comment]
This should be working. Can confirm when simulation service is working again.

**Comment by jonrkarr** [comment]
The fix looks to be deployed.
