### ISSUE TITLE
Cannot Submit Simulations using webform

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2412]
The submit button is not working on the webform.

**Comment by jonrkarr** [comment]
How so?

The form has changed. Its necessary to select a file and choose a simulation tool.

**Comment by bilalshaikh42** [comment]
Starting a new run, it seems that one needs to both upload a file, then switch to the "url" option and paste a URL. Then, either a file upload or URL will work.

**Comment by bilalshaikh42** [comment]
This must be a validation issue where both fields are marked as required

**Comment by bilalshaikh42** [comment]
The button also does not seem to indicate when it is disabled or enabled. The color remains grey throughout. Didn't this turn blue when ready previously?

**Comment by jonrkarr** [comment]
I fixed the validation of the combination of the file/URL options.

The button is now always enabled. Clicking it before the form is valid will lead to errors being displayed.

**Comment by bilalshaikh42** [comment]
> I fixed the validation of the combination of the file/URL options.
> 
> The button is now always enabled. Clicking it before the form is valid will lead to errors being displayed.

Are the changes pushed?

**Comment by jonrkarr** [comment]
They are will be in #2414.
