### ISSUE TITLE
Delete created combine archives after some time

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2415]

**Comment by jonrkarr** [comment]
This refers to archives created by https://run.biosimulations.org/create.

This should be deleted, say after 24 h, so we're not storing users data long-term.

**Comment by jonrkarr** [comment]
I believe this can be done with a lifecycle configuration rule.
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#bucketlifecycleconfiguration
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketLifecycleConfiguration.html

Here's Python code. Note, I've changed the prefix to `temp/createdCombineArchive/` to help us keep track of these files.
```python
import boto3

bucket = 'biosimdev'
prefix = 'temp/createdCombineArchive/'
expiration_days = 1

s3 = boto3.resource('s3')
bucket_lifecycle_configuration = s3.BucketLifecycleConfiguration(bucket)
bucket_lifecycle_configuration.put(
    LifecycleConfiguration={
        'Rules': [
            {
                'ID': 'delete-temporary-combine-archives',
                'Status': 'Enabled',
                'Filter': {
                    'Prefix': prefix,
                },
                'Expiration': {
                    'Days': expiration_days
                },
            },
        ]
    }
)
```

**Comment by bilalshaikh42** [comment]
I agree that the lifecycle configuration is ideal to use.  I am a bit uncertain on how to manage this across the various apps. It seems that the "put" method replaces the entire configuration. Each app would only have knowledge of its own rules. 

This might be better of as a one of script/ its own config in a file in the repo. This seems more of a policy change made at the infrastructure level rather than in  the app

**Comment by jonrkarr** [comment]
Handling this globally works. I didn't mean to suggest this needed to be managed locally by each app.

Few other thoughts -- no action needed.
- If you wanted to handle it locally to each app, you could use a combination of `get` and `put` calls to make sure you preserve all other lifecycle rules.
- Another option to support more local management of lifecycle rules is to use multiple buckets. I don't know if that would be more complicated to deploy.
- Regarding managing the usage of the bucket by multiple apps, you could adopt the convention that prefixes should be equal to the name of the app which manages their contents (e.g., '/combine-service/tmp/`).
