### ISSUE TITLE
Confirm that the created combine archives are being deleted as set in the policy

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2432]
[Sample File](http://biosimdevbucket.cam.uchc.edu/s3/temp/createdCombineArchive/dcddf914-399f-4188-a1de-b77eed589aaf)

**Comment by bilalshaikh42** [comment]
The sample file is still present. need to figure out why

**Comment by jonrkarr** [comment]
The sample file appears to be gone. Is this done?

**Comment by bilalshaikh42** [comment]
I don't think so. Last I checked the files were not expiring correctly.

**Comment by jonrkarr** [comment]
Added a FAQ about the 1-day expiration.

The life cycle configuration looks correct, but the objects are still there. If I understand correctly, the `expiration` property of the affected objects should indicate when the object will be expired. However, this property is null. It feels like this feature is somehow disabled or there's an error that we're not seeing.  I'll send Mike an email on Monday to see if he knows how to set up an expiration policy.

Alternatively, we could set up a cron action for this.

**Comment by bilalshaikh42** [comment]
I can create a workflow in the deployment branch to do this. We can leave the code as-is, to keep it platform-independent. Presumably, this would work on cloud/standard amazon aws

**Comment by jonrkarr** [comment]
I asked Mike to look into this last week. In theory, I think the policy you set should be enough. It feels like there's some error that we're not seeing or a permission that we don't have. We can ping him again to see if he figured it out.

**Comment by bilalshaikh42** [comment]
This is due to the version of Scality currently deployed at UConn not supporting Life Cycle rules.  Supposedly, this should be updated in the near future. The issue can be closed with #3992 as at some point the update should ensure that the current policies start working

**Comment by jonrkarr** [comment]
I must have missed that. It didn't seem like we had a clear understanding of why this wasn't working. The cron schedule can be turned off when Life Cycle rules are enabled.
