### ISSUE TITLE
Change COMBINE archives to be downloaded rather than redirected to

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2435]
The UI can't facilitate the downloading of COMBINE archives due to this security issue (runBioSimulations runs over HTTPs, but the download runs over HTTP).
```
Mixed Content: The site at 'https://run.biosimulations.dev/' was loaded over a secure connection, but the file
at 'http://biosimdevbucket.cam.uchc.edu/s3/temp/createdCombineArchive/34a1029e-02cb-45b9-ac89-0d82ab3d7199'
was redirected through an insecure connection. This file should be served over HTTPS. This download has
been blocked. See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
```

Steps to reproduce:
- Open https://run.biosimulations.dev/create?modelUrl=https:%2F%2Fraw.githubusercontent.com%2Fbiosimulators%2FBiosimulators_utils%2Fdev%2Ftests%2Ffixtures%2FBIOMD0000000075.xml&modelFormat=format_2585&modelingFramework=SBO_0000293&simulationType=SedUniformTimeCourseSimulation&simulationAlgorithm=KISAO_0000019
- Entire time course parameters, e.g.
  - Initial time: 0
  - End time: 10
  - Output start time: 0
  - Number of steps: 10
- Click "Download"

If the data will be available by HTTPS shortly, this issue will resolve itself. Otherwise, we need to figure out a different way to download these files.

**Comment by bilalshaikh42** [comment]
A temporary solution is to redirect the users to the URL rather than have
the UI trigger the download. We should have https working shortly

**Comment by jonrkarr** [comment]
I temporarily changed this to redirection. This should be changed back once HTTPS is enabled so that the UI can make sure the file is downloaded with a more informative named e.g., `archive.omex` rather than `{id}.zip`.

**Comment by bilalshaikh42** [comment]
@jonrkarr  I don't remember where exactly this was. The download functionality seems to be working fine. Can we close?

**Comment by jonrkarr** [comment]
Here's the relevant piece which I believe can be simplified now:

https://github.com/biosimulations/Biosimulations/blob/dev/apps/dispatch/src/app/components/create-simulation-project/create-simulation-project/create-simulation-project.component.ts#L1803
