### ISSUE TITLE
Add attribute to results data model(s) to keep track of the type of each "report"

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2442]
In order to render plots described in SED documents as discussed at the end of the HARMONY with Lucian Smith and Frank Bergmann, we need to save the data for plots (e.g. to HDF/CSV). After thinking about this, I think the simplest solution is to basically treat report and plot data the same -- save the plot data to CSV/HDF and use the same typescript/MongoDB data structures.

To help keep track of which data corresponds to `SedReport`s and which to `SedPlot2D` or `SedPlot3d`, it would helpful to record the type of the output associated with each instance of `ResultsModel` (`SedReport`, `SedPlot2D` or `SedPlot3d`). 

Example: add attribute with name `type` or `_type` to `ResultsModel` in `biosimulations/apps/dispatch-api/results/results.model.ts`. The value of this attribute could be `SedReport`, `SedPlot2D` or `SedPlot3D`.

(Ideally, we'd also rename attributes from `reportId` to `outputId`, reflecting their new more general meaning. But changing this seems like a lower priority.)

**Comment by bilalshaikh42** [comment]
This will be handled directly by the hsds return information. Still todo, define the model for the returned data

**Comment by jonrkarr** [comment]
This information is captured in HDF5 by the `_type` attribute. The values can be `Report`, `Plot2D`, or `Plot3D`.

**Comment by bilalshaikh42** [comment]
@jonrkarr  could you take a look at this commit and approve the changes to the datamodel? This is the data that is returned from the dispatch-api.  I am not sure if sedmlName and sedmlId are designed to be exposed

https://github.com/biosimulations/Biosimulations/pull/2627/commits/b02ab010150be4484e6b672d0518ead45c542dde

The next commit makes the name changes that were also mentioned. We are going to be making breaking changes to the API anyway, so this is a good time to make those. 

https://github.com/biosimulations/Biosimulations/pull/2627/commits/8b8363f4c6ea7908f043d31d378c82c0d8e33294

**Comment by jonrkarr** [comment]
Looks good. I added a couple thoughts about attribute names (mainly for consistency between the classes) before I saw your latter commit already does some of this.
