### ISSUE TITLE
Simulation runs stuck in running status

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2448]
Is there potentially a problem submitting simulations shortly after an image refresh was triggered? or are some image refreshes failing?

I was able to run a couple simulations with BoolNet this hour, but simulations with PySCeS and tellurium are stuck in running status
- https://run.biosimulations.dev/simulations/607769c665d205e3b7ea2f43
- https://run.biosimulations.dev/simulations/60776a8265d20530a5ea2f45

Simulation: https://github.com/biosimulators/Biosimulators_test_suite/raw/dev/examples/sbml-core/Caravagna-J-Theor-Biol-2010-tumor-suppressive-oscillations.omex

**Comment by bilalshaikh42** [comment]
The logs suggest that the image needed to be built, and this caused the timeout. It seems that building the images in advanced in quite necessary. Did you call the image refresh endpoint when the images were updated?

**Comment by bilalshaikh42** [comment]
Okay, seems that the job to generate the image itself was timed out. I will increase the timeout for this.

**Comment by jonrkarr** [comment]
I refreshed the images hours earlier. It seemed like image generation likely had failed and no valid image was available.

**Comment by bilalshaikh42** [comment]
Should be fixed
