### ISSUE TITLE
API results validation does not account for padding of datasets with "NaN" 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2468]
**Please describe the bug**
The API currently checks each row of the results by parsing the input into numbers. If the input is parsed to 'NaN' then the input is considered invalid. However, the BioSimulators specification recommends padding the dataset with  'NaN' to get equivalent shapes for each row. 

@jonrkarr  Wanted to confirm that I should account for this in the API.  I can do a check to see if the value is literally a string == 'NaN' and if so accept it. Otherwise, I will attempt to parse it into a number, and return an error if I get 'NaN'.

**Comment by jonrkarr** [comment]
"NaN" is valid in CSV because data sets don't necessarily have the same shape. 

I'm using Pandas to create the CSV files. Here's how Pandas exports a 3x2 matrix of `NaN` with a single non-NaN at (2, 1) to CSV:

```
,0,1
A,,
B,,
C,,1.0
```

Pandas exports "NaN" as empty strings (``).

**Comment by jonrkarr** [comment]
Unfortunately, this is only the major subtle was that CSV is not used consistently -- more reason to use HDF5 where we can be more specific about NaN vs empty strings.

**Comment by bilalshaikh42** [comment]
Sorry, I am not clear on what the final outputs will contain.  Should both empty strings and 'NaN' be accepted? 

Another clarification: Will these ever be the first element of a dataset?

**Comment by bilalshaikh42** [comment]
This will be resolved with HDF
