### ISSUE TITLE
Add button to run simmilar simulation

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2502]
The simulation view page can have a button to preload all of the information into the form to submit a new run. This will make it easier to make minor changes to repeated runs (ie change version of the tool)

**Comment by jonrkarr** [comment]
Yes, this requires a few changes
- Modify the create archive form to support modification
- Create an endpoint to extract models/ SED specifications out of archives
- Ideally, expand the create archive form to support more of the features of SED-ML, at the very least multiple tasks. This is relatively easy. The form elements for each task could be displayed within tabs or an accordion.

**Comment by bilalshaikh42** [comment]
I was actually thinking much simpler. The omex file would be identical, but
give the use the option to swap it out entirely. Introspection of the
actual simulation is definitely a more complicated usecase. I ran into this
when trying to run the same simulation file with different versions of
simulators.

**Comment by jonrkarr** [comment]
That's this. Just add a route to `/run` with query arguments.
