### ISSUE TITLE
COMBINE API endpoints limited to small files

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2513]
`/combine/validate` seems to be limited to small files -- see error below. Larger (1.5 mb) files generate 413 errors. I'm guessing the other endpoints have the same problem.

@bilalshaikh42 do you know where this is coming from?

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.19.2</center>
</body>
</html>
```

**Comment by bilalshaikh42** [comment]
I assume something like the following is needed in the main app file. The upload limit seems to be unlimited by default, but maybe it is set by connexion somehow. 

```
app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 16 * 1024 * 1024
```

**Comment by bilalshaikh42** [comment]
Actually, I just noticed that the source of the error is Nginx and not the python app. It seems that the default ingress limit is quite low. This might be the issue: 
https://www.net7.be/blog/article/kubernetes_nginx_ingress_max_upload_size.html

**Comment by bilalshaikh42** [comment]
Would 16mb be a reasonable limit for this?

**Comment by bilalshaikh42** [comment]
@jonrkarr  I have tried to u[date the limit on the dev branch. Could you confirm if it is working? If so, I can set the configuration for the org deployment as well

**Comment by jonrkarr** [comment]
Looks good. I added validation to the forms for file sizes.

Should be good to redeploy.

**Comment by bilalshaikh42** [comment]
The deployment is updated. The max size is actually set to 600MB I can update the validation shortly

**Comment by jonrkarr** [comment]
Great. There's also a couple points in the documentation that say "16 MB". That string should be updated too.

**Comment by bilalshaikh42** [comment]
Superseded by #2537
