### ISSUE TITLE
Check for size limits to address security vulnerability in URL handling code

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2536]
When a URL is provided to a combine archive the backend will download the file in order to simulate it. A malicious user could repeatedly provide a URL to extremely large files causing denial of service and blocking backend resources.

The API should download the file and include a check to make sure it is below a reasonable size for a Combine Archive. 

@jonrkarr What would be a good limit to use for this? This can be much higher than any reasonable combine archive. Would something like 1gb or 10gb make sense here?

**Comment by jonrkarr** [comment]
For reference, the largest compressed entry in BioModels is 68 MB. This is mainly driven by a large PNG image for a simulation result. The biggest SBML file is 3 MB. The biggest SED-ML files is 0.1 MB. In other contexts, I have seen larger SBML files > 15 MB. Of course someone could quickly get to a larger archive if they had multiple variants of a model in a single archive. While I can't think of example of where someone has done this with SED-ML, there are definitely examples of this in the literature (where SED-ML/COMBINE wasn't used).

Given all of this, 1GB seems plenty big. 10GB would be fine too. Whatever you choose, it would be helpful to have a clear error message.

**Comment by bilalshaikh42** [comment]
Got it, thanks

**Comment by bilalshaikh42** [comment]
Block size on the NFS is 1048576 bytes. 
1gb limit would be set as ```ulimit -f 1048576000```
This can be added to the download part of the bash script

**Comment by jonrkarr** [comment]
We should also update the relevant part of the FAQs with this new limit:
https://github.com/biosimulations/Biosimulations/blob/dev/biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.html#L178

The following FAQ already has a note that users can contact us for help executing larger simulations.
