### ISSUE TITLE
Update the relevant part of the FAQs new limit

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2537]
We should also update the relevant part of the FAQs with this new limit:
https://github.com/biosimulations/Biosimulations/blob/dev/biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.html#L178

The following FAQ already has a note that users can contact us for help executing larger simulations.

_Originally posted by @jonrkarr in https://github.com/biosimulations/Biosimulations/issues/2536#issuecomment-839258747_

**Comment by bilalshaikh42** [comment]
In #2513  The size limit was set to 600MB. This should be updated to 1GB to be consistent. This will also need documentation updates.

**Comment by bilalshaikh42** [comment]
The Angular forms for the combine archives have a validation set for 16MB. This must also be updated

**Comment by jonrkarr** [comment]
Thanks for making all of this consistent.
