### ISSUE TITLE
Rerun button does not remove tabs from url, causing failure in downloading the omex archive

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2540]
**Please describe the bug**
The rerun button in the simulation run page does not properly set the url of the form

**Please describe how to reproduce the bug**
1. Go to https://run.biosimulations.dev/simulations/609eb8d243b089476566a226#tab=log
2. Click on  rerun 
3. Look at URL field
4. See URL is https://run.api.biosimulations.dev/run/609eb8d243b089476566a226#tab=log/download instead of https://run.api.biosimulations.dev/run/609eb8d243b089476566a226/download

**How should BioSimulations have behaved**
The URL should be set properly

**Comment by jonrkarr** [comment]
This also impacts the sharing button.
