### ISSUE TITLE
Complete std output not shown in front end

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2543]
**Please describe the bug**
Only a portion of the log is shown
**Please describe how to reproduce the bug**
1. Go to '.https://run.biosimulations.dev/simulations/609f196c6374a5fb3231e90a#tab=log
2. Click on view full output
3. See only first part of log
4. Download full logs. See more info is presetn, but just not displayed

**How should BioSimulations have behaved**
The bottom logs should be scrollable to show full output.

@jonrkarr  I have no idea why this would stop working since it used to scroll fine before. Is there some encoding in the text causing it to end?

**Comment by jonrkarr** [comment]
The text isn't being rendered into the HTML, so its not a formatting issue.

Something must be preventing the full text from being passed to the HTML template.

**Comment by jonrkarr** [comment]
Its due to the `ansi-to-html` package. This is truncating the logs.

**Comment by jonrkarr** [comment]
I think maybe `ansi-to-html` has trouble with the progress bar

```
 0% [                                       ] 0           --.-K/s              
100%[======================================>] 6,185       --.-K/s   in 0s   
```

**Comment by jonrkarr** [comment]
Switched to `anser`. Seems to work better.
