### ISSUE TITLE
Mongo error when invalid id is queried

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2551]
Stackdriver Error Reporting error detail

reason: Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characte...
https://console.cloud.google.com/errors/CN-yqMWkg7mEbQ?project=biosimulations&src=VESPA&time=P30D

This must be caused by a user querying for an invalid id, since all IDs generated server side are valid. We should catch this error and return a 404 instead

**Comment by jonrkarr** [comment]
I think this is now handled. Both the examples below generate 404 errors
- http://localhost:3333/simulators/x?includeTests=false
- http://localhost:3333/simulators/1?includeTests=false
