### ISSUE TITLE
Disable plotting for some types of simulations

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2564]
If a simulation is an FBA for example, line plots do not make sense.
There may be some usecases that I am not concidering, so we can discuss if this might be more user friendly.

**Comment by jonrkarr** [comment]
We could disable 2-d plots for 1-dimensional results. 

In addition, we could provide a different type of plot that make sense for 1-dimensional data such as a bar chart or kernel density plot.

Another limitation is the lack of 3D plots (#1718). We don't yet have a 3d simulator to motivate this.

I've also been thinking of about changing the plot menu to these options:
- Select the plots from a SED-ML file
- Select a Vega file from the COMBINE archive
- Design a 2d plot
- Upload a Vega plot

(2) is partly motivated by (a) the need to store visualizations for our simulation database and (b) the desire to make Vega visualizations easier to demonstrate.

**Comment by jonrkarr** [comment]
I added #2601 #2602 #2603 to address this issue.

@bilalshaikh42, close this if you feel these other issues will address your point.
