### ISSUE TITLE
Fix storage of creation date of simulation tools

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2570]
The creation dates of simulation tools are getting overwritten each time a simulation tool is updated. This should be fixed.

**Comment by jonrkarr** [comment]
I think the issue traces to [`biosimulations/libs/simulators/database-models/src/lib/biosimulatorsMeta.ts#L156`](
https://github.com/biosimulations/Biosimulations/blob/dev/biosimulations/libs/simulators/database-models/src/lib/biosimulatorsMeta.ts#L156).

@bilalshaikh42 when a simulator is updated, are the subdocuments updated? or a new subdocuments created? Seems like it must be the later. In that case, I think the created date needs to be copied from the previous record in [`biosimulations/apps/simulators-api/src/simulators/simulators.service.ts#L63`](https://github.com/biosimulations/Biosimulations/blob/dev/biosimulations/apps/simulators-api/src/simulators/simulators.service.ts#L63).

I think may `sim.overwrite(doc);` needs to be replaced with
```
doc.biosimulatorsMeta.created = sim.biosimulatorsMeta.created;
sim.overwrite(doc);
```

**Comment by bilalshaikh42** [comment]
Yes, I think that is the source of the issue. The created/updated times are managed automatically. So the overwrite method should probably be replaced with something like 'update'. I'll take a look at this.

**Comment by bilalshaikh42** [comment]
Actually, you are correct about the approach. The simulators database is not setting the dates automatically the same way that the others do. Copying over the created date from the older model should be correct.

**Comment by jonrkarr** [comment]
I think MongoDB only saves history when attributes are edited one at a time and then the `save` method is used. I'm guessing history includes created and updated timestamps.

Rather than dealing with the save method, it might simpler to add the one additional line I suggested above:
1. Copy the creation date from the old record to the new content
2. `overwrite` the old record with the new content

**Comment by bilalshaikh42** [comment]
Yup, that is the approach I took in #2572. I am having some trouble with the database connection locally, so we can confirm if it's fixed as soon as it deploys to dev. 
There seem to be some build issues with deployment, that I am working on.

**Comment by bilalshaikh42** [comment]
This should be resolved
