### ISSUE TITLE
Combine Service has uncaught error

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2621]
An error was reported on the backend from the combine-service. The error was not caught, meaning the api responded with a 5xx rather than a 4xx error. This should be caught so the user gets a more meaningful error. 

The trace information is here: https://console.cloud.google.com/errors/CK67pcOVkJGsIQ?time=P1D&project=biosimulations

**Comment by jonrkarr** [comment]
I can catch this so its a 400 rather than 500 error.

Is there a way to see what caused the error (the payload to the REST API endpoint)?

**Comment by bilalshaikh42** [comment]
Unfortunately not yet. I am hoping to add better tracing at some point

**Comment by jonrkarr** [comment]
This will be included with the next push.

**Comment by jonrkarr** [comment]
Closed by #2624.
