### ISSUE TITLE
Downloading results failed for 60bd3746f83fe5520bad31c3

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2622]
https://run.biosimulations.org/simulations/60bd3746f83fe5520bad31c3

{"error":[{"status":"500","title":"Internal Server Error","meta":{"time":1623184041076,"url":"/results/60bd3746f83fe5520bad31c3/download"}}]}

**Comment by bilalshaikh42** [comment]
This is caused by the file no being available. 2 things to do
1. Figure out why the file is not uploaded
2. Catch the error and return a 404
