### ISSUE TITLE
Allow frontend to attempt fetching results even when simulation is failed

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2634]
See this run.: https://run.biosimulations.dev/simulations/60ca36d3ec4fbea4a994933d#tab=log

While the simulation failed for some output, there were other outputs that were successful. These should still be retrievable from the frontend.

**Comment by jonrkarr** [comment]
We could do this. It requires more nuanced handling e.g. so that only plots for which data is available are plotted. 

I think we can skip this for now.

**Comment by bilalshaikh42** [comment]
Perhaps we can fetch the results, but show a warning that results may be inaccurate due to a failure?

**Comment by jonrkarr** [comment]
Yes, we would need to indicate that some results are not available. Also we need to change the way that that plotting works to make sure that missing data doesn't cause an error and instead plots for missing data are skipped.

**Comment by bilalshaikh42** [comment]
Ah, I didn't account for that. I assumed any missing data would just not
produce a plot, but it could cause errors.

**Comment by bilalshaikh42** [comment]
@jonrkarr based on recent discussion, would we want to update the "statusReason" to a more detailed document that contains information about which steps succeeded/failed?
