### ISSUE TITLE
Setup DNS to forward docs.biosimulators.org (or similar) to https://biosimulators.github.io/

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2654]
As discussed today, https://biosimulators.github.io/ (Sphinx) could be a simpler way to communicate documentation than the HTML files we're currently using for https://biosimulators.org/conventions. 

We could make this look more professional by forwarding docs.biosimulators.org (or similar) to https://biosimulators.github.io/. GitHub has instructions here: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

- [x] Add `CNAME` file to https://github.com/biosimulators/biosimulators.github.io with value `docs.biosimulators.org`
- [x] Add CNAME record to DNS for biosimulators.org to point to https://biosimulators.github.io

**Comment by bilalshaikh42** [comment]
deployed at https://docs.biosimulators.org/
