### ISSUE TITLE
Results cannot be retrieved for GillesPy2 run

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2657]
This query
https://run.api.biosimulations.dev/results/60cd5ee28b96debc78eaaecf?includeData=true

generates this response
```json
{
	"error": [{
		"status": "500",
		"title": "Internal Server Error",
		"meta": {
			"time": 1625025324488,
			"url": "/results/60cd5ee28b96debc78eaaecf?includeData=true"
		}
	}]
}
```

**Comment by bilalshaikh42** [comment]
This is the same issue as  the PySCeS issue earlier. The hdf file contains the attributes

```
dataSetDataTypes 
dataSetIds 
dataSetLabels 
dataSetShapes 
``` 
instead of the required: 

```
sedmlDataSetDataTypes 
sedmlDataSetIds 
sedmlDataSetLabels 
sedmlId
uri
```

**Comment by jonrkarr** [comment]
This is because the example run was run with an older image. I'm not sure why this is the case. 1.5.11 should have been used at the time rather than 1.5.7.

**Comment by jonrkarr** [comment]
I deleted the records for the older images pre June.

We haven't set anything up to migrate older versions of simulator images forward. There are GitHub action workflows that could be triggered, but this isn't automated.

Ideally, we would have versions of the simulator standard and filter out all images for older versions from RunBioSimulations.

**Comment by bilalshaikh42** [comment]
Agreed. Have we been keeping track of the standards versions?
