### ISSUE TITLE
Fix sorting of latest version of simulation tools

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2665]
In [`getLatestSimulators`]( https://github.com/biosimulations/Biosimulations/blob/3bf849aaf2142bf13712963c24a8baf41216f3ca/apps/simulators-api/src/simulators/simulators.controller.ts#L83)

Possible solution
https://www.npmjs.com/package/compare-versions
https://www.npmjs.com/package/string-natural-compare

**Comment by bilalshaikh42** [comment]
Repeat of #2664
