### ISSUE TITLE
Cache some slow API endpoints

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2678]
Some API endpoints could be cached to speed up loading our applications, especially if #2668 doesn't speed things up enough. In particular, 
- [ ] https://api.biosimulators.org/simulators
- [ ] https://api.biosimulators.org/simulators/latest
- [ ] https://ontology.api.biosimulations.org/{ontologyId}/list

**Comment by bilalshaikh42** [comment]
Is the intention to have to cache on the frontend or the API?

**Comment by jonrkarr** [comment]
Closing because the application seems sufficiently fast due to various improvements
- Switching from COMBINE API to MongoDB/S3
