### ISSUE TITLE
Pull validation results into simulator view page

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2696]
The view page for each simulation tool should pull the validation information from the API since it is no longer downloaded by default

**Comment by jonrkarr** [comment]
This needs to be done as part of adding the new query argument. The two changes need to be released together.

**Comment by bilalshaikh42** [comment]
The query argument has been added already. I needed to deploy the changes
to fix the issue with the API being down yesterday, so currently, the
validation info is not shown on the front end.

**Comment by jonrkarr** [comment]
Done in #2713
