### ISSUE TITLE
COMBINE/OMEX downloads broken

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2706]
Example: https://run.api.biosimulations.dev/run/60dcfd6af14a8929e410e130/download

This breaks the functionality of the COMBINE API, which relies on this.

**Comment by bilalshaikh42** [comment]
simulation-60dcfd6af14a8929e410e130

**Comment by bilalshaikh42** [comment]
This is quite odd. The backend uses that very URL to download the archive to start the simulation. It must have downloaded correctly in order for the simulation to succeed. It somehow got deleted

**Comment by bilalshaikh42** [comment]
I am unable to reproduce for a new simulation run

**Comment by jonrkarr** [comment]
Is there anything that could cause the OMEX file to expire in the S3 bucket?

**Comment by bilalshaikh42** [comment]
Actually, the file still exists: https://files-dev.biosimulations.org/s3/simulations/60dcfd6af14a8929e410e130/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint-continuous.omex

**Comment by bilalshaikh42** [comment]
Unfortunately the logs on the deployment are not helpful. Will debug locally tomorrow

**Comment by bilalshaikh42** [comment]
I see the issue. The mongo collection for this was deleted, so the correct URL for the file is no longer available. I'll restore the last backup we have

**Comment by bilalshaikh42** [comment]
This only happened on the dev database. @jonrkarr It is probably easier to just regenerate the simulations

**Comment by jonrkarr** [comment]
OK. I'll rerun as needed.
