### ISSUE TITLE
Reenable VCell once issues are addressed

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2714]
This run failed with VCell for no clear reason
https://run.biosimulations.dev/simulations/60f13090c9fb54c29d9f0cc3

**Comment by bilalshaikh42** [comment]
StatusReason: Checking status for job with id 3176413 for simulation 60f13090c9fb54c29d9f0cc3: Status is FAILED
The job on the hpc failed. I will debug further

**Comment by bilalshaikh42** [comment]
The actual job on the hpc passed, so must have been an error connecting to HPC to check status.  Unfortunately, no errors were thrown so there is no log

**Comment by bilalshaikh42** [comment]
The rerun worked, but there seem to be issues with the results: https://run.biosimulations.dev/simulations/60f5883b72ff0120ba5ce11e#tab=viz

**Comment by bilalshaikh42** [comment]
API is returning results correctly, so seems to be frontend issue: 
https://run.api.biosimulations.dev/results/60f5883b72ff0120ba5ce11e?includeData=true

**Comment by jonrkarr** [comment]
I'll take a look at the rerun.

**Comment by jonrkarr** [comment]
The Vega visualization for the rerun is failing because https://run.api.biosimulations.dev/results/60f5883b72ff0120ba5ce11e/simulation_1.sedml%2Freport?includeData=true is failing.

The Vega visualizations are using the report endpoint for two reasons
- Avoid streaming data not needed for a visualization
- Avoid dealing with more deeply nested data -- though I think Vega could flatten this out

**Comment by jonrkarr** [comment]
Disregard my previous message.

I improved the handling of data loading errors with Vega.

The re-run doesn't display the SED-ML plots correctly, but it does display the user-configured plots. I believe this is due to VCell not saving the data for plots as intended. VCell is confusing data set ids and labels. I'll have to add an assertion to the simulators test suite to cover this, and VCell will have to fix this. I already had an issue for this: biosimulators/Biosimulators_test_suite#42. We can temporarily disable VCell until they fix it.

**Comment by jonrkarr** [comment]
I created three issues for VCell about this. Turns out that VCell doesn't save plot data consistently. The result is different, depending on whether reports are also defined or not. I set VCell to validated=False until this is fixed. This will avoid users encountering a simulation tool that produces inconsistent data.

**Comment by bilalshaikh42** [comment]
This should be handled automatically by the submission of the simulator
