### ISSUE TITLE
Simplify endpoints for various services

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2724]
Currently, each service is running on an individual subdomain. We can set the backend to route the same domain to the different services.  For example, the path  `api.biosimulations.org/run/ID` will route the same as` run.biosimulations.org/run/id` This will require changes for a couple of the endpoints. 

- [x]  SimulationRuns- `/runs`
- [x] Results -` /results`
- [x] Projects -`/projects`
- [x] Ontologies -`/ontologies` - This requires prefixing the `/ontologies' path to the API. I thought this was already the case, but seems it was removed.
- [ ] Combine - `/combine` and `/sedml `are easy to handle. @jonrkarr could `/kisao ` be changed? alternatively, we can have /combine be a prefix for all the routes (`/combine/sedml` and `/combine/kisao`)
- [ ] Simulators ` /simulators`

**Comment by jonrkarr** [comment]
Fine with me to change any of the routes.
