### ISSUE TITLE
Front End should fetch simulation  logs without refresh

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2736]
https://run.biosimulations.dev/simulations/60fadc0f75a71768c1b0ab55

**Comment by jonrkarr** [comment]
It looks like this functioned as intended.

This run does have a structured log. Stdout/err was also captured. The failure is fairly nicely displayed. There shouldn't be any simulation results because no simulation was run (due to the SED-ML being invalid).

**Comment by bilalshaikh42** [comment]
Seems like the front end needed to be refreshed. This should be fixed

**Comment by jonrkarr** [comment]
In my experience, refreshing isn't needed. Can you replicate this?

**Comment by bilalshaikh42** [comment]
Not sure what caused this. Can't replicate
