### ISSUE TITLE
Results API cannot process valid dataset

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2737]
Getting the following error for a results dataset that seems okay from the logs: 

```
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "meta": {
        "time": 1627054518475,
        "url": "/results/60fae1574180a0df5d7a0fc9?includeData=true"
      }
    }
  ]
}

{
  _type: 'SedReport',
  uri: 'simulation.sedml/report',
  sedmlId: 'report',
  sedmlName: '',
  sedmlDataSetDataTypes: [
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64',
    'float64', 'float64', 'float64'
  ],
  sedmlDataSetIds: [
    'time',
    'dynamics_species_A2c',
    'dynamics_species_A2m',
    'dynamics_species_A3c',
    'dynamics_species_A3m',
    'dynamics_species_aco',
    'dynamics_species_aps',
    'dynamics_species_C1',
    'dynamics_species_C2',
    'dynamics_species_cys',
    'dynamics_species_eth',
    'dynamics_species_eth_ex',
    'dynamics_species_H2O',
    'dynamics_species_Hm',
    'dynamics_species_Ho',
    'dynamics_species_hyd',
    'dynamics_species_N1',
    'dynamics_species_N2',
    'dynamics_species_oah',
    'dynamics_species_oxy',
    'dynamics_species_oxy_ex',
    'dynamics_species_pap',
    'dynamics_species_PPi',
    'dynamics_species_S1',
    'dynamics_species_S2',
    'dynamics_species_sul',
    'dynamics_species_sul_ex'
  ],
  sedmlDataSetNames: [
    'Time',
    'Dynamics of species "ADP"',
    'Dynamics of species "ADP_mit"',
    'Dynamics of species "ATP"',
    'Dynamics of species "ATP_mit"',
    'Dynamics of species "AcCoA"',
    'Dynamics of species "APS"',
    'Dynamics of species "C1"',
    'Dynamics of species "C2"',
    'Dynamics of species "CYS"',
    'Dynamics of species "EtOH"',
    'Dynamics of species "EtOH_ex"',
    'Dynamics of species "H2O"',
    'Dynamics of species "Hm"',
    'Dynamics of species "Ho"',
    'Dynamics of species "H2S"',
    'Dynamics of species "NAD"',
    'Dynamics of species "NADH"',
    'Dynamics of species "OAH"',
    'Dynamics of species "O2"',
    'Dynamics of species "O2_ex"',
    'Dynamics of species "PAPS"',
    'Dynamics of species "PPi"',
    'Dynamics of species "S1"',
    'Dynamics of species "S2"',
    'Dynamics of species "SO4"',
    'Dynamics of species "SO4_ex"'
  ],
  sedmlDataSetShapes: [
    '11', '11', '11', '11', '11',
    '11', '11', '11', '11', '11',
    '11', '11', '11', '11', '11',
    '11', '11', '11', '11', '11',
    '11', '11', '11', '11', '11',
    '11', '11'
  ],
  sedmlDataSetLabels: [
    'Time',
    'Dynamics of species "ADP"',
    'Dynamics of species "ADP_mit"',
    'Dynamics of species "ATP"',
    'Dynamics of species "ATP_mit"',
    'Dynamics of species "AcCoA"',
    'Dynamics of species "APS"',
    'Dynamics of species "C1"',
    'Dynamics of species "C2"',
    'Dynamics of species "CYS"',
    'Dynamics of species "EtOH"',
    'Dynamics of species "EtOH_ex"',
    'Dynamics of species "H2O"',
    'Dynamics of species "Hm"',
    'Dynamics of species "Ho"',
    'Dynamics of species "H2S"',
    'Dynamics of species "NAD"',
    'Dynamics of species "NADH"',
    'Dynamics of species "OAH"',
    'Dynamics of species "O2"',
    'Dynamics of species "O2_ex"',
    'Dynamics of species "PAPS"',
    'Dynamics of species "PPi"',
    'Dynamics of species "S1"',
    'Dynamics of species "S2"',
    'Dynamics of species "SO4"',
    'Dynamics of species "SO4_ex"'
  ]
}
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mError parsing data due to inconsistent atributes and values. Recieved ids, labels, shapes, names,types:[39m
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mtime,dynamics_species_A2c,dynamics_species_A2m,dynamics_species_A3c,dynamics_species_A3m,dynamics_species_aco,dynamics_species_aps,dynamics_species_C1,dynamics_species_C2,dynamics_species_cys,dynamics_species_eth,dynamics_species_eth_ex,dynamics_species_H2O,dynamics_species_Hm,dynamics_species_Ho,dynamics_species_hyd,dynamics_species_N1,dynamics_species_N2,dynamics_species_oah,dynamics_species_oxy,dynamics_species_oxy_ex,dynamics_species_pap,dynamics_species_PPi,dynamics_species_S1,dynamics_species_S2,dynamics_species_sul,dynamics_species_sul_ex[39m
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mTime,Dynamics of species "ADP",Dynamics of species "ADP_mit",Dynamics of species "ATP",Dynamics of species "ATP_mit",Dynamics of species "AcCoA",Dynamics of species "APS",Dynamics of species "C1",Dynamics of species "C2",Dynamics of species "CYS",Dynamics of species "EtOH",Dynamics of species "EtOH_ex",Dynamics of species "H2O",Dynamics of species "Hm",Dynamics of species "Ho",Dynamics of species "H2S",Dynamics of species "NAD",Dynamics of species "NADH",Dynamics of species "OAH",Dynamics of species "O2",Dynamics of species "O2_ex",Dynamics of species "PAPS",Dynamics of species "PPi",Dynamics of species "S1",Dynamics of species "S2",Dynamics of species "SO4",Dynamics of species "SO4_ex"[39m
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31m11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11,11[39m
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mTime,Dynamics of species "ADP",Dynamics of species "ADP_mit",Dynamics of species "ATP",Dynamics of species "ATP_mit",Dynamics of species "AcCoA",Dynamics of species "APS",Dynamics of species "C1",Dynamics of species "C2",Dynamics of species "CYS",Dynamics of species "EtOH",Dynamics of species "EtOH_ex",Dynamics of species "H2O",Dynamics of species "Hm",Dynamics of species "Ho",Dynamics of species "H2S",Dynamics of species "NAD",Dynamics of species "NADH",Dynamics of species "OAH",Dynamics of species "O2",Dynamics of species "O2_ex",Dynamics of species "PAPS",Dynamics of species "PPi",Dynamics of species "S1",Dynamics of species "S2",Dynamics of species "SO4",Dynamics of species "SO4_ex"[39m
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31mfloat64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64,float64[39m
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[ResultsService] [39m[31m0[39m
[31m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [31m  ERROR[39m [38;5;3m[DefaultFilter] [39m[31mError: Cannot process data[39m
Error: Cannot process data
    at ResultsService.<anonymous> (/app/main.js:1972:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[32m[Nest] 1  - [39m07/23/2021, 3:35:29 PM [32m    LOG[39m [38;5;3m[DefaultFilter] [39m[32mObject:[39m
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "meta": {
        "time": 1627054529326,
        "url": "/results/60fae1574180a0df5d7a0fc9?includeData=true"
      }
    }
  ]
}
```

**Comment by bilalshaikh42** [comment]
https://run.biosimulations.dev/simulations/60fae1574180a0df5d7a0fc9#tab=viz

**Comment by jonrkarr** [comment]
The input seems fine.

**Comment by bilalshaikh42** [comment]
Issue seems to be with the HDF5 output. contains many Nan and Infinity/- Infinities
@jonrkarr is this a case that the utils accounts for?

**Comment by bilalshaikh42** [comment]
The "root" cause of this was selecting a algorithm that did not really work at producing the results. (Range-Kutta instead of CVODE). I guess either the tellurium image should have failed, or the results should have been parsed anyway. The results were unable to be parsed bc they contained string values such as "infinity" and "-infinity" along with "NaN"

**Comment by bilalshaikh42** [comment]
This may be a mistake that users make, and we should provide a better error or display that the above. @jonrkarr can the utilities be fixed to correctly deal with the infinite case? I will look into perhaps marking the simulation as failed if the results cannot be processed. The above error was actually correct. The error was thrown bc the results were not processable, since the HSDS service returned and empty array of values

**Comment by jonrkarr** [comment]
I think each simulation tool has to be responsible for determining what is/isn't a failure. I don't think its a good idea to automatically equate NaN or Infinity with failure. Such values could be correct in some cases. BioSimulators utils can't be responsible for this because determining failure requires domain-specific information that only the simulation tools have. 

The data service and downstream should be able to handle NaN and Infinity. It probably won't be possible to see this through to Vega because Vega relies on JSON (rather than a variant that supports NaN and Infinity).

In this case, my opinion is that tellurium should have raised an exception. Unfortunately, many simulation tools probably don't have good error handling. This is related to also not having good testing.

**Comment by jonrkarr** [comment]
How does the HSDS return NaN and Infinity values? 

Handling this might be as simple as changing the default JSON parser used by the results service and frontend to one that supports NaN and Infnity such as [JSON5](https://www.npmjs.com/package/json5).

**Comment by bilalshaikh42** [comment]
> I think each simulation tool has to be responsible for determining what is/isn't a failure. I don't think its a good idea to automatically equate NaN or Infinity with failure. Such values could be correct in some cases. BioSimulators utils can't be responsible for this because determining failure requires domain-specific information that only the simulation tools have.

Sorry, I was unclear on this. The failure was not because of the existence of the infinity values. The values that were returned were an empty array, which is what triggered the error on the backend. Currently, it is possible for a simulation to be successful even if the results cannot be retrieved due to an error in processing the results. That was the case in which I was considering marking the simulation as failed.

**Comment by bilalshaikh42** [comment]
> How does the HSDS return NaN and Infinity values?
> 
> Handling this might be as simple as changing the default JSON parser used by the results service and frontend to one that supports NaN and Infnity such as [JSON5](https://www.npmjs.com/package/json5).

I will take a look at this. I have not yet debugged weather it is HSDS or the typescript code that is returning the empty values

**Comment by bilalshaikh42** [comment]
> The data service and downstream should be able to handle NaN and Infinity. It probably won't be possible to see this through to Vega because Vega relies on JSON (rather than a variant that supports NaN and Infinity).

The results API can only return valid JSON however, since any http libraries calling the API would fail to parse the json response.  I believe the same is true of the HSDS.

**Comment by jonrkarr** [comment]
In this case, my opinion is that tellurium should have raised an exception.

In that case, BioSimulators-utils could also check that tellurium didn't produce results of the requested length and raise an exception. However, I don't want to do this. As we push SED-ML to capture a broad range of simulations, only simulation tools will know how to run simulations. (Without more information encoded into SED-ML), BioSimulators-utils won't know what the shape of the results should be or what the data type should be. Simulation tools have to be responsible for this and raise exceptions as appropriate.
