### ISSUE TITLE
Submitting a new run fails if combine-service is not accessible

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2750]
Trying to submit this form fails. https://run.biosimulations.org/run?projectUrl=https:%2F%2Frun.api.biosimulations.org%2Frun%2F60f906bc227eb28472089ccb%2Fdownload&simulator=bionetgen&simulatorVersion=2.6.0&runName=Dolan%202020:%20Non-homologous%20end%20joining%20(BNGL,%20NFSim,%20BioNetGen)%20(rerun)

This is because the front end code is waiting for a response from the combine-service, currently down as in #2740. However, the combine service is optional, not required to submit a new run, so this should not cause the form to hang

**Comment by jonrkarr** [comment]
COMBINE service is used as part of suggesting a simulation tool. You're right that the service is not essential to simulation submission. We could change so its still works even if the COMBINE service isn't working.
