### ISSUE TITLE
Add page to publish simulation

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2768]
Todo
- [x] Add page
   - [X] Check simulation id defined
   - [X] Check run is valid for publication
   - [X] Display metadata errors if invalid
   - [X] Request human readable id
   - [X] Ask for confirmation that run captures the expected reusults
   - [X] Ask for confirmation of granting license to BioSimulations to publish the run
- [x] Uncomment input box for human readable name
- [x] Uncomment and implement check that id isn't already taken
- [x] Complete API call to publish simulation
- [ ] Grant web app permissions to POST projects
- [ ] Remove navigation to construction message

**Comment by jonrkarr** [comment]
Skeleton done.

**Comment by jonrkarr** [comment]
I think this is ready for #3067.

**Comment by bilalshaikh42** [comment]
@jonrkarr  If you are done working on the branch , ill rebase in the changes from dev

**Comment by jonrkarr** [comment]
Go ahead. I'm done with the branch.

**Comment by jonrkarr** [comment]
I think the only remaining issue is providing permissions to POST projects

**Comment by jonrkarr** [comment]
Closing. Remaining tasks are in #3412.
