### ISSUE TITLE
Renovate needs to be configured to update `Pipfile.lock`

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2781]
We're presently using pipenv (`Pipfile`, `Pipfile.lock`) to manage the requirements for DockerfilePython. In contrast, Renovate works with `requirements.txt`.

I think we need to make two changes:

(1) Add the following to `renovate.json` to instruct Renovate to work with the Pipfile for pipenv. See https://docs.renovatebot.com/python/.

```json
"pip_requirements": {
  "fileMatch": ["Pipfile"]
}
```

(2) Delete `requirements.txt` or add a CI action to sync this with `Pipfile.lock`
```sh
pipenv lock --requirements > requirements.txt
```

**Comment by bilalshaikh42** [comment]
Should be done.  Lets see if the change works on the next run

**Comment by jonrkarr** [comment]
Yeah, not entirely sure if Renovate will update `Pipfile.lock`. From their GitHub issues, its unclear whether Renovate is handling this correctly or not.
