### ISSUE TITLE
Simulation runs are broken

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2820]
All simulation runs are broken. 
Seems to be caused by https://github.com/biosimulations/Biosimulations/commit/107221acfef0d611dba986f1da1e1782c1472d91 or one of the later commits

**Comment by bilalshaikh42** [comment]
I rolled back the deployment, but will need to find out what caused the issue.  I've updated the submit script to include testing the functionality of running simulations that can be used to test any changes to the dispatch-service before committing

**Comment by bilalshaikh42** [comment]
@jonrkarr  I assume this is the line that caused the issue
https://github.com/biosimulations/Biosimulations/commit/107221acfef0d611dba986f1da1e1782c1472d91#diff-77fcbf9559c35612bd6da318c0016868a25f6746e19dc1b7160bcc2af5289d44R74

**Comment by jonrkarr** [comment]
I think its because I didn't correctly handle the case where there are no environment variables that need to be set. I should have checked this. I added a condition to handle this.
