### ISSUE TITLE
Handle many simultaneous users to combine-service

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2846]
If JWS or others want to use the combine-service to run simulations, we need to make sure that it can support multiple simultaneous users.

This is low priority since JWS seems to want to host simulations themselves.

**Comment by bilalshaikh42** [comment]
Is this currently not possible with the deployment? Or are you referring to the performance?

**Comment by jonrkarr** [comment]
It should be able to support multiple simultaneous users, although probably not very many. This is something we probably still need to work on.

**Comment by jonrkarr** [comment]
Additional pods could be assigned if needed.
