### ISSUE TITLE
Combine service container uses large amount of memory

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2851]
The deployed container for the combine service uses up to 900Mi, causing the nodes to run out of memory.

**Comment by jonrkarr** [comment]
That doesn't necessarily sound so bad. Do you know what was it before? Or before the new `/run` endpoints are executed?

**Comment by bilalshaikh42** [comment]
With the two deployments and 3 replicas by default, it adds up to roughly 6Gi, which is enough to cause issues on the nodes.

 The dispatch-api for example is around 100Mi. 
Before calling the endpoints, the combine API uses about 150 Mi

**Comment by jonrkarr** [comment]
The memory is likely due to the simulator modules. They're setup to only be imported as necessary to run a simulation. Like all Python modules, once they're imported they remain in Python's module cache. I could try forcing Python to release them from this cache (`del sys.modules[...]` for each module and submodule)

The `/run/simulators` endpoint causes all modules to be imported. The `/run/run` endpoint imports only the requested simulator.

If others wanted to use the simulation endpoint, the simplest solution might be to use a higher memory instance.

**Comment by jonrkarr** [comment]
To my knowledge, there's no recognized way to unload Python modules.

Deleting modules (`del sys.modules[...]`) doesn't seem to work. This seems to make things worse. The modules doesn't appear to be completely released from memory and they're re-imported. I tried some variations of this where I keep biosimulators_utils modules but delete modules for individual simulators. This seems to create an inconsistent state.

An alternative solution is to execute simulations in isolated memory environments. 
- One option is the [process-isolation package](https://alexflint.github.io/process-isolation/). Unfortunately, this needs converted from Python 2 to 3. I tried the `2to3` tool, but that wasn't enough. It would need to be updated by hand. Its only ~1000 lines, so it should be manageable. This uses the multiprocessing module. 
- Alternatively, we could implement something ourselves using `multiprocessing` or `subprocess`. I'm pretty sure `subprocess` would work, but be less efficient.

**Comment by jonrkarr** [comment]
We could also consider 
- (Easy) For now, only deploy `/run` on `.dev` so we don't kill the performance of the other endpoints while we figure this out.
- (More work) Run the `/run` endpoints as a separate app to isolate its deployment from the other functionality.

**Comment by bilalshaikh42** [comment]
The memory usage seems to have gone down to reasonable level (300mi). We are still running into issue however as the gunicorn managed processes are timing out.

**Comment by jonrkarr** [comment]
I'll push a patch to disable these endpoints on `org` until we can work this out.

**Comment by jonrkarr** [comment]
Memory usage is down. Additional issues can be opened for other problems as needed.
