### ISSUE TITLE
Restore background color to white

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2855]
This most noticeable on some pages
https://run.biosimulations.org/simulations/6101f585414ac58ab96b7f68#tab=viz

Likely due to a change in material.

**Comment by bilalshaikh42** [comment]
Sorry about this, it should have been automatically migrated. 
Here are the instructions from angular 

> Sass imports from @angular/material/theming are deprecated. There is a new Angular Material Sass API for @use. Run the migration script ng g @angular/material:themingApi to switch all your Sass imports for Angular CDK and Angular Material to the new API and @use.

**Comment by jonrkarr** [comment]
I think we only have a few SASS files.

**Comment by bilalshaikh42** [comment]
This refers to importing the base theme I believe. The scss files are also
considered sass I believe, just a different syntax.

**Comment by jonrkarr** [comment]
I don't think that's the source. We're not using `material:themingAPI`. I think this is due to a change in the default styling of the  `mat-drawer-container`, one of the material components.
