### ISSUE TITLE
Missing simulation Id causes front end to crash 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2910]
The example RBA model has an id of XXXXXXX 
If this is included in the list of users simulations, the app will go to a 404 error page, even if that is not the simulation that was selected. This is related to the overly sensitive error handling mentioned in #1950

**Comment by jonrkarr** [comment]
Thanks for noticing. I didn't intend to commit that.
