### ISSUE TITLE
Create a 'Visualization" object

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2913]
In the dispatch front end,  the combine service is used to determine the various visualizations included in a simulation run. This information should be extracted upon submission, and stored in the database as its own resource type. 

The same implementation style that is used for the metadata extraction should be used here, so that the dispatch-service can call the combine service, not the front end.

**Comment by jonrkarr** [comment]
This information is now pretty easy to get from the files and SED-Ml specs stored in the database. I think this substantially removes the need for this. The pages now look fairly quickly.

**Comment by jonrkarr** [comment]
Superseded by #3439 and new summary endpoints
