### ISSUE TITLE
Create "File" object 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2914]
When an omex archive is uploaded, it is saved as 1 object on s3, and a database entry is created with some properties of the file and its location (provided as a url). 
This should be extended to all the files in the omex archive. Each file will have a database entry, and each file can be addressed individually. This will happen once on submission and the locations will then be available in the database, removing the need to query the combine service for each file on the frontend.

**Comment by jonrkarr** [comment]
Attributes
- Location within COMBINE archive (copied from manifest)
- Format URI (copied from manifest)
- File size
- S3 URL -- could be included here, or there could be another way to get the base S3 url for a project
