### ISSUE TITLE
chore(deps): update dependency @ionic/storage to v3

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2922]

**Comment by jonrkarr** [comment]
Appears to require to changes
- `import { IonicStorageModule  } from '@ionic/storage' --> `import { Storage } from '@ionic/storage-angular'
- `import { Storage } from '@ionic/storage' --> `import { Storage } from '@ionic/storage-angular'
- `driverOrder: ['indexeddb', 'websql', 'localstorage']` --> `driverOrder: [Drivers.IndexedDB, Drivers.LocalStorage]`
- `storage.ready()` --> `storage.create`
