### ISSUE TITLE
Refreshing images fails with 500 error

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2937]
https://run.api.biosimulations.org/images/refresh

**Comment by bilalshaikh42** [comment]
The connection to the HPC was disrupted for a bit. It is working now?

**Comment by bilalshaikh42** [comment]
Fix should be rolling out now

**Comment by jonrkarr** [comment]
Just tried again. It isn't working. It this something will be deployed after a delay?

**Comment by jonrkarr** [comment]
Seems to be working now
