### ISSUE TITLE
Organize scripts and related data files for importing models from model repositories

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2950]
In the `model-importing` branch, I started an "app" to import models from model repositories (e.g., BiGG, BioModels, etc.)
- This will likely be implemented in Python
- This will probably be Python scripts and small data files which keep track of which entries of each repository have been imported and when they were last updated, which the scripts will use to determine which entries are new or have been updated.
- We can probably use the same DockerfilePython/pipenv for the combine-service. Additional dependencies can be added as `dev` dependencies.
- I'm thinking we'll want to setup GitHub Action cron tasks to run the scripts to periodically pull new content from model repositories and push them to RunBioSimulations and then BioSimulations.
- We'll want unit tests, as well as the source code
- This is just for our internal use
- This will not need to be deployed or shared to the community. We can just focus on sharing the end result through BioSimulations.
- As a result, I don't think we need to document this

@bilalshaikh42 thoughts on how to organize this?

**Comment by bilalshaikh42** [comment]
This probably makes more sense in a separate repo. Since the scripts are in python, they won't be making use of the shared data model anyway, and the point of the monorepo is more to assist with consistency across deployments. 

For this package, we can actually use the API-specs to create a library to call the API. That way the python code will responsible for importing the models and then can just use the API to submit them.

**Comment by jonrkarr** [comment]
That's what I started for BioModels.  Then I thought maybe its simpler to organize everything here even though its quite separate.

Depending on how source model repository are willing to collaborate, this may also be temporary.

**Comment by bilalshaikh42** [comment]
I see on the branch now that you just have a folder for the app, and not actually integrating it into the build system.  That is fine and works if its easier

**Comment by jonrkarr** [comment]
Correct, I'm thinking this could be a folder organized under apps. It wouldn't need to be built. Any linting/unit tests could be managed separately. We might just want a semantic versioning scope for it.

**Comment by jonrkarr** [comment]
Thinking again, I agree we should organize this into a separate repository.

The main reason is that we would like the source repositories to help with this. I'd like to keep that as simple as possible by keeping it separate from this repository.
