### ISSUE TITLE
Metadata loading in RunBioSimulations is broken

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2951]
The `//` issue is fixed in the `dev` deployment
https://api.biosimulations.org//metadata/6101f588414ac522336b7f6e

However, the metadata endpoints also fail, e.g.
https://api.biosimulations.org/metadata/6101f588414ac522336b7f6e

Do the example simulation runs need to be re-generated?

**Comment by bilalshaikh42** [comment]
Yes, I regenerated them for the dev branch, but not the production.  Github actions seems to be having some issues, so I have not been able to deploy them yet

**Comment by bilalshaikh42** [comment]
Build issues should be fixed. Regenerating examples and deploying shortly

**Comment by bilalshaikh42** [comment]
I didn't notice this issue at first, but technically the latest changes I made have broken support for older submissions since they won't have any metadata present in the database.  Don't think we need to worry about this too much yet, but we should be more mindful of ensuring older runs still work

**Comment by jonrkarr** [comment]
I think we don't need to worry about previously submitted runs
