### ISSUE TITLE
Results download broken

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2959]
Example:
https://run.api.biosimulations.org/results/6134edbdd73440e9b686f488/download

**Comment by bilalshaikh42** [comment]
Still running into this issue. Might be a change on the unconn side.

**Comment by bilalshaikh42** [comment]
Was a config error. Storage endpoint was not set in the config, so the default value was selected. The default value has http as the protocol instead of https. The default value should be updated
