### ISSUE TITLE
Forward model repository documentation (e.g., https://biosimulations.github.io/biosimulations-bigg) to GitHub pages

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2965]
I think it makes sense to have individual packages for importing separate model repositories. These will have a small amount of documentation. The first one will have documentation at https://biosimulations.github.io/biosimulations-bigg.

Can we make https://docs.biosimulations.org/biosimulations-bigg or https://docs.biosimulations.org/bigg point to the above URL?

**Comment by bilalshaikh42** [comment]
Sure. I am working on the docs at the moment, so can add that in alongside the other changes

**Comment by bilalshaikh42** [comment]
Should nest this under some folder? For example https://docs.biosimulations.org/repos/bigg or https://docs.biosimulations.org/sources/bigg ?

**Comment by jonrkarr** [comment]
Nesting it and stripping off the "biosimulations_" prefix would be nice.

**Comment by jonrkarr** [comment]
I like the theme you chose. I could switch the Python docs to a more modern theme. There's a bunch of themes at https://sphinx-themes.org/. Do you like one of these?
- Book
- Furo
- Press

**Comment by jonrkarr** [comment]
There's a few more at https://sphinxthemes.com/#featured-themes including a [material theme](https://bashtage.github.io/sphinx-material/) that's similar to the theme you're using.

**Comment by bilalshaikh42** [comment]
These docs are actually made with mkdocs instead of sphinx. The theme is [mkdocs-material](https://squidfunk.github.io/mkdocs-material/getting-started/)  which adds quite a bit of functionality. 

There is sphinx [material](https://bashtage.github.io/sphinx-material/) if you want to try to match the look of them. Of the 3 you mentioned, I like furo the best.

**Comment by bilalshaikh42** [comment]
On an unrelated note, github does not seem to be updated the deployment of the pages. The last deployment was 12 hours ago

**Comment by bilalshaikh42** [comment]
Opened a ticket for this: https://support.github.com/ticket/personal/0/1300231

**Comment by jonrkarr** [comment]
I know you're using mkdocs. I could try to match the look with the material theme.

**Comment by bilalshaikh42** [comment]
Ticket is resolved, and builds seem to be going through again

**Comment by bilalshaikh42** [comment]
Here is the url to the bigg import docs: https://docs.biosimulations.org/repositories/bigg
