### ISSUE TITLE
On a users profile, the personal website link does not work 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#297]
On the user profile, clicking on the link to the user's personal website redirects to https://ourdomain/userdomain rather than https://userdomain as it should

**Comment by jonrkarr** [comment]
The value of the profile URL should be a complete URL beginning with `http(s)`. In this case, the profile page displays the URL correctly.

The profile edit form should validate URLs to begin with `http(s)`.

**Comment by bilalshaikh42** [comment]
Got it. So in the case where I ran into this issue, it was because the form did not validate. The linked issue is the underlying cause.

**Comment by jonrkarr** [comment]
The forms have almost no validation. This needs to be implemented.
