### ISSUE TITLE
Remove extra field in feedback component form when Bruit is fixed

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#299]
Change `type` of `Comments` to `textarea` in Bruit config in `src/environment/environment*.ts`

**Comment by bilalshaikh42** [comment]
I was able to get the feedback working by adding a dummy form object as the first element, which for some reasons gets converted to a checkbox. We can remove that when the bug is fixex

**Comment by bilalshaikh42** [comment]
It also seems that the feedback won't send if the user does not click the consent box for extra information, though it should create an issue without the technical data. Not sure what is causing that either.

**Comment by jonrkarr** [comment]
Looks like this fixed. See [GitHub issue](https://github.com/Moventes/bruit.io/issues/61#issuecomment-574749371) for Bruit.

`@bruit/component` needs to be updated to 1.3.11

**Comment by jonrkarr** [comment]
I think the consent box must be checked for any information to be sent. When the consent box isn't checked, I think Bruit intends for submission to be invalid. If this isn't what's happening, submit a Bruit issue: https://github.com/Moventes/bruit.io/issues/.

**Comment by bilalshaikh42** [comment]
Yes, I did notice that.  A quick fix is to mark the consent field as required on the config, which makes the behavior less confusing

**Comment by jonrkarr** [comment]
I just pushed that and submitted a [Bruit issue](https://github.com/Moventes/bruit.io/issues/63).
