### ISSUE TITLE
Missing metadata causes 404 page

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2994]
Any 404's across the app end up redirecting to the 404 page. Need to find where the 404s are generated, and appropriately handle them at the source rather than getting to the error handler. The error handler should only be catching rare errors that were not properly handled by mistake.

**Comment by jonrkarr** [comment]
All intended error signals should already be getting caught. Redirects to the 404 page are due to unintended errors. The error handler could be changed to print errors to the console in production.

**Comment by bilalshaikh42** [comment]
Currently missing logs, metadata or results seem to cause redirection to
the 404 page. For the logs and metadata I just need to add in error handling

**Comment by bilalshaikh42** [comment]
Split into #2999
