### ISSUE TITLE
Simulation results retrieval broken

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3013]
Example: https://api.biosimulations.org/results/6132c885780779f102355af0?includeData=false

**Comment by bilalshaikh42** [comment]
Caused by https://github.com/HDFGroup/hsds/issues/105.   I am unable to restore the previous behavior just by
tweaKing the deployment settings, unfortunately.

**Comment by jonrkarr** [comment]
Thanks for following up. Seems like an unfortunately thorny issue.

**Comment by bilalshaikh42** [comment]
Resolved
