### ISSUE TITLE
Load thumbnail images for simulation projects from S3 bucket

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3039]
- [x] Unpack COMBINE archives to S3 bucket -- #2914
- [ ] Store list of files and S3 ids in database -- see also #2945
- [x] Change dispatch apps to load images from bucket
- [x] Change platform app to load images from bucket

**Comment by bilalshaikh42** [comment]
Should be covered by #2914  and #2945

**Comment by bilalshaikh42** [comment]
The platform front end is hitting the files endpoint, which currently redirects to the combine-service. This should redirect to the s3 URL. No change should be needed to the frontend

**Comment by jonrkarr** [comment]
I think we should unpack all files, save them all to S3, and record the list of all files into the database. Then at some point we could display the full list of files in the archives in the UIs and allow individual downloads (similar to other model repositories).

**Comment by bilalshaikh42** [comment]
Right, that is the intention of #2914
