### ISSUE TITLE
Customize style of Swagger apps

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3041]
Use BioSimulators/BioSimulations colors and fonts.

Could potentially switch to a material-like base theme
http://ostranme.github.io/swagger-ui-themes/

- [x] API
- [x] Accounts API
- [x] Simulators API
- [x] COMBINE API

**Comment by bilalshaikh42** [comment]
Done for api
Stylesheet is located here: https://github.com/biosimulations/static/blob/dev/stylesheets/biosimulations_swagger.css
This deploys to https://static.biosimulations.org/stylesheets/biosimulations_swagger.css
That is loaded in as the customCssUrl field in setting up the swagger doc

**Comment by jonrkarr** [comment]
Nice!
