### ISSUE TITLE
Add searching and filtering to platform browse projects view

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3042]
- Could be placed in a pop-up box to keep the UI clean
- Search could be done in-browser using [Lunr](https://lunrjs.com/), similar to the dispatch simulations and simulators table.

**Comment by bilalshaikh42** [comment]
An important architectural point for this would be to ensure that the project-card-list component does not contain any logic that handles filtering/searching. It should remain a purely functional component that is provided a list of projects as an input. Any filtering should happen at a higher level component that can then simply update the input to the card list component.

**Comment by bilalshaikh42** [comment]
@jonrkarr I can start working on this if you have not yet

**Comment by jonrkarr** [comment]
Please start with the processors so that we can get simulation results visualized in the platform. This is the key output of our key advance.
- list of files (manifest)
- SED-ML content (needed for visualizations)
- Vega
