### ISSUE TITLE
Restrict the platform to public simulation runs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3044]
The endpoints that the platform relies on to retrieve the list of simulation runs must only return runs with `public=true`. It is important not to publicly display all runs that users have submitted. Doing so would breach their trust.
- [ ] List of runs
- [ ] Metadata for runs

**Comment by bilalshaikh42** [comment]
This was an oversight. Forgot to set the query parameters correctly to only return the public models
