### ISSUE TITLE
fix display of licenses for simulation runs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3050]
Example
https://run.biosimulations.org/simulations/6132c885780779f102355af0#tab=project

**Comment by bilalshaikh42** [comment]
Metadata api returns an array of  
```typescript
 {label: string, uri: string}
```
I believe the front end expected just a single value, but I forgot to update it.

**Comment by jonrkarr** [comment]
I traced this. I believe the bug is in the `apps/dispatch-api` or `apps/dispatch-service` code somewhere between in the second step below. Somewhere that code is unintentionally transforming the license from an object to a list of objects.

The types appears to be correct everywhere -- license is consistently typed as an object. Somewhere the code is diverging from the typing, presumably somewhere where the typing is loose.

1. License in an object
  i. COMBINE API: returns a license object; this aligns with the expected type.
  ii. `srcHandlersCombineGetMetadataForCombineArchiveHandlerBiosimulations` appears to preserve this
  iii. `convertMetadata` appears to preserve this
2. License appears to be transformed from an object to a list
  i. POST `https://run.api.biosimulations.dev/metadata/615223bcfd47f2d4392a91c9` appears to receive a license object
  ii. `createMetadata`appears to receive a license object
3. License has become a list of objects
  i. `https://run.api.biosimulations.dev/metadata/615223bcfd47f2d4392a91c9` returns an list of licenses even though its typed as an object
  ii. `metadataService.getMetadata` receives a list of licenses
  iii. `initSimulationProjectMetadata` receives a list of licenses
  iv. `view.component.html` receives a list of licenses

**Comment by bilalshaikh42** [comment]
I believe the original data model provided in one of the issues had an
inconsistency where the license was displayed as a list in one example and
a single value in another. I chose to simply make it a list to match all of
the other fields. Later I realized the combine service was returning a
single object, so I converted it to match the expected datamodel.

I think its probably easier to update the view component to keep the logic
for all the fields the same

**Comment by jonrkarr** [comment]
The result from the dispatch-api diverges from the expected type.

I think the types are consistently defined everywhere, including in the COMBINE API and Python code. The logic in the view component is correct for the expected type. However, the view component doesn't work with input that doesn't match the expected type.

**Comment by jonrkarr** [comment]
Alternatively, we could make license a list everywhere. This means changing the types throughout the dispatch app, dispatch-service, and dispatch-api. I don't we need to do this because its close to consistently being an object. There's just one place where the typing is diverging.

**Comment by bilalshaikh42** [comment]
All of the typescript code should be consistent other than the frontend.
Currently, I am able to loop through all the fields and use the same logic
to handle them. I can make the change if you strongly prefer, but I would
need to handle the licence field differently from all the other cases. It
would also prevent using models that are dual-licenced

**Comment by bilalshaikh42** [comment]
Oh, it seems I was incorrect. The model is not consistent on the API. I
thought I had already made that change.

**Comment by jonrkarr** [comment]
Either way is fine as long as its consistent everywhere.

I think multi licensing a little more complicated. License-X OR License-Y isn't the only possibility. This package illustrates more complex combinations. I think we should punt on this. I opened an issue about this a while back.
https://www.npmjs.com/package/spdx-expression-parse
biosimulations/biosimulations#1862

**Comment by bilalshaikh42** [comment]
I'll make the change

**Comment by jonrkarr** [comment]
Thanks!
