### ISSUE TITLE
Remove double slash in metadata.uri for simulation runs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3052]
Example
`6151fe6b44ba7df46bce0904//simulation_1.sedml/Figure_3a`
https://api.biosimulations.dev/metadata/6151fe6b44ba7df46bce0904

**Comment by bilalshaikh42** [comment]
This is based on the environment variables set for the domain. The thumbnails in this case are set to "/combineapi/..." so this must have been run locally and had the env variable set incorrectly. Does this appear on any runs started on the deployed versions?

**Comment by bilalshaikh42** [comment]
This does show up even when run on the deployment, so is indeed a bug
