### ISSUE TITLE
Example simulation run failed for unknown reason

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3056]
http://localhost:4200/simulations/615223bbdfce8b155e4da29d#tab=log

**Comment by bilalshaikh42** [comment]
rerun seems to be fine https://run.biosimulations.dev/simulations/6152a16c8499dd75aab03c60

**Comment by bilalshaikh42** [comment]
Seems that the job failed on the HPC for some reason. Unfortunately, the logs don't show any issues, so must have been some sort of transient error with getting the status. 
Closing for now
