### ISSUE TITLE
Handle academic use of Gurobi

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3059]
Issue discussed with @mpw6 @moraru 

- [x] Add academic use checkbox to simulation run form
- [x] Add academic use key to simulation run model
- [x] Only use Gurobi keys when academic use = true

**Comment by bilalshaikh42** [comment]
Should we require logging in with a verified .edu email to use the academic license?

**Comment by jonrkarr** [comment]
This is intended to be a relative simple start to addressing the issue. Email verification would be better. Since this is more work, I separated this to another issue: #3068.
