### ISSUE TITLE
Restrict direct publication of simulation runs to trusted users

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3065]
- [ ] dispatch API `POST` and `PATCH` `/runs` should only allow `public=true` for privileged users; other users should have to go through the dispatch app web GUI where they must review the outputs of their run before making it public
- [ ] Make the dispatch app web GUI such a privileged user
- [ ] Create tokens for model repositories to also be able to directly publish runs without having to manually them -- essentially, we would delegate review to trusted model repositories

**Comment by bilalshaikh42** [comment]
> - [ ] dispatch API `POST` and `PATCH` `/runs` should only allow `public=true` for privileged users; other users should have to go through the dispatch app web GUI where they must review the outputs of their run before making it public

The intention was to have the published projects be a separate object that can only be created via an authenticated call from the API, but only after some sort of server-side validation occurs. Having a GUI based validation provides a user experience suggesting some sort of check, but could always be overridden by an API call

> - [ ] Make the dispatch app web GUI such a privileged user

This is not really possible. The only way to do this is a via a token that would be embedded in the source and not hidden

**Comment by bilalshaikh42** [comment]
@jonrkarr can we close this is favor of #3067?

**Comment by jonrkarr** [comment]
Closed in favor of #3067.
