### ISSUE TITLE
Vega visualization doesn't resize when window is resized and visualization is hidden (e.g., when a different tab is open)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3087]

**Comment by bilalshaikh42** [comment]
I have a fix for this is a local branch.  Its diverged quite a bit now, but here is the code I was able to adapt. the refresh method can be replaced with the render method that we use

```
@ViewChild('map') m;
private isVisible: boolean = false;
ngAfterContentChecked(): void
{
    if (this.isVisible == false && this.m.nativeElement.offsetParent != null)
    {
        console.log('isVisible switched from false to true');
        this.isVisible = true;
        this.Refresh();
    }
    else if (this.isVisible == true && this.m.nativeElement.offsetParent == null)
    {
        console.log('isVisible switched from true to false');
        this.isVisible = false;
    }
}
```

**Comment by bilalshaikh42** [comment]
This bypasses all the issues with detecting when to change the rendering/size by just rendering when the tab was not in view and now is. One issue with this is that this fires very very often when actually dragging to resize the window and can easily overwhelm the results endpoint since the vega keeps calling the results endpoint each time

**Comment by jonrkarr** [comment]
I tried putting your suggestion into the Vega component to no avail. Try again after my changes are pushed.

While we're doing this for testing purposes, users probably won't resize much. I think we can ignore the issue regarding overloading the results endpoint.

The plotly visualization has the same issue.

**Comment by jonrkarr** [comment]
Solved with [ResizeObserver](https://www.npmjs.com/package/@juggle/resize-observer).
