### ISSUE TITLE
Additional Endpoints and organization

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3093]
There's two things we'd ideally do next to reduce the data we're pulling from the API to populate

Reasons for processing out information
- List of visualizations in the view route
- Filter simulations in the browse route on additional attributes not currently available in the SimulationRun or metadata

Data to process out
- Process out the visualizations
  - Create a list of visualization objects
  - Create an endpoint to return the ids/names of the visualizations
  - Create an endpoint to return the details of an individual visualization -- this could parallel these data models: https://github.com/biosimulations/biosimulations/blob/polish-published-simulation-view/libs/datamodel/view-simulation/src/lib/view-simulation.ts#L6
- Process out some additional simulation run metadata
  - From SED-ML specs
    - Set of model formats (e.g., `urn:sedml:langauge:sbml`)
    - Set of simulation types (e.g., uniform time course)
    - Set of algorithms (KISAO ids)
  - From logs
    - Duration
    - Set of executed algorithms

Thoughts for organizing this
- Visualizations: Separate, new endpoints
- Simulation run metadata: no strong thoughts here. This could be returned via a separate, new endpoint for simulation run metadata. This would distinguished from SimulationRun which contains information about the requested run. Also, this would be read only information (unlike SimulationRun) derived from the submitted COMBINE archive.

_Originally posted by @jonrkarr in https://github.com/biosimulations/biosimulations/issues/3089#issuecomment-933016395_

**Comment by jonrkarr** [comment]
Partly done by new summary endpoints
