### ISSUE TITLE
Move combine archive extraction and uploading to s3 from hpc to dispatch-service

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3094]
The combine archive is unzipped on the HPC and then uploaded along with the rest of the output to s3 at the end of the simulations run. 
It might make sense to have the API/dispatch service handle this 
Pros
1. can get information about size directly. Currently are using additional HTTP calls to make head requests to get size 
2. can get URL information directly instead of hardcoding it throughout app
3. can keep track of the URL for the archive itself (alternatively, just name all the archives as input.omex)
4. One less step on slurm to track/monitor
5. Speedup? 
Cons:
1. harder than just using the sync CLI tool 
2. Need to coordinate uploading the outputs 
3. Keep track of when its complete

**Comment by jonrkarr** [comment]
Each call do the COMBINE service is also downloading the COMBINE archive. Ideally, we'd also factor out that repeated work.
