### ISSUE TITLE
Add status indicators to relevant components

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3129]
- [x] platform
  - [x] browse projects
    - [x] list
    - [x] individual images
  - [x] view projects
    - [x] Main page loading
       - Run metadata
       - Project metadata
       - Files
       - List of visualizations 
    - [x] Loading data for Vega visualizations
    - [x] Loading data for SED-ML visualizations
    - [x] Loading data for user designed visualizations
    - [x] Exporting to Vega
    - [x] Exporting to COMBINE archive
- [ ] dispatch
  - [x] Browse simulations
  - [ ] View simulation
  - [x] web forms
    - [x] validate model
    - [x] validate simulation
    - [x] validate metadata
    - [x] validate project
    - [x] create project
    - [x] suggestion simulation tool
    - [x] run simulation
    - [x] publish simulation
- [x] simulators
  - [x] browse
  - [x] ~~view simulator~~: not that much data loaded

**Comment by bilalshaikh42** [comment]
@jonrkarr should i work on this? Or is it a part of #3084

**Comment by jonrkarr** [comment]
This is only partly addressed by #3084. 

I'll leave spinners and error handling to you. You seem to have thoughts about how to best handle this.
