### ISSUE TITLE
Simulation runs failed for no clear reason

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3135]
- [x] dev: 615b562c2f1add0daafd6d2e (tellurium)
- [ ] org: 61610ddf09e39101d573cbab (COBRApy)
- [ ] org: 61610e1ae3fd8649821315d3 (COBRApy)

**Comment by bilalshaikh42** [comment]
I noticed this and have been looking into it. I cannot figure out why the
status check will sometimes fail. Everything seems to run just fine on the
backend

**Comment by bilalshaikh42** [comment]
Im going to keep this open as I want to add logging to trace why this happens. I assume it must be some sort of transient error with ssh that the code interprets as getting back a "failure". I have not been able to pinpoint what the actual response that causes this is, but that is the only feasible cause. It should be an easy fix, but its annoying to try to track down since it happens relatively rarely

**Comment by jonrkarr** [comment]
Here's two more (of 89) that failed in publishing the BiGG models. These are both on `org`. The same OMEX files succeeded in subsequent runs, so the OMEX file probably isn't the issue.

- `61610ddf09e39101d573cbab`
- `61610e1ae3fd8649821315d3`

**Comment by jonrkarr** [comment]
I'll compiled any failed runs to the first message

**Comment by jonrkarr** [comment]
This sounds like an issue I fixed. Previously, the code was only checking the status of the last step within the sbatch group reported by sacct. However, saact doesn't immediately return the full list of steps. Its possible for the last step reported by sacct to be completed, while other steps haven't even begun yet (or have failed). I think its safer way to check this is to focus on the status of the first output of sacct, which reports the status of the entire run, and to check the status of each individual step. The state of the entire job doesn't change to completed until each step completes.

In addition, the code now checks that status of each individual step, including the unzip step which wasn't previously monitored by SLURM. Simulation runs are now interpreted as failing if any step fails. Before, it was possible, for example, for the the run to be interpreted as succeeded even if the HSDS storage step failed because the code had only been checking the status of the final step (storage to S3).

Log messages are also now improved by naming each step (`--job-name`). This enables the code which checks their status (looking for each step to have succeeded) to list the failed steps by their names. This also removes the reliance on the job steps being at specific indices (since they're identified by their names rather than step numbers).

@bilalshaikh42 close this if it sounds like the error you saw. If you intend to improve the logging of failures please open a new issue which outlines that.

**Comment by bilalshaikh42** [comment]
Sounds great. Thanks!
