### ISSUE TITLE
Allow CORS access to https://files.biosimulations.org/s3 from localhost

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3139]
Ports
- 4200
- 4201
- 4202

**Comment by bilalshaikh42** [comment]
@moraru is this something that we can do? 
Alternatively we can use https://github.com/garmeeh/local-cors-proxy

**Comment by bilalshaikh42** [comment]
Another alternative for dev work
https://alfilatov.com/posts/run-chrome-without-cors/

**Comment by bilalshaikh42** [comment]
consolidate in #3159
