### ISSUE TITLE
Debug plotly issues 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3142]
Either switch to cdn or work out how to deal with https://github.com/plotly/plotly.js/issues/5925
Might be fixed by fixing  #2926

**Comment by jonrkarr** [comment]
Can you simply add the missing ndarray dependency? And make a todo to remove it once plotly's distribution is fixed?

**Comment by bilalshaikh42** [comment]
It seems they are using a custom version of the dependency that is not on npm, but on github. Older versions of npm are not able to resolve this properly. 
I've just pinned the version of plotly to the latest one  that works. I think that when we  update npm/node this should resolve itself and we can just close.
