### ISSUE TITLE
Remove SimulationRunFile  object

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3146]
There is a simulationRunFile in the database that contains information about the omex archive. Now that we have a list of all the associated files of the simulations, this should be added there instead

**Comment by jonrkarr** [comment]
`SimulationFile` in `apps/api/src/simulation-run/file.model.ts`

**Comment by jonrkarr** [comment]
This is going to be a breaking change. This would be a good point to clear the databases and rebuild the examples and published projects.
