### ISSUE TITLE
Allow CORS to to s3 from front end urls

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3159]
Access to fetch at 'https://files-dev.biosimulations.org/s3/simulations/615b55fa3b2a0dd76c664fdb/contents/activity-flow-diagram.vega.json' from origin 'https://run.biosimulations.dev' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by bilalshaikh42** [comment]
I sent an email to @mpw6 and @moraru. I can try to set up a proxy on our API if this takes long, but that will be a bit annoying. We didn't run into this issue before because I was using the API to download the file and then send it to the browser, which I could try to restore

**Comment by bilalshaikh42** [comment]
We are running into some CORS issues for the s3 domains at files.biosimulations.org/s3 and files-dev.biosimulations.org/s3. 

Could we get cors added for *.biosimulations.org,  *.biosimulations.dev, *.biosimulators.org, and *.biosimulators.dev. If the wildcard domains are not supported, we need at least the following: 

run.biosimulations.org
run.biosimulations.dev
biosimulations.org
biosimulations.dev
biosimulators.org
biosimulators.dev

It would also be helpful to have http://localhost:4200 added as well for  development

**Comment by bilalshaikh42** [comment]
Figured out how to do this on the console. Done.
CORS is enabled for Get requests, which should be all that is needed.
