### ISSUE TITLE
Add a files download endpoint

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3162]
For each file add an endpoint /download to redirect the user to the s3 URL. This should be sufficient to prevent #3159

**Comment by jonrkarr** [comment]
That would work

**Comment by bilalshaikh42** [comment]
It might not, https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSExternalRedirectNotAllowed

Worth a shot, i'll have it up shortly

**Comment by jonrkarr** [comment]
Wouldn't a proxy work? A service which downloads from S3 and then forwards that along. Obviously this would add extra overhead.

**Comment by jonrkarr** [comment]
Solved by @bilalshaikh42
