### ISSUE TITLE
Vega window resize events need to be debbounced

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3165]
Window resize event  fires very often as a window is being dragged sending multiple requests to API. This can easily be fixed via an observable from event, piped through a debounce

**Comment by jonrkarr** [comment]
There are probably other unnecessary repeated REST queries in the new shared project-service that could be avoided with this. I haven't paid attention to this.

**Comment by bilalshaikh42** [comment]
If there are other repeated requests they are probably on the order of 3/4
where we could optimize it to 1. But since this one is tied to the window
resize event, which fires a lot, even for a relatively small resize, it can
easily send out 100 or more requests.

**Comment by jonrkarr** [comment]
I think this is pretty easy to fix with rxjs operators. I'm haven't taken the time to understand them.

**Comment by bilalshaikh42** [comment]
Yup, the Debounce operator is what we need. Just a one line fix, I'll put
it in

**Comment by jonrkarr** [comment]
Fixed for Plotly as well as in #3333
