### ISSUE TITLE
Add cache to API endpoint for results 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3166]
The api can maintain a cache for the simulation results. This is probably very useful since a user exploring a simulations/changing graphs around will be hitting the same simulation endpoint repeatedly. No need to go read the hdf5 file every time

**Comment by jonrkarr** [comment]
There seems to be some form of caching already. The results endpoint is much faster after the initial successful call.

**Comment by bilalshaikh42** [comment]
Yes, that is happening on the HSDS service. So I suppose technically, we
are not rereading the hdf5 file every time, but the API sends a request to
HSDS. That response can be cached. All I need to do is add a @Cache()
decorator to the method

**Comment by jonrkarr** [comment]
Great!
