### ISSUE TITLE
Add Schema.org information for biosimulations web application

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3174]
This lets us get a nice sidepanel on google when someone searches biosimulations
ex. 

https://g.co/kgs/dbL3zx

https://developers.google.com/search/docs/advanced/structured-data/software-app

**Comment by jonrkarr** [comment]
- Dataset: https://developers.google.com/search/docs/advanced/structured-data/dataset
- FAQ/Q&A: https://developers.google.com/search/docs/advanced/structured-data/faqpage
- Logo: https://developers.google.com/search/docs/advanced/structured-data/logo

**Comment by bilalshaikh42** [comment]
Done for apps and logo
Dataset and FAQ are a bit more involved, so we can open a separate issue when the pages are set for those

**Comment by jonrkarr** [comment]
We could start with the simulators.
