### ISSUE TITLE
Resubmit example projects

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3190]
Since ids are now case-insensitive the ids of the submitted projects won't match. 
Need to resubmit the projects after #3186 is merged

**Comment by jonrkarr** [comment]
Sounds like you're making the ids lower case and unique rather than case insensitive.

**Comment by jonrkarr** [comment]
That's fine too.

**Comment by bilalshaikh42** [comment]
Whatever the user inputs, the id is set to lowercase. That way all the id's in the database will be lowercase. however, the id itself can be shared with any casing. Is there an easy way to make it case insensitive while still saving the correct id in the database?

**Comment by bilalshaikh42** [comment]
> Whatever the user inputs, the id is set to lowercase. That way all the id's in the database will be lowercase. however, the id itself can be shared with any casing. Is there an easy way to make it case insensitive while still saving the correct id in the database?

Yes, there is.
https://docs.mongodb.com/manual/core/index-case-insensitive/

We will steed need to resubmit the projects since the index is being recreated, but it should preserve the case

**Comment by jonrkarr** [comment]
To resubmit, delete the projects and then run `tools/publish-examples`.

**Comment by bilalshaikh42** [comment]
Done.
