### ISSUE TITLE
Users reporting that the page to create simulation projects errors after a minute 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3197]
Error logs show that the list of similar algorithms was not downloaded, so the app tried to filter an empty object. 
```
TypeError: Cannot read properties of undefined (reading 'filter')
    at filter (webpack:///apps/dispatch/src/app/components/create-simulation-project/create-simulation-project/create-simulation-project.component.ts:1267:11)
    at function (webpack:///node_modules/rxjs/dist/esm5/internal/Subscriber.js:123:20)
    at _next (webpack:///node_modules/rxjs/dist/esm5/internal/Subscriber.js:63:25)
    at next (webpack:///node_modules/rxjs/dist/esm5/internal/Subscriber.js:34:17)
    at source.subscribe (webpack:///node_modules/rxjs/dist/esm5/internal/operators/withLatestFrom.js:34:27)
    at function (webpack:///node_modules/rxjs/dist/esm5/internal/operators/OperatorSubscriber.js:11:20)
    at next (webpack:///node_modules/rxjs/dist/esm5/internal/Subscriber.js:34:17)
    at onBeforeNext (webpack:///node_modules/rxjs/dist/esm5/internal/operators/mergeInternals.js:25:27)
    at function (webpack:///node_modules/rxjs/dist/esm5/internal/operators/OperatorSubscriber.js:11:20)
    at next (webpack:///node_modules/rxjs/dist/esm5/internal/Subscriber.js:34:17)
```
This can happen if the API call fails, but the API call is working just fine, so I am unable to figure out what is causing this. I cannot reproduce on my end, which makes me think it could be a problem for users that do not have previously cached resources

**Comment by bilalshaikh42** [comment]
@jonrkarr Based on the user reports, I believe this is happening to users outside the US due to network latency from the combine-service for the get similar endpoints call. I can replicate this issue by setting the network settings to 'slow-3g' 

Here is the call: https://combine.api.biosimulations.dev/kisao/get-similar-algorithms?algorithms=KISAO_0000449&algorithms=KISAO_0000657&algorithms=KISAO_0000450&algorithms=KISAO_0000573&algorithms=KISAO_0000659&algorithms=KISAO_0000662&algorithms=KISAO_0000663&algorithms=KISAO_0000030&algorithms=KISAO_0000032&algorithms=KISAO_0000437&algorithms=KISAO_0000526&algorithms=KISAO_0000528&algorithms=KISAO_0000554&algorithms=KISAO_0000088&algorithms=KISAO_0000019&algorithms=KISAO_0000086&algorithms=KISAO_0000029&algorithms=KISAO_0000408&algorithms=KISAO_0000279&algorithms=KISAO_0000321&algorithms=KISAO_0000031&algorithms=KISAO_0000309&algorithms=KISAO_0000280&algorithms=KISAO_0000288&algorithms=KISAO_0000669&algorithms=KISAO_0000524&algorithms=KISAO_0000263&algorithms=KISAO_0000087&algorithms=KISAO_0000436&algorithms=KISAO_0000039&algorithms=KISAO_0000575&algorithms=KISAO_0000535&algorithms=KISAO_0000536&algorithms=KISAO_0000381&algorithms=KISAO_0000301&algorithms=KISAO_0000282&algorithms=KISAO_0000496&algorithms=KISAO_0000283&algorithms=KISAO_0000033&algorithms=KISAO_0000672&algorithms=KISAO_0000367&algorithms=KISAO_0000664&algorithms=KISAO_0000668&algorithms=KISAO_0000057&algorithms=KISAO_0000560&algorithms=KISAO_0000304&algorithms=KISAO_0000027&algorithms=KISAO_0000048&algorithms=KISAO_0000561&algorithms=KISAO_0000562&algorithms=KISAO_0000563&algorithms=KISAO_0000566&algorithms=KISAO_0000527&algorithms=KISAO_0000599&algorithms=KISAO_0000598&algorithms=KISAO_0000600&algorithms=KISAO_0000616&algorithms=KISAO_000061

**Comment by bilalshaikh42** [comment]
Network requests from user: 

![Untitled](https://user-images.githubusercontent.com/32490144/136830288-cd6e89cb-bc1e-4947-99bd-23ae129fa693.png)

**Comment by bilalshaikh42** [comment]
338be997320e053b054137a44546a82a21c13e34 addresses the handling of the error, but not the cause. I don't think the issue is actually the size of the requests itself, but some other requests that have been tied to it. When those request time out, this one ends up being canceled. #3198 shows the location in the code where the requests are being chained together.

**Comment by bilalshaikh42** [comment]
Seems the request before is downloading all the simulators, including all of the logs. This is almost certainly timing out, which causes the request for the kisao terms to get canceled, leading to an undefined array. When the filter method is called on the undefined array the the app crashes. 
Few issues that  cause this. 
1. Chaining of requests that shouldn't be chained
2.  `Using` type overrides, which prevents typescript from catching  that the list is potentially undefined and prompting the user for a fix
3. Directly using http instead of a shared service, causing several requests to be made repeatedly

**Comment by bilalshaikh42** [comment]
The original request that caused the issue seems to be the simulators list, without the includeData parameter not set. #3199 should fix that portion. #3198 should be addressed to clean up some of the issues with chaining the requests. https://github.com/biosimulations/biosimulations/commit/338be997320e053b054137a44546a82a21c13e34 should have fixed the actual crash

@DeepaMahm Thanks for the report! The website at run.biosimulations.dev should now work without the crash. After some testing, we will deploy it to the regular run.biosimulations.org page.

**Comment by jonrkarr** [comment]
@DeepaMahm Thanks for the report! Please be patient with BioSimulations/runBioSimulations. We're aware the early version we've shared has a variety of bugs (see issues) and will fix them.

**Comment by DeepaMahm** [comment]
@jonrkarr No issues at all. I find this work really amazing and I look forward to using BioSimulations.  Please bear with me if I opening new threads and have some feature requests.

@bilalshaikh42 Thanks a lot for the update. I could load my model file in the dev site. I will test a few things and revert back.

**Comment by jonrkarr** [comment]
The Thursday session is a time to discuss specific ideas with us and explore how we could work together.

**Comment by DeepaMahm** [comment]
Sure, I will also explore the options in the tool using my model until then.

**Comment by bilalshaikh42** [comment]
@all-contributors add @DeepaMahm for bug report
