### ISSUE TITLE
Add various acknowledgements

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3206]
Using the @all-contributors  bot add various contributors to the CONTRIBUTORS.md  file

**Comment by bilalshaikh42** [comment]
@all-contributors add @bilalshaikh42,  @jonrkarr, @gmarupilla for code. Add @moraru, @mpw6 for infrastructure

**Comment by bilalshaikh42** [comment]
@all-contributors add @bilalshaikh42 for code, docs, infrastructure

**Comment by bilalshaikh42** [comment]
@all-contributors add @bilalshaikh42 for infrastructure

**Comment by bilalshaikh42** [comment]
@all-contributors add @jonrkarr  for code

**Comment by bilalshaikh42** [comment]
@all-contributors add @gmarupilla for code

**Comment by bilalshaikh42** [comment]
@all-contributors add @moraru for infrastructure

**Comment by bilalshaikh42** [comment]
@all-contributors add @mpw6 for infrastructure

**Comment by bilalshaikh42** [comment]
@all-contributors add @jonrkarr for code, docs

**Comment by bilalshaikh42** [comment]
@all-contributors add @mpw6 for infrastructure
@all-contributors add @moraru for infrastructure
@all-contributors add @gmarupilla  for code

**Comment by bilalshaikh42** [comment]
@all-contributors add @mpw6 for infrastructure

**Comment by bilalshaikh42** [comment]
@all-contributors add @gmarupilla for code

**Comment by bilalshaikh42** [comment]
@all-contributors add @moraru for infrastructure

**Comment by bilalshaikh42** [comment]
@all-contributors add @jonrkarr for design

**Comment by bilalshaikh42** [comment]
@all-contributors add @jonrkarr for code, docs

**Comment by bilalshaikh42** [comment]
@all-contributors add @jonrkarr for design

**Comment by bilalshaikh42** [comment]
@all-contributors add @NIHGOV  for financial

**Comment by bilalshaikh42** [comment]
@all-contributors add @nsf-open for financial

**Comment by bilalshaikh42** [comment]
@all-contributors add @NIBIB for financial

**Comment by bilalshaikh42** [comment]
@all-contributors add @vcellmike for ideas

**Comment by bilalshaikh42** [comment]
@all-contributors add @NIHGOV for funding

**Comment by bilalshaikh42** [comment]
@all-contributors add @NIHGOV for financial

**Comment by bilalshaikh42** [comment]
@all-contributors add @NSF-open for financial

**Comment by bilalshaikh42** [comment]
@all-contributors add @NIBIB for financial

**Comment by bilalshaikh42** [comment]
@all-contributors add @reproducible-biomedical-modeling for financial, fundingFinding, projectManagement

**Comment by bilalshaikh42** [comment]
@all-contributors add @reproducible-biomedical-modeling for financial, fundingFinding, projectManagement

**Comment by bilalshaikh42** [comment]
@all-contributers add @artgoldberg for ideas

**Comment by bilalshaikh42** [comment]
@all-contributors add @artgoldberg for ideas

**Comment by artgoldberg** [comment]
@bilalshaikh42 Thanks Bilal.

**Comment by bilalshaikh42** [comment]
@all-contributors add  @artgoldberg for ideas

**Comment by bilalshaikh42** [comment]
> @bilalshaikh42 Thanks Bilal.

No worries! though you might get a few more notifications as I debug the bot!

**Comment by artgoldberg** [comment]
@bilalshaikh42 That's OK, I'll filter them. How are you?

**Comment by jonrkarr** [comment]
@all-contributors add @jcschaff for ideas
