### ISSUE TITLE
Add status badges/links to app UIs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3210]
- [x] Pull status from new `/health` endpoints
- [x] Bottom of all pages
- [x] Main menus of apps

**Comment by jonrkarr** [comment]
@bilalshaikh42 can we get status badges from Upptime?

**Comment by bilalshaikh42** [comment]
Sure. We can get badges for essentially any url. Though I'm not sure what an uptime badge for the readme or docs would convey. Those are statically hosted by GitHub, so should always be up. 

I think I'm missing some context here

**Comment by jonrkarr** [comment]
Ideally, I think we'd make the static UI apps (simulators, dispatch, platform) clearly display a warning message if the status is down. The upptime app already stores JSON documents with the status of each service. We could modify the upptime GitHub action to merge that information into 1 JSON document and then read that into the UIs. Due to CORS, I think we need to save that to GitHub pages (i.e., subdirectory of the status repo served by GitHub pages). Then I think the apps could read the status from a URL like `https://biosimulations.github.io/status/upptime-summary.json`.

@bilalshaikh42 thoughts?

**Comment by bilalshaikh42** [comment]
Oh, I see what you mean now. I thought you meant creating buttons for the webpages, not including the info in the webpages. 

The website status.biosimulations.org uses the following file to determine the current state. We could do the same

https://raw.githubusercontent.com/biosimulations/status-monitor/master/history/summary.json

**Comment by bilalshaikh42** [comment]
> We could modify the upptime GitHub action to merge that information into 1 JSON document and then read that into the UIs. Due to CORS, I think we need to save that to GitHub pages (i.e., subdirectory of the status repo served by GitHub pages). Then I think the apps could read the status from a URL like `https://biosimulations.github.io/status/upptime-summary.json`.

There is already the summary json linked above. The status front end seems to be able to make a xhr request to it without cors issues, so hopefully should work on the front end as well

**Comment by jonrkarr** [comment]
Addressed by new status notifications at bottom of apps
