### ISSUE TITLE
Add status endpoints to APIs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3213]
I think it would be helpful to add an endpoint to each API that returns trivial status information about each one (i.e., up/down). If something isn't working, users would be able to check if the service is down.

**Comment by bilalshaikh42** [comment]
That is the intention of[ status.biosimulations.org](https://status.biosimulations.org). The issue with an API endpoint is that the API alone does not know about the various components but is just one of the components needed to get have everything working. Also it would not be able to report status if it was itself down. We should definitely make the existence of status.biosimulations.org more well known by including it in the docs/readme/front end apps however

**Comment by jonrkarr** [comment]
I'll close this. My main point is that we should somehow communicate status more quickly so that users know that something is expected to be not working versus due to a bug in our implementation.

**Comment by jonrkarr** [comment]
Will be implemented by health endpoints in #3308
