### ISSUE TITLE
Change success status code of `/auth/open` from 418 to 204

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3238]
Endpoint: http://biosimulators.org/auth/open

418 seems like an odd code to indicate that the API is operational. I think a code like 204 should be used.

**Comment by bilalshaikh42** [comment]
This was added in as a bit of an easter egg. I really didn't intend for
this to be a accessed by  users. During testing the teapot error was a fun
way to make sure I was actually hitting this endpoint

I am planning to add a /health end point to the API that can be used by
users and we can remove this one.

**Comment by jonrkarr** [comment]
I figured that. Replacing this with a health endpoint would be great. 

I think the key thing is to more clearly communicate the status so that we calibrate reviewers expectations by telling them that we know there's a problem (and we're working on it), rather than leaving them to potentially conclude that our tool is too early to use. The status website is great, but users have to know where to find it. I think #3237 will help a lot with this by directly displaying a summary of the status in the app.

**Comment by jonrkarr** [comment]
This endpoint still returns 418, which looks like an error rather than a successful response.
