### ISSUE TITLE
Add /health path to combine service

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3309]
Due to the combine-api container using gunicorn, Kubernetes is unable to determine its health based on the status of the container. 
Adding a simple /status endpoint that returns a 200 should be sufficient to add a health check to Kubernetes and prevent the deployment of bad containers. 

@jonrkarr  I can add this in after #3308 . but feel free to grab it

**Comment by jonrkarr** [comment]
I can take care of this. 

What do you want the route and return type to be?

**Comment by bilalshaikh42** [comment]
"/health" returning an object  ```{status: "ok"} ``` should be sufficient.

The main API will return the following if we want to be consistent:

```json

{
  "status": "ok",
  "info": {
    "Some-dependency": {
      "status": "up"
    }
  },
  "error": {},
  "details": {
    "Some-dependency": {
      "status": "up"
    }
  }
}

```

**Comment by jonrkarr** [comment]
I can make it look the same. What do intend the dependencies to be? The only dependent service is S3.

**Comment by bilalshaikh42** [comment]
Yeah I don't think there are any depdencies, which is why I figured the simpler version was just fine

**Comment by bilalshaikh42** [comment]
Yeah I don't think there are any depdencies, which is why I figured the simpler version was just fine

S3 we probably don't want to include since kubernetes will restart the container repeatedly if s3 is inaccessible.

**Comment by jonrkarr** [comment]
We're presently using S3 to temporarily save created COMBINE archives so we can pass them onto simulation as URLs. It would take some effort to refactor that out.

I can leave S3 out of the response from the `/health` endpoint.
