### ISSUE TITLE
Combine API documentation page returns 500 error

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3310]
https://combine.api.biosimulations.org/ returns a 500; The other endpoints seems to be working just fine 

Seems to be some sort of error with connexion/swagger API package. 
@jonrkarr Do you know if this was working with the latest API schema? if so, its probably a package version issue. 

This causes the health check in #3308 to fail. #3309 would get around this by providing a health URL to ping instead of the root

**Comment by jonrkarr** [comment]
I believe this is because I put the Swagger template in a `vendor` directory that wasn't being copied into the Docker image. Fixed in #3311.
