### ISSUE TITLE
[Bug]: Delete all simulators executes successfully, but raises a 500 error

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3362]
### Location

BioSimulators API

### What happened?

Deleting all simulators executes properly but returns a 500 error

### What made it happen?

Running the delete endpoint 

### Version

Production (Deployed on a .org domain)

### Relevant log output

```shell
{
  "error": [
    {
      "status": "500",
      "title": "Operation Failed",
      "detail": "\"Operation Failed\""
    }
  ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
I believe the issue is due to checking the `acknowledged` property of the result. In my experience, this property doesn't exist. There is a `deletedCount` property.

The `deletedCount` property doesn't clearly indicate whether everything was deleted. Instead, the count could be checked to be zero:
```
const count = await this.model.count();
if (count !== 0) {
  throw new InternalServerErrorException('...');
}
```

**Comment by jonrkarr** [comment]
Same problem exists for simulation runs

**Comment by bilalshaikh42** [comment]
These properties have been updated in the latest mongoose versions.
See https://github.com/Automattic/mongoose/pull/10908/files
