### ISSUE TITLE
Simulations are getting stuck in `CREATION` state

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3363]
Examples:
- https://run.biosimulations.org/simulations/61731375b2be97c51f9f68f3
- https://run.biosimulations.org/simulations/6172575db2be97c51f9f6864
- https://run.biosimulations.org/simulations/6173152a1c15a74c82c580a4
- https://run.biosimulations.dev/simulations/617259338ea6fc21f919544e

**Comment by bilalshaikh42** [comment]
caused by #3365
