### ISSUE TITLE
NX CI build uses wrong base for branches

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3384]
When a branch is behind the main branch (dev), `nrwl/nx-set-shas` appears to choose the wrong base resulting in no tests executing. It sets the base equal to the latest commit in the main branch, which may be ahead of where the branch diverged from the main branch.

**Comment by bilalshaikh42** [comment]
To clarify do you dev? or is it explicitly checking for master

**Comment by jonrkarr** [comment]
It found the latest commit in dev, but didn't run any tests. The latest commit in dev was ahead of where the branch diverged from dev.

**Comment by jonrkarr** [comment]
I think we want to use something like this

NX_HEAD=HEAD

NX_BASE=dev

Or NX_HEAD= one of
```
git merge-base ${{ github.ref }} dev
git merge-base --forkpoint develop
```

**Comment by bilalshaikh42** [comment]
Hmm, this may be resolved already for more recent prs. I previously had not set the config options. Can you confirm this is still happening? 
That should automatically be set by the action though.

**Comment by bilalshaikh42** [comment]
> I think we want to use something like this
> 
> NX_HEAD=HEAD
> 
> NX_BASE=dev
> 
> Or NX_HEAD= one of
> 
> ```
> git merge-base ${{ github.ref }} dev
> git merge-base --forkpoint develop
> ```

Rather than having the ci merge into base, I would want to set the CI requirement that the branch be up to date.

**Comment by jonrkarr** [comment]
This happened last night on a branch I started earlier in the day. 

The CI doesn't currently require the branch to be up to date. 

After I merged dev into the branch, still no affected find no tests to run.

**Comment by jonrkarr** [comment]
The latest PR tested correctly. I'll re-open if I see this again.
