### ISSUE TITLE
Parameterize HSDS base path in HDF5 API client

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3453]
`https://data.biosimulations.dev` is currently hard-coded into the HDF5 API client e.g., `libs/hdf5/api-client/src/lib/api/domain.service.ts`

**Comment by jonrkarr** [comment]
I see configuration is being passed in. I can't tell if this correctly set up.

**Comment by jonrkarr** [comment]
The prod dispatch-API is still using `https://data.biosimulations.dev`. This prevents is from retrieving simulation data.

**Comment by jonrkarr** [comment]
Configuration does not appear to be getting passed to `libs/hdf5/api-client/src/lib/api/domain.service.ts`, the first HDF5 API client service that the results service (`apps/api/src/results/results.service.ts`) invokes.

**Comment by jonrkarr** [comment]
The domain service is constructed before the `Configuration` has been constructed.

**Comment by jonrkarr** [comment]
I think I figured it out

**Comment by bilalshaikh42** [comment]
The intention with this config was the both deployments could just use HTTP://hsds:80 as the kubernetes DNS would point it to the container in the current workspace. 
I am not sure how the basepath could be explicitly set to the dev domain through this setup

**Comment by bilalshaikh42** [comment]
Locally, I can confirm that the provided base path is passed all the way down to the dataset service properly. Do you want to hop on a zoom call to debug this?

**Comment by bilalshaikh42** [comment]
I see the issue, the domain service is the one that is receiving the default domain. This is a dependency injection hierarchy issue. My wrapper module is providing the domain service thought it should not

**Comment by jonrkarr** [comment]
I figured out the dependency hierarchy issue. This should be addressed by #3563. I've left this open until prod is deployed and we can confirm this is is set up correctly.

The issues with the HSDS configuration had been masked by hard coded values in multiple places, which were all aligned with each other until I changed the password and changed the prod configuration to use data.biosimulations.org.

**Comment by jonrkarr** [comment]
The prod dispatch API now uses http://hsds:80, but I'm seeing 403 errors on retrieving simulation data through the prod dispatch API. Not sure if that's because the error occurred before a recent deployment and is cached by redis, or there's still a problem.
