### ISSUE TITLE
`docker.yml` is building COMBINE API unnecessarily frequently and not using a cache

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3511]
Building the COMBINE API Docker image from scratch is slowing down the CI testing. It would be helpful to
- [ ] Only build this image when the COMBINE API has changed (when any of `DockerfilePython`, `Pipfile`, `Pipfile.lock`, or `apps/combine-api` have changed).
  - [ ]  To simplify this, `DockerfilePython`, `Pipfile`, and `Pipfile.lock` could be nested under `apps/combine-api`. If we did add another Python-powered service, we probably wouldn't want to reuse any of this anyway. We'd want minimal Docker images without unnecessary extra software needed by the COMBINE API.
- [ ] Only rebuild new layers

**Comment by bilalshaikh42** [comment]
I added caching to all the docker builds. They should now be significantly faster. The issue with skipping builds is that there is then no way to deploy a given commit or PR. I am hoping that the cache is good enough to allow for a new tag without actually needing to rebuild the image. 
Is there room to speed up the docker image build?

**Comment by bilalshaikh42** [comment]
Looking at a given run, it seems the cache is quite good for the typescript apps. Is there a testing step in the python that can be skipped for builds?
https://nx.app/branch?workspaceId=5f318c65a3653d0005f2de5a&branchName=3509

**Comment by jonrkarr** [comment]
I think this is much faster now. I'll leave this open because it looks like you have a question about testing the COMBINE API.

**Comment by bilalshaikh42** [comment]
Nope, no issue. I was just curious about ways to speed up the build, but if it working well now, that should be good.

**Comment by jonrkarr** [comment]
Image caching should be sufficient.

The COMBINE API tests only need to be run when the API changes -- any of `DockerfilePython`, `Pipfile`, `Pipfile.lock`, or `apps/combine-api`  have changed.
