### ISSUE TITLE
Add retrying for complete processor actions

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3531]
Example  502 errors
- 6188587f6e13c7816f28c3b5: log post
- 618c12abc60ec10bd2621e39: SED-ML post

**Comment by bilalshaikh42** [comment]
I'll take a look at this. All pushes to the API should be going through the client lib, so we can add the rety there

**Comment by jonrkarr** [comment]
I've now seen multiple 502 errors for multiple runs.

**Comment by bilalshaikh42** [comment]
Is this on prod or dev? Getting a 502 is quite strange to me, as that means the entire API is down, or at least nginx thinks it is. Not sure what could be causing that. I did add retrying in #3568 but we shouldn't be getting 502 in the first place.

**Comment by jonrkarr** [comment]
The latest one I saw was prod, I believe the other was dev.
