### ISSUE TITLE
Update NX Lint, Test, Serve, and Build targets for combine-api

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3534]
Currently, we are using nx-python to manage the combine-api. However, the builders provided do not work for our directory setup. See #3355. 
We can remove nx-python and just use the [run commands builder](https://nx.dev/l/r/executors/run-commands-builder) to run the commands needed for the Lint, Test, Build, and Serve targets.

**Comment by jonrkarr** [comment]
Yes, `nx-python` assumes a flat directory structure and this isn't configurable. This is why I set up separate lint and testing in biosimulations/biosimulations#2375.

If you really want to use nx, this would be easy to fix with a fork of nx-python. I submitted a feature request: eulerrapp/nx-python#41.

**Comment by jonrkarr** [comment]
I think its simpler to test with an alternative method than to try to enhance nx-python because the tests are best executed in the Docker image. Also, the tests are best executed with pytest rather than `unittest discover`. The latter is easy to change in a fork, but changing the tests to run in a Docker image is more complicated.

**Comment by bilalshaikh42** [comment]
The reason for creating the issue is that the previous ci script and changes in #2375 are no longer used, since the new CI workflow is dramatically simplified. We can either create a custom workflow for the or just use the above package, which allows for arbitrary commands to be run as a part of the targets

**Comment by bilalshaikh42** [comment]
> I think its simpler to test with an alternative method than to try to enhance nx-python because the tests are best executed in the Docker image. Also, the tests are best executed with pytest rather than `unittest discover`. The latter is easy to change in a fork, but changing the tests to run in a Docker image is more complicated.

Right, this is why I suggested using [run commands builder](https://nx.dev/l/r/executors/run-commands-builder)  which can run arbitrary commands for the test target

**Comment by bilalshaikh42** [comment]
Here is more detailed docs about the options and configuration
https://nx.dev/l/r/workspace/run-commands-executor

**Comment by jonrkarr** [comment]
Had to merge this in because its only configured to run from the dev branch. Can be closed once this is verified to be working corrrectly.
