### ISSUE TITLE
Ontology Service Error 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3551]
Stackdriver Error Reporting error detail

```
TypeError: i.toUpperCase is not a function
at toUpperCase
webpack:///libs/ontology/client/src/lib/ontology.service.ts:140

at this.sanitizer.bypassSecurityTrustHtml(Anser.ansiToHtml
webpack:///apps/dispatch/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.component.ts:95
```

https://console.cloud.google.com/errors/CL3cjuuA5uPawQE?project=biosimulations&src=VESPA&time=P30D

**Comment by jonrkarr** [comment]
This should be prevented by recently added validation for logs. The underlying issues in simulation tools not creating valid logs have been addressed, except VCell which has an open pull request.

I'll also add error handling to the relevant methods to provide better error messages for this.
