### ISSUE TITLE
Review HSDS API client wrapper configuration

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3564]
Previously this line
https://github.com/biosimulations/biosimulations/blob/dev/libs/hsds/client/src/lib/api-client-wrapper.module.ts#L48

was 
```
provide: 'HSDSOPTIONS',
```

`HSDSOPTIONS` felt wrong because `HSDSOPTIONS` isn't defined anywhere. In trying to figure out what wasn't working, I also changed this to the following. 
```
provide: Configuration,
```

@bilalshaikh42 does this need to be `HSDSOPTIONS`?

**Comment by bilalshaikh42** [comment]
No that seems fine. That whole provider isn't actually relevant anyway since the import below it was taking care of it seems. I'll take a look at this at some point to see if it can be cleaned up a bit
