### ISSUE TITLE
Improve interaction between APIs and services to avoid 502 errors in post-processing

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3585]
Currently, 
- the API calls the Simulators API via https://api.biosimulators.org
  - check that simulator exists prior to starting a simulation job)
  - Health
- the API calls the COMBINE API via https://combine.api.biosimulations.org 
  - Health
- the dispatch-service calls the COMBINE API via https://combine.api.biosimulations.org 
  - get COMBINE archive manifest
  - get SED-ML specs
  - get metadata
- the dispatch-service calls API via https://api.biosimulations.org 
  - post results

Perhaps this use of external URLs is responsible for 502 errors in post-processing

Change to URLs internal to the Kubernetes cluster
- [ ] http://simulators-api
- [ ] http://combine-api
- [ ] http://api

@bilalshaikh42 thoughts?

**Comment by bilalshaikh42** [comment]
Yes changing them to the internal URLs would be better.  This was always the intention, but has not been set yet. 

Now that we have an endpoints class, the methods for each endpoint or perhaps the constructor of the class can be set to take in a parameter called "kuberbetes-internal" or "internal" similar to the "external" parameter. This can return the kubernetes versions of the domains.

**Comment by jonrkarr** [comment]
Alternatively, this might be easier to solve by defining aliases within the cluster configuration. This would avoid the code have to know where things are deployed, which varies depending on whether its deployed in the cloud or tested locally. Instead, the deployment would control how traffic is routed.

https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/

**Comment by jonrkarr** [comment]
I examined the code related to these 502 errors. I think this has to be solved at the network level, maybe by using local network URLs or host aliases in the kubernetes configuration.

**Comment by bilalshaikh42** [comment]
Addressed in #3691. The deployment config can have environment variables set for "URLs" and "EXTERNAL_URLS". 
Backend services getting a URL to use for an API call load the external URL, while front end services and backend services getting a URL that is user-facing or passed to another service load the external url
