### ISSUE TITLE
Simulation results still failing with transient 500 errors

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3609]
Examples: 
- #3608
- #3607

**Comment by jonrkarr** [comment]
Perhaps we need to increase the resources to the prod backend deployment.

**Comment by bilalshaikh42** [comment]
I was finally able to trace this

```
10.20.2.58 - - [15/Nov/2021:18:41:00 +0000] "PATCH /runs/6192a13f6ece437141826e4e HTTP/1.1" 200 611 "-" "axios/0.23.0" 1925 0.099 [dev-api-80] [] 10.20.4.68:3333 611 0.097 200 d570d82014cc12be45225158a0d8df45
10.20.4.66 - - [15/Nov/2021:18:41:00 +0000] "GET /runs/6192a13f6ece437141826e4e HTTP/1.1" 200 611 "-" "axios/0.23.0" 1075 0.037 [dev-api-80] [] 10.20.2.56:3333 611 0.037 200 aa595d67ae48141ddd7b2d81e56d4332
10.20.5.56 - - [15/Nov/2021:18:41:01 +0000] "PATCH /runs/6192a1576ece437141826ebc HTTP/1.1" 200 610 "-" "axios/0.23.0" 1927 0.103 [dev-api-80] [] 10.20.4.68:3333 610 0.100 200 31ff76bb23f3ee4f92101133e625ed4a
10.20.2.58 - - [15/Nov/2021:18:41:01 +0000] "PATCH /runs/6192a15b6ece437141826ecf HTTP/1.1" 200 595 "-" "axios/0.23.0" 1927 0.108 [dev-api-80] [] 10.20.4.68:3333 595 0.106 200 aa75ea070e62095cdb31f6ced95c879e
2021/11/15 18:41:02 [warn] 39#39: *985 a client request body is buffered to a temporary file /tmp/client-body/0000000001, client: 10.20.5.56, server: api.biosimulations.dev, request: "POST /logs HTTP/1.1", host: "api.biosimulations.dev"
10.20.5.56 - - [15/Nov/2021:18:41:03 +0000] "PATCH /runs/6192a15d8fe2d70bb9d380a0 HTTP/1.1" 200 630 "-" "axios/0.23.0" 1927 0.101 [dev-api-80] [] 10.20.4.68:3333 630 0.099 200 f5f03bf29cf14b52846964bd93f70732
10.20.2.58 - - [15/Nov/2021:18:41:06 +0000] "PATCH /runs/6192a1748fe2d70bb9d38104 HTTP/1.1" 200 584 "-" "axios/0.23.0" 1927 0.100 [dev-api-80] [] 10.20.4.68:3333 584 0.097 200 1924417573ba68a2a2c007e125f37a43
10.20.5.56 - - [15/Nov/2021:18:41:07 +0000] "PATCH /runs/6192a1776ece437141826f43 HTTP/1.1" 200 607 "-" "axios/0.23.0" 1927 0.105 [dev-api-80] [] 10.20.4.68:3333 607 0.100 200 487d2ac5add93009d7913e4d4c3c5648
2021/11/15 18:41:08 [error] 40#40: *987 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 10.20.2.58, server: api.biosimulations.dev, request: "PATCH /runs/6192a1506ece437141826e98 HTTP/1.1", upstream: "http://10.20.2.56:3333/runs/6192a1506ece437141826e98", host: "api.biosimulations.dev"
10.20.2.58 - - [15/Nov/2021:18:41:08 +0000] "PATCH /runs/6192a1506ece437141826e98 HTTP/1.1" 502 150 "-" "axios/0.23.0" 1927 5.497 [dev-api-80] [] 10.20.2.56:3333 0 5.489 502 6bbc4b6db278250ee8796010a5effe7b
10.20.5.56 - - [15/Nov/2021:18:41:08 +0000] "PATCH /runs/6192a1518fe2d70bb9d3806b HTTP/1.1" 200 575 "-" "axios/0.23.0" 1927 4.841 [dev-api-80] [] 10.20.2.56:3333 575 4.837 200 3c4aa06098310ef3ade4ad457665af02
10.20.5.56 - - [15/Nov/2021:18:41:08 +0000] "PATCH /runs/6192a14c6ece437141826e8a HTTP/1.1" 200 592 "-" "axios/0.23.0" 1927 0.099 [dev-api-80] [] 10.20.4.68:3333 592 0.097 200 2b89cf5335d6ab4cbccbe23ae42be8f9
10.20.2.58 - - [15/Nov/2021:18:41:09 +0000] "PATCH /runs/6192a16e8fe2d70bb9d380e7 HTTP/1.1" 200 585 "-" "axios/0.23.0" 1927 0.780 [dev-api-80] [] 10.20.2.56:3333 585 0.771 200 48dab40354402614caffd6a0c3023824
10.20.5.56 - - [15/Nov/2021:18:41:09 +0000] "POST /logs HTTP/1.1" 201 231618 "-" "axios/0.23.0" 233426 6.814 [dev-api-80] [] 10.20.2.56:3333 231618 6.790 201 9aa91c54458de7ac1f898e88c30556d2
10.20.2.58 - - [15/Nov/2021:18:41:09 +0000] "PATCH /runs/6192a14e6ece437141826e91 HTTP/1.1" 200 597 "-" "axios/0.23.0" 1927 0.580 [dev-api-80] [] 10.20.2.56:3333 597 0.577 200 b782a0318ab2327184a0e64a2f3475b4
10.20.5.56 - - [15/Nov/2021:18:41:12 +0000] "PATCH /runs/6192a1748fe2d70bb9d38104 HTTP/1.1" 200 584 "-" "axios/0.23.0" 1927 0.107 [dev-api-80] [] 10.20.2.56:3333 584 0.103 200 f035dfc0312f774bed0bdc20563354d5
```

**Comment by bilalshaikh42** [comment]
Though this case was for the /runs endpoint not /logs. It could be possible that the logs are too big

**Comment by jonrkarr** [comment]
I thought about that. I was seeing issues with the metadata and SED-ML endpoints. The metadata is fairly small.

**Comment by jonrkarr** [comment]
This still does not appear to be addressed.  See #3745.

**Comment by bilalshaikh42** [comment]
That error is that the results could not be read, but that is handled already with the retires built into the apps correct? I was able to load the simulation and associated plots and the status is marked as succeeded

**Comment by bilalshaikh42** [comment]
For the second one, I am getting a spinner (on mobile) but can see the logs, specifications, results and metadata all just fine from the API

**Comment by bilalshaikh42** [comment]
I am not sure that the examples are actually incorrect at all. In either case, this is a sperate issue since these errors were occuring during processing leading to failure, but these have both succeeded it seems

**Comment by jonrkarr** [comment]
I don't think there's any issues with the logic our of code. 

I think these are similar to the intermittent deployment performance-related failures in submission, resources seem to get overloaded and fail. This is noticeable with batch submissions or tests. Retrying should work if enough time is allocated. However, retrying isn't a great fix because users may still interpret a long delay as an error.

**Comment by bilalshaikh42** [comment]
Oh, I see. I thought this issue was about the  502 errors that would sometimes appear during processing. This issue refers to the results endpoint. Ill check the logs for the cause of this

**Comment by bilalshaikh42** [comment]
This is not possible to trace due to the structure of the validate endpoint. Since the endpoint is directly importing the various services instead of calling the HTTP endpoints, the API is not logging any errors for the results. 

Additionally, the simulationRun module is registering itself as a provider for the services it is importing,  the services are created as singletons unique to the simulationRun module, which will have a different state than the services that are actually providing the results, including entirely separate database connections. 

I am not sure how to address the issue unless the 500 errors are returned from the HTTP endpoints directly

**Comment by jonrkarr** [comment]
The code can be modified to log more diagnostic information. Errors do not need to be handled as implemented with Promise.allSettled at https://github.com/biosimulations/biosimulations/blob/dev/apps/api/src/simulation-run/simulation-run.service.ts#L989. allSettled is convenient, but collects limited error information. More information can be logged by combining Promise.all with catches for each check as done at https://github.com/biosimulations/biosimulations/blob/541e383969c9dd203078923ecb490c3e8846cf32/apps/dispatch-service/src/app/submission/complete.processor.ts#L106.

That said, I expect that the 500 errors have little information. A log for the HSDS might have more helpful information.

**Comment by jonrkarr** [comment]
biosimulations/biosimulations#3752 adds more diagnostic information. Neverthless, I don't think this will reveal much since this is examining the client for the HSDS rather than the HSDS itself. The log for the HSDS itself is likely more informative.

**Comment by jonrkarr** [comment]
Closing. More recent errors are described in #3811.
