### ISSUE TITLE
Requests from machine accounts no longer include user information (no AuthToken)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3628]
Tokens are need to track ownership of projects. This information is no longer included in requests. For machine accounts, the `user` object is now empty.

**Comment by bilalshaikh42** [comment]
I am surprised that they were previously included. Machine apps inherently are not users, so I would expect the user object to be empty. 

The token for the machine apps looks like this to me

```
{
  "iss": "https://crbm.auth0.com/",
  "sub": "5BRH4SlefREz7YRRuUeEo9tNf9HP9k2f@clients",
  "aud": "api.biosimulations.org",
  "iat": 1637085609,
  "exp": 1637172009,
  "azp": "5BRH4SlefREz7YRRuUeEo9tNf9HP9k2f",
  "scope": "read:Projects update:Projects create:Projects",
  "gty": "client-credentials",
  "permissions": [
    "read:Projects",
    "update:Projects",
    "create:Projects"
  ]
}
```

A user identity token would look similar but potentially contain additional metadata.  The "sub" claim provides the unique identity of the user and/or machine client. 

Are you specifically talking about the  `User` decorator in auth library?  If this was working previously, then it was not intentional. However, it can be adapted to provide a User or Client depending on what makes the call.

**Comment by jonrkarr** [comment]
I'm referring to the `@Req` decorator and the `user` attribute of `Request`. This previously had tokens for both users and machine accounts. Now it only has tokens for users.

import { Req } from '@nestjs/common';
import { Request } from 'express';

**Comment by bilalshaikh42** [comment]
Can you point me to the code where this is happening?

**Comment by jonrkarr** [comment]
This is marked in the comment in https://github.com/biosimulations/biosimulations/pull/3629

https://github.com/biosimulations/biosimulations/blob/d3258aaca6342f324e4e68aca59f9dcabc286bf5/apps/api/src/simulation-run/simulation-run.controller.ts#L232-L237

This is how I'm submitting requests for simulation runs with requests to publish the run upon its successful completion:
```python
import json
import requests
import subprocess

client_id = '...'
client_secret = '...'

response2 = requests.post('https://crbm.auth0.com/oauth/token', json={
    'client_id': client_id,
    'client_secret': client_secret,
    'audience': 'api.biosimulations.org',
    "grant_type": "client_credentials",
})
response2.raise_for_status()
response_data = response2.json()
auth = response_data['token_type'] + ' ' + response_data['access_token']

run = {
    'name': 'Kockout of gene A',
    'simulator': 'tellurium',
    'simulatorVersion': '2.2.1',
    'cpus': 1,
    'memory': 8,
    'maxTime': 20,
    'envVars': [],
    'purpose': 'other',
    'email': 'info@biosimulations.org',
    'url': 'https://github.com/biosimulators/Biosimulators_test_suite/raw/dev/examples/sbml-core/Ciliberto-J-Cell-Biol-2003-morphogenesis-checkpoint-continuous.omex',
    'projectId': 'test',
}

response = requests.post('http://localhost:3333/runs', json=run, headers={'Authentication': auth})
response.raise_for_status()
```

**Comment by bilalshaikh42** [comment]
The name of the HTTP header in the request is incorrect. It should be "authorization" not "authentication"

The URL to get the token is `auth.biosimulations.org/oauth/token`. While the endpoint you used is an alias, this affects the 'iss' claim on the token, which can cause auth to fail sometimes.

**Comment by jonrkarr** [comment]
I had both before; that didn't work either.

**Comment by bilalshaikh42** [comment]
I am able to use an m2m token (biomodels) to connect to the run endpoint and log the correctly received token . 

There may be some issues with your config file.  The issuer, audience and domain must match to token

**Comment by jonrkarr** [comment]
Yeah, I figured that out. I hadn't changed it to `api.biosimulations.org`.

**Comment by jonrkarr** [comment]
The `user` attribute is fine.
