### ISSUE TITLE
Argo application is down

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3646]

**Comment by bilalshaikh42** [comment]
The application is up, though the ssl cert is not valid. To access it, HSTS needs to be disabled on chrome. 

https://sectigostore.com/blog/how-to-disable-hsts-in-chrome-firefox/

**Comment by jonrkarr** [comment]
In addition to the invalid certificate I saw 503 errors.
