### ISSUE TITLE
HSDS are down

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3648]
I think these have been down for a couple of days. This is not due to changes to handling configuration by the Angular and Nest apps. The services are unresponsive even to h5pyd.

```
hsls --endpoint https://data.biosimulations.dev --username ... --password ...
hsls --endpoint https://data.biosimulations.org --username ... --password ...
```

**Comment by bilalshaikh42** [comment]
I have been working on debugging this

**Comment by bilalshaikh42** [comment]
Follow here: https://github.com/HDFGroup/hsds/issues/107

**Comment by jonrkarr** [comment]
Did we upgrade to a new version of HSDS? Perhaps we need to be more conservative about upgrading the HSDS and not deploy to `org` before checking `dev`.
