### ISSUE TITLE
Status and health should include the data service

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3649]
The status and health are currently misleading because the data service is down, but the status and health says everything is ok. 

For these to be effective, they need to include all relevant status. With all relevant status included, this has the ability to communicate to users that the developers are aware there's a problem, they know what it is, and are working to quickly fix. 

Not including all relevant status can have the unintended consequence of leading users to think that the developers aren't aware of any problems and thus likely aren't working to fix them.

**Comment by bilalshaikh42** [comment]
Yes, the current situation for the hsds was not accounted for in the status check or the status website. Both should be added

**Comment by bilalshaikh42** [comment]
As a clarification- The health endpoint should not be changed, as the API is healthy without the dataservice functioning. 
The status however does need to be updated
