### ISSUE TITLE
🐛: Search and Filter options not visible when browse page is scrolled down

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3658]
### Location

BioSimulations

### What happened?

Options are not visible when selecting search and filter after scrolling down page. User needs to scroll back up to see the menu appear. 

### What made it happen?

1. Scrolled down the browse page
2. Clicked on "Search and Filter" button
3. Did not see options
4. Scrolled to top
5. Saw options

### Version

Development (Deployed on a .dev domain)

### What browsers are you seeing the problem on?

Firefox, Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
Added scroll to top on the opening of that panel
