### ISSUE TITLE
Remove outdated package npn-slider

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3706]
The [npn-slider](https://www.npmjs.com/package/npn-slider) package used in some of the components has not been updated in 3 years and is causing issues with the latest versions of angular.  See #3668.

The mat-slider component should be used instead to ensure compatibility.

**Comment by bilalshaikh42** [comment]
The issue with this, and the reason we are using npn-slider in the first place, is that mat slider does not allow for setting a range easily. The component is currently only used in one location, so perhaps we can make a custom component to handle this use case

**Comment by jonrkarr** [comment]
Unfortunately, material provides a somewhat limited component library, which necessitates the use of third-party components.

This might be an import issue. Here's a blog post that discusses something similar.
https://careydevelopment.us/blog/angular-how-to-deal-with-that-cursed-does-not-have-emod-error

Another possibility is this package. However, it isn't frequently maintained either.
https://www.npmjs.com/package/@angular-slider/ngx-slider

**Comment by bilalshaikh42** [comment]
The import issue is showing up because the package uses and older build engine for the module I believe. The newer angular build system does not seem to support importing those modules, leading to the error.  The ngx-slider package was updated more recently, so it might not have this issue.

**Comment by jonrkarr** [comment]
I'm only vaguely familiar with the evolution of Angular's build engine. The module looks very similar to recent versions of angular. Might be easy to fork or copy.

**Comment by bilalshaikh42** [comment]
Likewise.  I have noticed references in the change notes about the build system moving from "View Engine" to "Ivy" and that this has an impact on libraries that use the older one, but not an actual understanding of what that means regarding changes that are needed. It might be that all that is needed is a small update to some metadata, in which case we could fork it

**Comment by jonrkarr** [comment]
I think it might just be a couple bits of metadata. See "How to set the format for a library?" in https://christiankohler.net/angular-view-engine-was-removed-what-you-need-to-know

**Comment by jonrkarr** [comment]
I think it might be sufficient to update the compilation options
https://github.com/npnm/NpnSlider/blob/master/projects/npn-slider/tsconfig.lib.json

**Comment by jonrkarr** [comment]
I think the other package might have the same problem.
https://github.com/angular-slider/ngx-slider/issues/296

It looks like forks of ngx-slider have already addressed the problem
https://github.com/rp3e11/ngx-slider/commits/master

**Comment by bilalshaikh42** [comment]
I simply included the package code as a custom component in the UI library in #3668. We can customize it as needed just as any other UI component

**Comment by jonrkarr** [comment]
Thanks
