### ISSUE TITLE
🐛:  OpenCor image not accepting file inputs with spaces

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3747]
### Location

runBiosimulations, BioSimulations API

### What happened?

The image is unable to load the OMEX archive correctly.
See: https://run.biosimulations.dev/simulations/61ad293f9bd352e8df2f2d13#tab=log

Removing spaces removes the error.
See: https://run.biosimulations.dev/simulations/61ad2bca35f38e7426a0c544#tab=log

No such limitation exists for other simulators, for example tellurium
See: https://run.biosimulations.dev/simulations/61ad2c7935f38e7426a0c55e

### What made it happen?

Provided an input omex archive with spaces in the name and chose opencor as the simulator

### Version

Production (Deployed on a .org domain)

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
============================================= Executing COMBINE archive =============================================
INFO:    Using cached SIF image
Traceback (most recent call last):
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 247, in 
    if not update_paths(args.path, args.scripts_dir, args.clear_args, args.extra_args):
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 213, in update_paths
    update_scripts(scripts_dir, new_path, clear_args, extra_args)
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 125, in update_scripts
    update_script(os.path.join(bin_dir, fn), new_path, clear_args, extra_args)
  File "/home/opencor/OpenCOR/bin/../python/bin/set_python_path.py", line 118, in update_script
    with open(script_filename, 'w') as f:
OSError: [Errno 30] Read-only file system: '/home/opencor/OpenCOR/bin/../python/bin/biosimulators-opencor'
usage: opencor [-h] [-d] [-q] -i ARCHIVE [-o OUT_DIR] [-v]
opencor: error: unrecognized arguments: simulation for Di Francesco and Noble (1985).omex
srun: error: xanadu-55: task 0: Exited with exit code 2
srun: Terminating job step 3726832.2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
I think I already corrected the escaping in the template slurm script. This might be related to how the Docker entrypoint is configured for OpenCOR's bespoke Python environment. 

Also, the simulation service does not need to use the original file names. The simulation service could use sanitized names or a standardized name such as 'project.omex'.

**Comment by bilalshaikh42** [comment]
While changing the file name would correct the issue on the backend, users may still provide a omex archive with spaces as input to the simulation tools directly. Since this case works for the other simulators, and is only an issue with opencor its probably best to address the image for opencor

**Comment by bilalshaikh42** [comment]
> I think I already corrected the escaping in the template slurm script. This might be related to how the Docker entrypoint is configured for OpenCOR's bespoke Python environment.

This is not an issue with the slurm script as other simulators (such as tellurium) are able to handle the spaces just fine

**Comment by jonrkarr** [comment]
Agreed. I didn't change the names of OMEX files in the simulation service because it isn't necessary. I did the minimum needed to enable names with spaces by escaping inputs.

The issue is due to the pythonshell script that OpenCOR provides. This script doesn't properly escape inputs. I'll work around this and file an issue to OpenCOR.

The other simulation tools don't have this problem because Python can be executed in the usual way. OpenCOR is unique in that Python has to be called **through** OpenCOR. This is the only recognized way to access the `opencor` Python module. I think module is dynamically created by the OpenCOR executable. I haven't looked into how they're doing this to understand further. I've never seen anything else with this design.

**Comment by jonrkarr** [comment]
Worked around with BioSimulators-OpenCOR 0.0.9. Reported underlying issue as opencor/opencor#2602.
