### ISSUE TITLE
🐛: NetPyNe example run times out

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3751]
### Location

runBiosimulations

### What happened?

NetPyNe example run times out repeatedly when submitting examples runs 

See: https://run.biosimulations.dev/simulations/61ad84c5da658557956a4d8b#tab=log

@jonrkarr Is this run expected to take longer than 20 mins? 

### What made it happen?

Ran example submission script

### Version

Development (Deployed on a .dev domain)

### Relevant log output

```shell
============================================ Downloading COMBINE archive ============================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   111  100   111    0     0    339      0 --:--:-- --:--:-- --:--:--   340

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 1308k  100 1308k    0     0  2853k      0 --:--:-- --:--:-- --:--:-- 19.0M

============================================= Extracting COMBINE archive ============================================
Archive:  input.omex
 extracting: contents/metadata.rdf   
 extracting: contents/simulation.sedml  
 extracting: contents/model.xml      
 extracting: contents/expected-results.json  
 extracting: contents/LeakConductance.channel.nml  
 extracting: contents/NaConductance.channel.nml  
 extracting: contents/manifest.xml   
 extracting: contents/reports.h5     
 extracting: contents/KConductance.channel.nml  
 extracting: contents/NML2_SingleCompHHCell.nml  

============================================= Executing COMBINE archive =============================================
INFO:    Using cached SIF image
slurmstepd: error: *** JOB 3727902 ON xanadu-55 CANCELLED AT 2021-12-05T22:54:40 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 3727902.2 ON xanadu-55 CANCELLED AT 2021-12-05T22:54:40 DUE TO TIME LIMIT ***
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
No. I recently corrected something. This might not be meshing well with UConn's HPC, even though its fine in GitHub actions. This probably has to be debugged by SSHing into the cluster.

**Comment by bilalshaikh42** [comment]
The above logs are all that are output on the cluster as well. I can try to run it in verbose mode and see if that gives any more information

**Comment by jonrkarr** [comment]
This likely relates to the use of MPI. I'd guess its either hanging at the very beginning or maybe at the very end. I think this may be hard to work out without interactively running this on an HPC node.

**Comment by jonrkarr** [comment]
The change is because I found a mistake which previously prevented NetPyNe from actually being used. I forgot to pass along an optional argument. As a result, the pyNeuroML, NEURON, and NetPyNe images were actually all using pyNeuroML. This logic is now corrected. I'm not terribly surprised that there's an issue with the environment set up with NetPyNe + UConn HPC.
