### ISSUE TITLE
Ci passes even if one step fails

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3758]
@jonrkarr could you take a look at the following line? I can't seem to get the bash exit code correct. I am trying to run all three steps in parallel and fail if any of them fail. 

https://github.com/biosimulations/biosimulations/blob/d75afbd1f4a69ea830813dd3c9978e3d2d63be41/.github/workflows/buildLintTest.yml#L89

**Comment by jonrkarr** [comment]
The individual exit codes have to be collected separately. This post shows a similar solution: https://stackoverflow.com/a/46212640.

```yaml
- run: |
    # launch processes concurrently and collect ids of processes
    npx nx affected --target=lint --parallel &
    P1=$!
    
    npx nx affected --target=build --prod --parallel &
    P2=$!
    
    npx nx affected --target=test --parallel &
    P3=$!
    
    # wait for processes to finish and collect exit codes
    wait $P1
    S1=$?
    
    wait $P2
    S2=$?
    
    wait $P3
    S3=$?
    
    # find highest exit code
    S_ARR=($S1 $S2 $S3)
    S=${S_ARR[0]}
    for n in "${S_ARR[@]}" ; do
        ((n > S)) && S=$n
    done
    
    # return highest exit code
    exit $S
```

**Comment by bilalshaikh42** [comment]
thanks!
