### ISSUE TITLE
🐛: Missing Kisao definition from api causes files and metadata to fail to display

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3771]
### Location

runBiosimulations

### What happened?

Submitted a simulation run. Loading the files and metadata tabs shows errors

### What made it happen?

The http logs show that the API responded with the files, metadata and specifications as expected. However, the call to https://api.biosimulations.dev/ontologies//KISAO/KISAO_0000019 failed with a 404. This is due to the extra "/" in the url.

The call to https://api.biosimulations.dev/runs/61b26393155eb3c5c3340493/summary fails due to missing simulators from the database

### Version

Development (Deployed on a .dev domain)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
The URL issue comes from a bug introduced in the restructuring of endpoints.

The missing simulators shouldn't happen in the org deployment. This can happen if dev resources are created with org simulators.

**Comment by bilalshaikh42** [comment]
Whoops, sorry didn't mean to assign you.  Has the dev simulators database been modified? Not sure why tellurium would stop working

**Comment by jonrkarr** [comment]
I copied the simulators over from org to dev yesterday. In general, they will diverge until we re-sync them. One way they diverge is different versions. They can also diverge if we migrate the schema and content, but don't update each entry in the dev database.
