### ISSUE TITLE
Error logging has been broken by changes to Axios error types

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3785]
Previously, error statuses were contained in `error.status` and `error.message`

Due to dependency upgrades, these now must be obtained from `error.response.status` and `error.response.data.detail`.

**Comment by bilalshaikh42** [comment]
This might be useful https://github.com/axios/axios/issues/3612

**Comment by jonrkarr** [comment]
Thanks.
