### ISSUE TITLE
dispatch-service unncessarily downloads archives using external URLs

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3787]
This was causing me problems stemming from #3786

**Comment by bilalshaikh42** [comment]
Could you point to where this is?

**Comment by jonrkarr** [comment]
https://github.com/biosimulations/biosimulations/blob/b4e7790155492fc9389bc7076062fb3ad2d474fa/apps/dispatch-service/src/file/file.service.ts#L36
https://github.com/biosimulations/biosimulations/blob/1156bdbad307bb15672bf9f10e13f176f4eb201b/apps/dispatch-service/src/sedml/sedml.service.ts#L32
https://github.com/biosimulations/biosimulations/blob/1156bdbad307bb15672bf9f10e13f176f4eb201b/apps/dispatch-service/src/metadata/metadata.service.ts#L36

Fixed in #3761
