### ISSUE TITLE
chore(deps): update dependency mongoose to v6.1.1

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3795]

**Comment by bilalshaikh42** [comment]
Simulators-API has incorrect typing when returning a simulator that need to be corrected. See the tests for #3760

**Comment by jonrkarr** [comment]
mongoose has already been updated to 6.1.2. Tests for `simulators` and `simulators-api` apps both pass.
