### ISSUE TITLE
Update documentation links and remove old-style documentation

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3796]
- [x] Sort concepts menu
- [x] lowercase names of concepts pages
- [x] Fix https://docs.biosimulations.org/users/user-tutorial/ link in platform app
- [x] Fix broken links in docs markdown files
- [x] Fix formatting of typewriter text
- [x] Clarify conventions overview
- [x] Clarify names of conventions files/routes
- [x] Group conventions under concepts or their own top-level category
- [x] Merge FAQsmodules in https://docs.biosimulations.org/
- [x] Merge tutorials modules in https://docs.biosimulations.org/
- [x] Merge about modules in https://docs.biosimulations.org/
- [x] Merge simulators and dispatch privacy policy into https://docs.biosimulations.org/
- [x] Merge simulators and dispatch terms of service into https://docs.biosimulations.org/
- [x] Change help links to https://docs.biosimulations.org/
  - [x] platform app
  - [x] dispatch app
  - [x] simulators app
  - [x] biosimulators repos
  - [x] ApiCurio
- [x] Change conventions links to https://docs.biosimulations.org
  - [x] platform app
  - [x] dispatch app
  - [x] simulators app
  - [x] biosimulators repos
- [x] Remove conventions module from simulators app
- [x] Remove help modules
  - [x] dispatch app
  - [x] simulators app
- [x] Remove shared privacy policy, terms of service components
- [x] Merge content from docs.biosimulators.org into docs.biosimulations.org
- [x] Change docs to reflect BioSimulations and BioSimulators
  - [x] HTML head title
  - [x] Landing page title
  - [x] About section
- [x] Add section on citing  BioSimulations/BioSimulators
- [x] Clean up licenses for dependencies
- [x] Improve section formatting of the changelog
- [x] Fix code formatting
- [x] Release biosimulators repos

**Comment by bilalshaikh42** [comment]
It would be useful to group the conventions underneath concepts before switching the URLs over. 
We had discussed adding information about each modeling languages interface to sed-ml under concepts as well

**Comment by jonrkarr** [comment]
Added to the todo list above
