### ISSUE TITLE
Update `version` in `package.json` in continuous deployment action (`cd.yml`)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3866]

**Comment by bilalshaikh42** [comment]
Oddly, this used to happen just fine. There is a plugin for semantic release that should handle this. I'll take a look

**Comment by jonrkarr** [comment]
In that case, it sounds like a configuration variable might need to be updated

**Comment by bilalshaikh42** [comment]
This was due to a change I made to include the changelog in the git commit. Seems each file included must be specified
https://semantic-release.gitbook.io/semantic-release/support/faq

**Comment by bilalshaikh42** [comment]
Fixed
