### ISSUE TITLE
Changelog in documentation is always 1 release behind

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3893]
https://docs.biosimulations.org/news/changelog/ is always 1 release behind. The release workflow needs to update the documentation after the changelog is compiled.

**Comment by bilalshaikh42** [comment]
I added a "release" trigger to the docs workflow that should hopefully run after the release is done. The [skip ci] that is included with the commit message may prevent this, so lets confirm next release before closing

**Comment by bilalshaikh42** [comment]
Fixed by adding the release trigger for docs
