### ISSUE TITLE
Investigate 502 errors between dispatch service and api

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3897]
After increasing the node size, we still saw many 502 errors between the dispatch service and Api. I believe they were all resolved with retrying. 

Potential things to consider
- use fewer replicas of api, each with more memory

**Comment by bilalshaikh42** [comment]
After running test as described in #4076 and looking at the request handling performance (https://monitoring.biosimulations.org/d/nginx/nginx-ingress-controller?orgId=1&refresh=5s&viewPanel=21) I am seeing 99.1% percent success rate so I believe this can be closed. 
@jonrkarr how were you keeping track of 502 errors? I scanned over the logs as the simulations were running looking for any red (errors logged using the logger) but didn't see any. I don't know if our retry logic consistently prints these errors however

**Comment by jonrkarr** [comment]
I downloaded the log from the Argo app and text searched for 500, 502, 503, etc.

**Comment by jonrkarr** [comment]
I don't see any 502, 503 in either the API or dispatch-service logs. The 500 errors in the API log are due to #4077.
