### ISSUE TITLE
Dispatch Service Fails to Start

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3977]
The latest deployment for the dispatch service have failed due to some missing dependencies. 

@jonrkarr do you know if any recent changes would require a c package called "sharp"?

**Comment by bilalshaikh42** [comment]
This is due to the image resizing library

**Comment by jonrkarr** [comment]
Probably just need to add `apk add vips-dev` to the Dockerfile at

https://github.com/biosimulations/biosimulations/blob/9694df907445bb9c3474824fc62c4777f4170f66/Dockerfile#L32

[sharp](https://www.npmjs.com/package/sharp) is a node package needed for resizing images.

It requires `libvips`. Installation requires
- C++11 compiler
- node-gyp

**Comment by jonrkarr** [comment]
#3979 isn't enough for sharp to work. This still has to be worked out.

**Comment by bilalshaikh42** [comment]
Yup, sorry didn't mean to close. Im just trying to get all the docker/dependency changes consolidated before debugging further

**Comment by jonrkarr** [comment]
I think sharp is the only relevant change.

**Comment by bilalshaikh42** [comment]
This seems to be caused by the --ignore-scripts command on the npm install. Removing this is a bit of an issue since we will run into issues with angular components not being available in the post-install compilation steps.

**Comment by bilalshaikh42** [comment]
Oddly, I am able to get the docker image built and running locally, but building it via CI is some how not working

**Comment by bilalshaikh42** [comment]
Should be resolved for real this time

**Comment by jonrkarr** [comment]
Looks good. `.org` is generating thumbnails. Thanks for fixing this.
