### ISSUE TITLE
Front end apps should not have dependencies on s3 URLS

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#3981]
The changes in #3975 overrode linting rules designed to prevent front-end apps from depending on storage bucket information. All interaction with the storage should be handled through the API as the API can work with a range of backend configurations in a way that is transparent to the front end apps.  This will cause breaking changes if we ever need to include a second bucket as suggested in #3896 or have alternate file storage mechanisms (like using NFS as we were previously) 

The API should expose a /thumbnails route for the images that takes in a query parameter to determine the appropriate size of the thumbnail. It can then return a redirect to the correct URL

**Comment by jonrkarr** [comment]
The thumbnails are generated as part of the post-processing and saved to the S3 bucket. This avoids the need to use our API to access images, generate them dynamically, or cache them dynamically.

The front end apps only need information about where to find thumbnails. They don't require detailed information about how this is stored.

**Comment by jonrkarr** [comment]
I think we have more important things to focus on than engineering for using multiple buckets or multiple storage mechanisms.

**Comment by bilalshaikh42** [comment]
> The front-end apps only need information about where to find thumbnails.

The locations of the thumbnails are provided as URLs under the files or files-dev domains, which are inherently tied to the UConn storage bucket. 

A URL such as api.biosimulations.org/SIMID/thumbnails?size=small would be a better source of the thumbnails.

 All that the API would be doing is sending back a 301  to the URL that is currently being retrieved via the shared config. This will allow any future changes to the actual location of the thumbnail to be irrelevant to any of the front-end apps. I feel very strongly that the front-end apps should not be accessing the storage bucket config at all.

**Comment by bilalshaikh42** [comment]
> I think we have more important things to focus on than engineering for using multiple buckets or multiple storage mechanisms.

I agree with this. I am not advocating for making this change now. But simply to avoid an architecture that will prevent any changes in the location of the files later without breaking all existing simulations/projects. The change to prevent this is quite minor.
