### ISSUE TITLE
Change deletion of temporary COMBINE archives to use an S3 life cycle rule

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#3994]
- [ ] Wait for UConn to upgrade their S3 bucket to a version that supports life cycle rules
- [ ] Disable cron schedule in `.github/workflows/delete-temporary-combine-archives.yml`
- [ ] Install life cycle rule with `tools/s3-config/retention.py`
- [ ] Check that rule is working

Labeled as future because we're waiting on support from UConn.

**Comment by bilalshaikh42** [comment]
Re #2432

**Comment by bilalshaikh42** [comment]
We could also add a simply cron job to the dispatch service since it is already deployed to behind the firewall. This would avoid the need for a complex github action

**Comment by jonrkarr** [comment]
If the S3 upgrade is coming up, lets plan on.
