### ISSUE TITLE
Remove retrying on network calls

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4032]
```
(node:1851305) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [FormData]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1851305) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [FormData]. Use emitter.setMaxListeners() to increase limit
(node:1851305) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [FormData]. Use emitter.setMaxListeners() to increase limit
```

**Comment by bilalshaikh42** [comment]
This might be related to #4031 as it only shows up when the dispatch-service is having this issue. Some event listeners for the retries/the HTTP requests must not be closing correctly, leading to both these issues.

**Comment by bilalshaikh42** [comment]
This is almost certainly a by-product of retrying. There must be created observables that are not being properly removed

**Comment by jonrkarr** [comment]
If the combine api isn't running, that would lead to a lot of retrying.

**Comment by jonrkarr** [comment]
I'll try to address the combine api tonight. The new issue feels like a problem with a dependency.

**Comment by jonrkarr** [comment]
@bilalshaikh42 can this issue be closed? This seems like its probably no longer relevant as a result of your refactoring?
