### ISSUE TITLE
🐛:  Combine API repeatedly crashes 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4037]
### Location

Other (please describe below)

### What happened?

https://deployment.biosimulations.org/applications/biosimulations-dev?node=apps%2FDeployment%2Fdev%2Fcombine-api%2F0

The deployment for the combine API is repeatedly crashing. this can be replicated locally by running the docker image

### What made it happen?

Run the docker image for the combine archive locally with 
```
ocker run -it -p 3335:3333 ghcr.io/biosimulations/combine-api:sha-48c85d4
```
Set the following env variables and the run the API and Dispatch-Service locally

```
EXTERNAL_COMBINE_API_URL=http://localhost:3335/
COMBINE_API_URL=http://localhost:3335/
```
### Version

Production (Deployed on a .org domain), Development (Deployed on a .dev domain)

### Relevant log output

```shell
mbine-api:sha-48c85d4
[2022-01-11 21:45:59 +0000] [30] [INFO] Starting gunicorn 20.1.0
[2022-01-11 21:45:59 +0000] [30] [INFO] Listening at: http://0.0.0.0:3333 (30)
[2022-01-11 21:45:59 +0000] [30] [INFO] Using worker: sync
[2022-01-11 21:45:59 +0000] [31] [INFO] Booting worker with pid: 31
[2022-01-11 21:47:10 +0000] [30] [CRITICAL] WORKER TIMEOUT (pid:31)
[2022-01-11 21:47:10 +0000] [31] [INFO] Worker exiting (pid: 31)
[2022-01-11 21:47:10 +0000] [47] [INFO] Booting worker with pid: 47
[2022-01-11 21:47:45 +0000] [30] [CRITICAL] WORKER TIMEOUT (pid:47)
[2022-01-11 21:47:45 +0000] [47] [INFO] Worker exiting (pid: 47)
[2022-01-11 21:47:46 +0000] [63] [INFO] Booting worker with pid: 63
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
Did you try undoing the upgrades to the dependencies?

500 level errors to the combine api would lead to a lot of retrying.

**Comment by bilalshaikh42** [comment]
I have not tried that yet. I am able to get the combine API running locally using python only (no gunicorn wrapper) and the current version does not show any issues. However, when I run it with gunicorn, I see the issues. We probably need to tweak the run command in the docker image. Here is a possible starting point. We can tweak the timeout parameter higher if we still see the worker timeout issues. 

```
CMD gunicorn --worker-class gevent --workers 8 --bind 0.0.0.0:5000 wsgi:app --max-requests 10000 --timeout 5 --keep-alive 5 --log-level info
```

**Comment by jonrkarr** [comment]
I approved the pr.

I think the crashing is related to a new version of a swagger dependency, or maybe connexion/flask. Hopefully i can narrow it down today.

**Comment by jonrkarr** [comment]
I think this might be caused by `rdflib` `6.1.1` which was released recently. I need to try more to convince myself that downgrading fixes the problem.

**Comment by jonrkarr** [comment]
I can replicate the worker timeout behavior with the Docker images all the way back to the first version of the image saved to GHCR.

**Comment by bilalshaikh42** [comment]
Odd. I wonder what the cause of the sudden uptick in crashes was. It seems to be resolved with the current deployment. I can still see the logs indicate that the workers have been killed, but the deployment as a whole stays responsive

**Comment by jonrkarr** [comment]
> cause of the sudden uptick in crashes

Not sure about that.

I should add that I only tested back two months. There's no saved images beyond that. Beyond that point might be when we called it combine-service.

Interestingly, I don't see the problem with flask's own test server.

I'm going to try to explore further.

**Comment by bilalshaikh42** [comment]
I take it back. The sedml endpoint continues to cause timeouts. The processing of simulation proceeds fine for each step except that one currently.

**Comment by jonrkarr** [comment]
Others seem to describe similar issues at https://github.com/benoitc/gunicorn/issues/1801.

There's some tips for using gunicorn with Docker at https://pythonspeed.com/articles/gunicorn-in-docker/.

I think this is solved by setting workers=2, threads=4.

**Comment by jonrkarr** [comment]
This seems to go away if Gunicorn is configured with any of the following:
- Set `worker-class` to `gevent`
- Set `workers` > 1
- Set `threads` > 1

#4072 sets the above and also sets the `server` argument of the FlaskApp to `gevent`. This configuration seems to work well locally. 

Next step: try the configuration in the dev deployment.

**Comment by bilalshaikh42** [comment]
Reopening until testing

**Comment by jonrkarr** [comment]
I think this issue has been addressed. The new dev deployment seems fine to me. I don't see any worker failure messages in the log in Argo. The API seems to work as intended.

I'm leaving this open until we can check the Argo log after a larger test (e.g., ~100 simulation runs).

**Comment by bilalshaikh42** [comment]
No crashes when testing about 150 simulation runs. One caveat, the processing seems to be moving quite slowly due to concurrency being limited on dispatch service. If we increase the concurrency, it might reveal new issues, but for now seems good.

**Comment by jonrkarr** [comment]
Great!
