### ISSUE TITLE
Set up networking for Storage Buckets

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4044]
## Buckets:
These can be accessed via the storage API or via custom URL depending on how we configure the loadbalancer/urls below
- [x]  Dev Files Bucket
- [x] Prod Files Bucket 
- [x] Temp Dev Bucket
- [x] Temp Prod Bucket
- [x] HSDS Bucket
- [x] HSDS Dev Bucket (optional) 

## CORS:
Need to enable cors access for the buckets
- [x] Dev files
- [x] Prod files
- [x] Temp dev bucket
- [x] Temp prod bucket

#Enable public access 
- [x] Dev files bucket
- [x] Prod files bucket
- [x] Temp dev bucket
- [x] Temp prod bucket

## URLS: 
- [x] files.biosimulations.dev
- [x] files.biosimulations.org
- [ ] a URL for the HSDS  backing bucket?
These need to be pointed to the loadbalancer IP 

## Loadblanacer: 
- [ ] Files load balancer (use host to send traffic to either dev/prod) 
- [ ] HSDS load balancer (not sure if this is needed)  

The files loadbalancer should be attached to the google CDN. Set the mode to cache all files since we are keeping all the files immutable 
 
currently have 1 loadbalancer for  Dev bucket. This should be edited to account for both. I don't think that hsds need a URL, so it won't need a  bucket. We can just use the standard s3 API config we already have

**Comment by jonrkarr** [comment]
For the temporary files buckets, I configured the COMBINE API to use `https://storage.googleapis.com`. I think this fine. I think its fine for the bucket behind HSDS as well, which isn't exposed at all.
