### ISSUE TITLE
🐛: Redirect in URL for file causes file processing step to fail 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4045]
### Location

Other (please describe below)

### What happened?

Some where in the file processing, we are getting and error with the code "302". This should just be a redirect, so perhaps some components (combine archive, rest of the processor) is not following redirects correctly and getting errors. Or this could be due to the s3 HEAD not working correctly . 

### What made it happen?

Run a simulation and see that Files are not posted and error is logged 

### Version

Offline (Some Library, Tool, or Image not on the web)

### Relevant log output

```shell
Post-processing of simulation run '61df27defbc1bd4ab9a35208' completed with status 'FAILED' due to 1 processing errors:
  * The COMBINE archive for simulation run '61df27defbc1bd4ab9a35208' could not be saved: 302: null
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
Was caused by not accounting for "./" in location

**Comment by jonrkarr** [comment]
The endpoints class accounts for this. We could simplify this by normalizing paths when COMBINE archives are processed.
