### ISSUE TITLE
🐛:  "Latest"  version of simulators does not return data from API

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4053]
### Location

BioSimulators API

### What happened?

Querying for the "latest" version of a simulators gives a 404 error. I noticed these popping up in our error reporting logs. I don't remember if this was ever a feature that was supported, or if only the /simulators/latest?id=simid endpoint was supported. In any case, it does seem that this is being used, so we should fix/add a redirect to get the endpoint to work. 

### What made it happen?

Make a get request to https://api.biosimulators.org/simulators/amici/latest

### Version

Production (Deployed on a .org domain), Development (Deployed on a .dev domain)

### Relevant log output

```shell
{"error":[{"status":"404","title":"Simulator with id 'amici' and version 'latest' was not found","detail":"\"Simulator with id 'amici' and version 'latest' was not found\""}]}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
This wasn't supported, but this can be supported

**Comment by jonrkarr** [comment]
I don't believe our apps are making those queries for `latest`
