### ISSUE TITLE
Change combine api temporary storage bucket

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4058]
Google cloud buckets only support lifecycle methods on a bucket wide scope. 

Therefore, the combine API must use a separate bucket than the main storage for temporary files

**Comment by jonrkarr** [comment]
That's easy enough to change.

With the Google bucket, the GitHub action for removing temp files can also be removed.

**Comment by bilalshaikh42** [comment]
Already done in the #4042

**Comment by jonrkarr** [comment]
The COMBINE API is still set up to use the main bucket. #4085 changes it to read the configuration for the new temporary bucket.
