### ISSUE TITLE
Increase processor concurrency

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4074]
Processing of about 150 simulations works with no/limited errors. But processing is very slow. I believe this is because each dispatch service worker only works on 1 simulation at a time, even though the vast majority of the time is waiting for network responses. Using a higher concurrency limit should speed things up quite a bit.

**Comment by jonrkarr** [comment]
Seems like a reasonable plan. Does this mean increase the number of replicas?

**Comment by bilalshaikh42** [comment]
The queue has an option for how many jobs it will process at once. This by default is 1. The number of jobs x number of replicas gives the total throughput. We can probably significantly increase the number of jobs since the bottleneck here would be CPU power, which we have a lot to spare. Most of the work is network calls which are async. This option is in the code itself.

**Comment by jonrkarr** [comment]
Got it. Sounds like our total throughput will be much higher than end of last year! End of last year, each run was relatively quick, but there was a big bottleneck at submission such that the total throughout was actually low.

**Comment by bilalshaikh42** [comment]
Updating the concurrency to 10 drastically sped up processing when running all example (32 runs) at a time.  Testing with 150 or so at a time is slower, but this is hard to separate from the issues with data service. 

Running the submit script took  3m24s

**Comment by jonrkarr** [comment]
I would imagine that 150 might start to overload the data service, resulting in processing slowing down.

Is hsload still in the Sbatch job, or in post-processing?

**Comment by bilalshaikh42** [comment]
Done in #idempotent
