### ISSUE TITLE
Disable VCell for online simulation until its logging it corrected

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4075]
Vcell simulations fail due to missing log

**Comment by jonrkarr** [comment]
VCell should be producing logs and saving them to `log.yml`. Here's an earlier run with VCell: https://run.biosimulations.dev/simulations/618d8b2389c70421ab793fdf#tab=log. Is there an error with the format? Could you point to an example run?

If the format is incorrect, we can demote the validation status of VCell (basically disable it) until its fixed.

**Comment by bilalshaikh42** [comment]
- 61e7431ef9a961c259123a56 --- Repressilator (Elowitz & Leibler, Nature, 2000; SBML; CVODE; VCell)
- 61e74326d8b0d0dbced04db3 --- Tumor-suppressive oscillations (Caravagna et al., J Theor Biol, 2010; SBML; CVODE; VCell)
- 61e74311f9a961c2591239eb --- Morphogenesis checkpoint (Ciliberto et al., J Cell Biol, 2003; SBML; CVODE; VCell)
- 61e7430c034d33f6e8eec761 --- Iron distribution (Parmar et al., BMC Syst Biol, 2017; SBML; CVODE; VCell)
-  61e74326f9a961c259123aa7 --- Tumor-suppressive oscillations (Caravagna et al., J Theor Biol, 2010; SBML; CVODE; VCell)
- 61e7431ed8b0d0dbced04d60 --- Repressilator (Elowitz & Leibler, Nature, 2000; SBML; CVODE; VCell)
- 61e74309d8b0d0dbced04cb1 --- Iron distribution (Parmar et al., BMC Syst Biol, 2017; SBML; CVODE; VCell)
- 61e7430ed8b0d0dbced04cd7 --- Morphogenesis checkpoint (Ciliberto et al., J Cell Biol, 2003; SBML; CVODE; VCell)

**Comment by jonrkarr** [comment]
Reported as virtualcell/vcell#130. I'll disable VCell by demoting its validation status and then close this issue.

**Comment by jonrkarr** [comment]
I demoted VCell's validation status in the BioSimulators database (both prod and dev). The tool for running the example simulations shouldn't run simulations with VCell until VCell is fixed.

**Comment by moraru** [comment]
Fixed in 6257b425bc6f79a85a38ea25e3416695a593cc55
VCell 7.4.0.33 validated https://github.com/biosimulators/Biosimulators/issues/535

**Comment by jonrkarr** [comment]
VCell will automatically be re-enabled in a few minutes when biosimulators/Biosimulators#536 is closed.
