### ISSUE TITLE
Testing results

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4076]
Ran the "submit script" with testing enabled 5 times concurrently. This is roughly 150 simulations (36 each). Other than the VCell runs (#4075) we had 2 failures

1.  61e74312034d33f6e8eec78b --- NFAT translocation (Tomida et al., EMBO J, 2003; SBML; LSODA/LSODAR; COPASI) 
409 on hsds. I ran this test with a single replica for hsds. The 409 could easily have been caused by the replica being overloaded considering we were previously running many more replicas. 

2. 61e7430ed8b0d0dbced04cd8 --- Lorenz system (Garny; CellML; CVODE; OpenCOR) 
Succeeded, but stuck for a long time on processing. This again caused issues due to the retrying (#4032). Not sure why the processing actually failed. No errors on the combine API.
Logs from API: 
```
40
(node:1) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [FormData]. Use emitter.setMaxListeners() to increase limit
39
(Use `node --trace-warnings ...` to show where the warning was created)
38
[Nest] 1  - 01/18/2022, 11:20:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
37
[Nest] 1  - 01/18/2022, 11:20:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
36
[Nest] 1  - 01/18/2022, 11:22:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
35
[Nest] 1  - 01/18/2022, 11:22:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
34
[Nest] 1  - 01/18/2022, 11:24:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
33
[Nest] 1  - 01/18/2022, 11:24:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
32
[Nest] 1  - 01/18/2022, 11:26:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
31
[Nest] 1  - 01/18/2022, 11:26:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
30
[Nest] 1  - 01/18/2022, 11:28:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
29
[Nest] 1  - 01/18/2022, 11:28:24 PM   DEBUG [Server] NatsStatus: type: "pingTimer", data: "1".
28
[Nest] 1  - 01/18/2022, 11:29:32 PM   ERROR [CompleteProcessor] Error: Error: socket hang up
27
[Nest] 1  - 01/18/2022, 11:29:32 PM    WARN [CompleteProcessor] The metadata for the COMBINE archive for simulation run '61e7430ed8b0d0dbced04cd8' could not be saved: undefined: undefined
26
[Nest] 1  - 01/18/2022, 11:29:33 PM   DEBUG [SshService] Connection ready
25
[Nest] 1  - 01/18/2022, 11:29:33 PM   DEBUG [SshService] Stream :: close :: code: 0, signal: undefined
24
[Nest] 1  - 01/18/2022, 11:29:33 PM   DEBUG [SshService] Connection closed
23
[Nest] 1  - 01/18/2022, 11:29:33 PM   DEBUG [SshService] Connection ready
22
[Nest] 1  - 01/18/2022, 11:29:33 PM   DEBUG [SshService] Stream :: close :: code: 0, signal: undefined
21
[Nest] 1  - 01/18/2022, 11:29:33 PM   DEBUG [SshService] Connection closed
20
[Nest] 1  - 01/18/2022, 11:29:33 PM   DEBUG [AuthClientService] Using cached token for audience api.biosimulations.org for client nzDn2Y8hHWKnddeUHJ0Ntwfa60ya4bJT
19
[Nest] 1  - 01/18/2022, 11:29:34 PM     LOG [LogService] The log for simulation run '61e7430ed8b0d0dbced04cd8' was successfully saved.
18
[Nest] 1  - 01/18/2022, 11:29:34 PM   DEBUG [AuthClientService] Using cached token for audience api.biosimulations.org for client nzDn2Y8hHWKnddeUHJ0Ntwfa60ya4bJT
17
[Nest] 1  - 01/18/2022, 11:29:34 PM     LOG [SimulationStatusService] The status of simulation run '61e7430ed8b0d0dbced04cd8' was successfully updated to 'SUCCEEDED'.
16
[Nest] 1  - 01/18/2022, 11:29:34 PM     LOG [CompleteProcessor] Post-processing of simulation run '61e7430ed8b0d0dbced04cd8' completed with status 'SUCCEEDED'.
15
14
The post-processing of simulation run '61e7430ed8b0d0dbced04cd8' raised one or more warnings:
13
  * The metadata for the COMBINE archive for simulation run '61e7430ed8b0d0dbced04cd8' could not be saved: undefined: undefined
```

**Comment by jonrkarr** [comment]
(1) may be exacerbated by still using the UConn bucket. Are you thinking of increasing the number of replicas?

For (2), the metadata saving failed. The error message for this needs to be corrected. Its appears not to be set up for the appropriate type of error (e.g., axios vs other).

**Comment by bilalshaikh42** [comment]
Second attempt far less successful (still running): over 60 or so failures (including vcell). All seem to be due to dataservice being overwhelmed. 

This is with 5 replicas. For almost 20 minutes, nearly 100% of responses from the data service were 503s. Data service logs indicate that the cluster is in a NOT READY state due to cache items needing to be flushed. 

Since there was such a drastic reduction of errors in the API while the dataservice seems to be getting "stuck" I think this is the UConn s3 bucket causing issues.

**Comment by bilalshaikh42** [comment]
> For (2), the metadata saving failed.

Yes, but not sure what caused this failure. The processing correctly handled the failure and marked it as a warning

**Comment by jonrkarr** [comment]
Its a warning because metadata is not required, unlike a log.

**Comment by bilalshaikh42** [comment]
yeah, that is correctly handled. I am trying to say that the issue is not knowing what caused the metadata to fail to save, but that everything else handled the failure exactly as it should.

> Second attempt far less successful (still running): over 60 or so failures (including vcell). All seem to be due to dataservice being overwhelmed.
> 
> This is with 5 replicas. For almost 20 minutes, nearly 100% of responses from the data service were 503s. Data service logs indicate that the cluster is in a NOT READY state due to cache items needing to be flushed.
> 
> Since there was such a drastic reduction of errors in the API while the dataservice seems to be getting "stuck" I think this is the UConn s3 bucket causing issues.

The high failure rate is misleading. This happened because I increased the number of replicas while there were pending writes to the s3 bucket. This causes the dataservice to lock up complelty, resulting in all remaining writes to fail. 

See https://github.com/HDFGroup/hsds/issues/104

**Comment by jonrkarr** [comment]
I'm going to try to write to John Ready about a blog post he asked us to write. I can ask him for help using HSDS with Google Cloud then.

**Comment by jonrkarr** [comment]
Sounds like HSDS was originally designed for AWS. Azure also works (see https://www.hdfgroup.org/2021/08/hsds-for-azure/). That post suggests Google Cloud should be close.

**Comment by bilalshaikh42** [comment]
> I'm going to try to write to John Ready about a blog post he asked us to write. I can ask him for help using HSDS with Google Cloud then.

The issue specifically is with the google cloud storage buckets. Getting it running on GKS instead of EKS was not a problem at all. This could be another post that we could help with. Getting HSDS running on google cloud

**Comment by bilalshaikh42** [comment]
Another test:  25 or so failures, most due to 409 conflicts when loading into dataservice. I remain suspious of the s3 bucket, though I wonder if just one replica of hsds might lead to better results

**Comment by jonrkarr** [comment]
I'll send you a link to the draft for the blog post. If you want to write a post on Google cloud, I think John would likely be happy to publish it.

**Comment by bilalshaikh42** [comment]
With the changes in #4087 I was able to run 120 simulations locally with 0 errors. The queues are all working well, with high concurrency. The bottleneck is the extraction step. This takes the majority of each processing workflow. It might be helpful to move this to the HPC or try to get it to start before the simulation run completes.

**Comment by jonrkarr** [comment]
Sounds great. 

Leaving further performance enhancement to the future seems good. Moving extraction to HPC sounds pretty easy. The COMBINE archives are already being downloaded there, unpacked there, and s3 sync is already installed there. The HPC also has more parallelism than our Kubernetes cluster, although not necessarily more bandwidth to Google object storage.

**Comment by bilalshaikh42** [comment]
With the dev deployment now working, 136 runs were all  completed and validated with no errors in about 8 minutes. The bottleneck was basically the concurrency limit on the extract and thumbnail steps (10 jobs at a time), so this should scale linearly with no issues. With 3 replicas, we can do 30 at a time, 5, 50 at a time etc. 
I think we can close this now and deploy to prod shortly

**Comment by bilalshaikh42** [comment]
300 runs seems to have taken out the HPC submit node however 😞 . Not sure how, since the concurrency limit also applies to job submissions/monitoring, so no more than 30 connections at a time should be happening

**Comment by jonrkarr** [comment]
Sounds great. I agree this seems closed!

Except pushing Mike to deal with the submit node, the only thing I could think to do is to rate limit submissions to the submit node.

**Comment by bilalshaikh42** [comment]
So that's why I am a bit confused because the concurrency limit of 10 also applies to the dispatch queue. So no more than 10 X number of replicas jobs should be submitted at any given time. So between the two runs, of 130 vs 300 there should be no additional load on the submit node since the same limit applies. There must be some other underlying issue that causes the node to go down frequently.

**Comment by jonrkarr** [comment]
The crash could largely be unrelated to your submissions. I agree the node seems to have some instability.

Maybe try 300 again after Mike restarts it.
