### ISSUE TITLE
🐛: No content type for HDF5 file and log.yaml in bucket

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4106]
### Location

Other (please describe below)

### What happened?

The storage buckets are not able to recognize the mimetypes for the two files. This can be fixed by splitting the s3 sync command in the bash script into three parts, one for the HDF5 file, one for yml and one for the rest. For the first two, we can provide the --content-type option to specify the type. 

I tried to do this, but it seems like am making some mistakes in the spacing/formatting of the script and running into issues

### What made it happen?

N/A

### Version

Production (Deployed on a .org domain), Development (Deployed on a .dev domain)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
## HDF5, Logs
I think this should be sufficient:
- `--content-type application/x-hdf` (`reports.h5`)
- `--content-type application/x-yaml` (`log.yml`)
- `--content-type application/zip` (`plots.zip`)
- `--content-type text/plain` (`job.output`; this mime-type isn't a great description, but it seems the most appropriate)

I don't think its necessary to also use `--no-guess-mime-type`

## COMBINE archives
Ideally, the content type of COMBINE archives would also be set to `application/zip` at
https://github.com/biosimulations/biosimulations/blob/5346ef79455a502bb58205271ab079a3133e5f1f/libs/shared/storage/src/lib/simulation-storage.service.ts#L164
https://github.com/biosimulations/biosimulations/blob/5346ef79455a502bb58205271ab079a3133e5f1f/libs/shared/storage/src/lib/shared-storage.service.ts#L142
```typescript
const request: AWS.S3.PutObjectRequest = {
    ...
    ContentType: 'XXX',
};
```

**Comment by bilalshaikh42** [comment]
The mimetypes for the zip files and the text files is correctly guessed so that is not needed. 

Good catch on adding it to the uploaded combine archive.

**Comment by jonrkarr** [comment]
If needed, we could also set mime types for the contents of archives by the manifest info. I'm guessing content types can be updated after objects are put to S3. This doesn't seem to be needed. Thumbails and Vega files seem to be loading fine.
