### ISSUE TITLE
Clarify concepts and branding

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4110]
@jmdetloff raised a point to clarify how some of our concepts are presented. We've discussed this a bit. The lack of good precedence in our field doesn't help. 

Nevertheless, I think a few things could help:
- [x] Change the `/simulations` route to `/runs` 
- [x] Change the related branding for this route e.g., "Your simulations" --> "Your simulation runs"
- [x] Clarify terminology in the metadata of the project view (e.g., "Simulation" --> "Simulation type", "Project" --> "Project format")
- [x] Update home pages. These have diverged from the concepts we've delineated.
- [ ] "Projects" -- I don't think this is sufficiently clear, but not sure what to do about that.
- [x] Add documentation page which outlines this terminology (model, simulation, project, etc.)

**Comment by bilalshaikh42** [comment]
We should also create a documentation page for each of these concepts.
