### ISSUE TITLE
Remove statusReason from SimulationRun 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4111]
The status reason field is no longer used on the frontend.  We should remove it from the API as it contains mostly internal implementation details. Alternatively, we can simplify the status reason or include it in the front end

@jonrkarr the front end code takes the status reason as input to the component to display the logs but does not seem to actually use it. Is this intentional?

**Comment by jonrkarr** [comment]
I think this is safe to remove from the API (or least what's returned without an admin account) and downstream. 

I believe the frontend did use `statusReason`, but not anymore. I believe the frontend used this until we added post-processing information to the log. It looks like I forgot to clean up `statusReason` from a couple of the components.
