### ISSUE TITLE
Investigate how to speed up extraction

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4112]
The extraction of the combine archive is the bottleneck in processing. There are a few ideas on how to fix this. Getting some empirical data would be helpful 

1. Try to start the extraction before the processing step, but still maintain the dependency for the other steps
2. Move the extraction to the HPC
3. move extraction and additional processing steps (one that don't need the simulation run to complete, essentially all but the logs, output) to a separate workflow that starts when the job is dispatched.

**Comment by jonrkarr** [comment]
Done in #4329
