### ISSUE TITLE
Improve display of logs

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4113]
Currently, the processing steps are logged as shown in https://run.biosimulations.dev/simulations/61fb2a83441829748d0ee603#tab=log
This can be cleaned  up to be more visually appealing

**Comment by jonrkarr** [comment]
The formatting seems fine to me. At least its no worse than the rest of the log. 

Maybe just:
- Remove newline after `==== Post-processing simulation run ===` for consistency with rest of log
- Add a new line before `==== Run complete ... ====` for consistency with rest of log
- Clean up `.....` (e.g., `Post the SED-ML file to the API.....Succeeded` --> `Post the SED-ML file to the API ... succeeded.`
