### ISSUE TITLE
🐛: Boolnet simulations failing

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4127]
### Location

runBiosimulations

### What happened?

Boolnet simulations have a higher than  average failure rate. The error is consistent, shown below in the logs

### What made it happen?

Submitted the following simulation
https://run.biosimulations.dev/simulations/61fc430b0da091d9e8116d82#tab=log

### Version

Development (Deployed on a .dev domain)

### Relevant log output

```shell
INFO:    Using cached SIF image
Fatal error: cannot create 'R_TempDir'
srun: error: xanadu-61: task 0: Exited with exit code 2
srun: Terminating job step 4023610.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
This is probably related to upgrading R. R seems to be trying to use a directory (value of `R_TempDir`) that it can't write to in UConn HPC. R is likely trying to use `/tmp` or a sub-directory of it.

The SBatch service sets the `--tmpdir` argument for `singularity run` to `local`. @bilalshaikh42 what does this do? I don't see that argument in the version of singularity on my machine.

Potential options
- Direct R to an accessible directory using one of the `TMPDIR`, `TMP`, or `TEMP` environment variables (i.e. set the value of `TMPDIR` with `singularity run ...` in the sbatch service.
- Bind `/tmp` in the containers to an accessible location (i.e. add `--bind /tmp/$jobId:/tmp` to `singularity run ...`)

**Comment by jonrkarr** [comment]
@bilalshaikh42 is `/tmp` not expected to be accessible within containers in the HPC?

**Comment by bilalshaikh42** [comment]
local is folder that will be located on the actual host the job is running on. The reason we want to use that over something in the home directory for example is that cache/tmp files shouldn't need to traverse the network since this is very slow for the types of operation that need a tmp directory

**Comment by bilalshaikh42** [comment]
> @bilalshaikh42 is `/tmp` not expected to be accessible within containers in the HPC?

I am not sure about this. I seem to remember that it is not, but will need to confirm with @mpw6

**Comment by jonrkarr** [comment]
This issue overlaps with #4128.

I agree we want to bind `/tmp` to the local file system. However, it sounds like `/tmp` isn't guaranteed to have space.

@mpw6 suggested binding `/tmp` to `/local` (add `--bind /local:/tmp` to `singularity run ...`), which is much larger.

**Comment by bilalshaikh42** [comment]
Superceeded by #4135
