### ISSUE TITLE
🐛:  Api repeatedly crashes on submitting BiGG projects

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4146]
### Location

BioSimulations API

### What happened?

Something about the Bigg Projects is causing the API to crash repeatedly. This happens even if the biosimulations-bigg python package first simulates each project locally, so it does not seem to be caused by submitting too many simulations at a time. The major difference between the Bigg Projects and the example runs is the size of the results, so I suspect that the large results are causing some issue either with Redis or the validation endpoint

### What made it happen?

Running the biosimulations-bigg submit script

### Version

Production (Deployed on a .org domain)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jonrkarr** [comment]
The results are a little larger, but not particularly large since theres no time dimension.

**Comment by jonrkarr** [comment]
You could try removing the caching of simulation results. 

The validation could be refactored so that it's moved into the dispatch service and it's result is stored to the database. This would avoid rechecking this later and allow more control over the computational load.

**Comment by jonrkarr** [comment]
Sounds like this doesn't appear to be a significant issue. @bilalshaikh42 can we close this, or mark this as `future`?

Refactoring calculation of summaries is captured by #4220.

**Comment by bilalshaikh42** [comment]
With the additional issues this is probably good to close
