### ISSUE TITLE
Add endpoint for modifying COMBINE archives

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4148]
New endpoint discussed in #3516 with @jmdetloff needed for UI for modifying COMBINE archives

Route: `/combine/modify`

Input
- COMBINE archive or URL for COMBINE archive
- New specifications for SED-ML files

Output: modified COMBINE archive OR S3 URL for modified archive

Operation
- If a URL was submitted, download the COMBINE archive
- Unpack the archive (with validation disabled)
- Use the SED-ML specifications to write new SED-ML files over the original ones
- Repackage the archive (with validation disabled)
- Return the archive OR save the archive to the second S3 bucket and return its URL

Validation, at least for metadata, should be disabled that the invalid metadata doesn't prevent users from modifying archives.

**Comment by bilalshaikh42** [comment]
Would it be feasible to architect this to use the sedml file and model files directly? Seems that it would save some bandwidth/time on downloading archives. 

I suppose that might not work with sedml files that refer to multiple model files

**Comment by jonrkarr** [comment]
The purpose of this new endpoint is to support a web form for modifying archives (see #3516).

We do already have an endpoint for creating COMBINE archives (`/combine/create`). This endpoint could be reused for this new purpose, however I thought a new endpoint would be simpler for the UI to use. The two endpoints would use much of the same underlying Python code. 

The inputs to the existing endpoint for creating COMBINE archives are:
- Specifications of SED-ML documents
- Uploads or URLs for all other files

If we reuse the existing endpoint, the new form would indicate the files that should be included in the archive via URLs to our S3 bucket. The COMBINE archive creation endpoint would then resolve these URLs. The create COMBINE archive endpoint would download the same content as the proposed new endpoint (less SED-ML files). The main difference from the proposed endpoint is that the existing endpoint would download each file individually from S3, whereas the new endpoint would download all of the files as a single compressed COMBINE archive.

One other advantage I see to creating a new endpoint, is that this endpoint could automatically add RDF that indicates that the new archive was derived from the old archive (of course this functionality could also be tacked onto the existing endpoint via a more general way for editing metadata).

Other than reusing existing code, one other advantage I see to using the existing endpoint is that its more straightforward to let uses add/remove the other files in COMBINE archives. However, I don't think thats necessary for the intended use case.
