### ISSUE TITLE
Truncate descriptions in JSON-LD metadata to 5000 characters for compatibility with Google

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4180]
One of the relevant places in the code: https://github.com/biosimulations/biosimulations/blob/10c713886ea555e8f2b0dbbdb76d3dcd882cc9d7/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts#L322

**Comment by bilalshaikh42** [comment]
It seems to be the other way around. The text that was flagged was "Boolean model of the budding yeast cell cycle" which is 45 characters, short of the minimum 50 characters

**Comment by jonrkarr** [comment]
I know the error is because the description is too short. We can't make descriptions longer, but we can truncate them to the 5,000 character limit if needed.
