### ISSUE TITLE
Investigate Performance Issues

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4236]
I submitted the BiGG projects again to update the biosimulations-bigg repo, which is tracking what the BiGG simulation runs. Several hours later 8 several runs are still running, 5, simulation failed, and 1 failed to publish to BioSimulations. The logs show a number of issues. See [error-log.txt](https://github.com/biosimulations/biosimulations/files/8083611/error-log.txt). One of the Redis replicas appeared to die (and is still degraded). Unless this was due to a temporary issue (there do appear to have been some issues connecting to UConn HPC), it seems there may still be performance issues.

- Stuck in processing (8):
  - 620d621c9c2803ef8a22a07c
  - 620d621e9c2803ef8a22a07f
  - 620d62399c2803ef8a22a0c1
  - 620d62428dda8ca4122e993d
  - 620d6252362ac03746b1eff9
  - 620d626e8dda8ca4122e99bf
  - 620d6293c904db6986a248f8
  - 620d62edc904db6986a249f6
- Failed (5):
  - 620d62459c2803ef8a22a0e5
  - 620d625092c0f14f91cfefd3
  - 620d62a992c0f14f91cff086
  - 620d62ac362ac03746b1f109
  - 620d62c092c0f14f91cff0c2
- Failed to publish to BioSimulations (1):
   - 620d62f4c904db6986a24a1d

## Errors
Some of the most frequent errors I noticed. The number of occurrences is at the beginning of each bullet. In decreasing order of frequency:
- 125: Request failed with status code 502 for Patch operation on path. Example https://api.biosimulations.org/runs/620d6232c904db6986a247f4
- 25: Error: Missing lock for job. Example 620d6264362ac03746b1f05a
- 20: Request failed with status code 409 for Post operation on path. Example https://api.biosimulations.org/logs/620d62a992c0f14f91cff086 for simulation run 620d62a992c0f14f91cff086
- 15: Error: Job is not in the active state. delayed. Example 620d628cc904db6986a248f1
- 12: An error occurred in submitting an HPC job for simulation run. Example '62066a569c2803ef8a229ab7'
- 10: Request failed with status code 502 for Post operation on path. Example https://api.biosimulations.org/specifications/620d62ec362ac03746b1f1c7
- 10: Request failed with status code 502 for Post operation on path. Example https://api.biosimulations.org/metadata/620d62f2c904db6986a24a0d
- 3: Request failed with status code 502 for Post operation on path. Example https://api.biosimulations.org/files/620d620e362ac03746b1ef40 for simulation run 620d620e362ac03746b1ef40
- 3: Request failed with status code 502 for Post operation on path. Example https://api.biosimulations.org/files/620d62b4362ac03746b1f124

**Comment by bilalshaikh42** [comment]
A few things that I am noticing that are different from the example runs
1. Redis memory usage shoots much higher 
2. Combine API goings down often, causing the retries and memory issues on the dispatch-service
3. API has a lot of 502s, despite not actually going down. I think this is due to the loadbalancer assuming no response is coming for some of the larger requests of logs etc that may be a bit slow

**Comment by bilalshaikh42** [comment]
Logs seem to be taking up the most space: for example, https://api.biosimulations.org/logs/620ea96261a88cceaed29d18 has nearly 13MB of logs.  The top 20 keys on redis using the most space are all log objects

This is somehow unique to the Bigg runs. Running all 90 or so Bigg simulations uses nearly 2GB of memory on redis. On the other hand, running nearly 300 of the example runs is using less than 200MB

**Comment by bilalshaikh42** [comment]
Plans to address this
- [ ] Determine why combine API fails. 
- [x] Clean out jobs from Redis as soon as the processing is complete 
- [x] ~~Reduce the concurrency of the CPU intensive jobs~~ I don't think this is a problem. The lock issue must have been from redis crashing and loosing the lock keys, not the job getting stuck. Once the changes from #4253 are deployed, we can test again 
- [ ] Get the Redis backups connected to bull. Look into deploying redis sentinel 
- [ ] Restore larger node sizes

**Comment by bilalshaikh42** [comment]
@jonrkarr Could we reduce the warnings logged by the simulators/turn them off in the Sbatch script? 
It seems like the vast majority of the logs size is coming from this sort of message repeated over and over 

```
BioSimulatorsWarning: \u001b[33mCOMBINE/OMEX archive may be invalid.\r\n 
 - The manifest does not include its parent COMBINE/OMEX archive. Manifests should include their parent COMBINE/OMEX archives.\u001b[0m\r\n  warnings.warn(termcolor.colored(message, Colors.warning.value), category)\
 - r\n/usr/local/lib/python3.9/site-packages/biosimulators_utils/warnings.py:31: BioSimulatorsWarning: \u001b[33mThe SED document is potentially incorrect.\r\n  - Model `model` may be invalid.\r\n    - The model file `iCHOv1_DG44.xml` may be invalid.\r\n      
 - In situations where a mathematical expression refers to a compartment, species or parameter, it is necessary to know the units of the object to establish unit consistency. In models where the units of an object have not been declared, libSBML does not yet have the functionality to accurately verify the consistency of the units in mathematical expressions referring to that object. \r\n        
 -  The units of the <compartment> 'c' cannot be fully checked. Unit consistency reported as either no errors or further unit errors related to this object may not be accurate.\r\n        \r\n      - If neither the attribute 'units' nor the attribute 'spatialDimensions' on a Compartment object is set, the unit associated with that compartment's size is undefined.\r\n        Reference: L3V1 Section 4.5\r\n        
 -  The <compartment> 'c' has no discernable units.\r\n        \r\n      - In situations where a mathematical expression refers to a compartment, species or parameter, it is necessary to know the units of the object to establish unit consistency. In models where the units of an object have not been declared, libSBML does not yet have the functionality to accurately verify the consistency of the units in mathematical expressions referring to that object. \r\n         
 - The units of the <compartment> 'x' cannot be fully checked. Unit consistency reported as either no errors or further unit errors related to this object may not be accurate.\r\n        \r\n      
 - If neither the attribute 'units' nor the attribute 'spatialDimensions' on a Compartment object is set, the unit associated with that compartment's size is undefined.\r\n        Reference: L3V1 Section 4.5\r\n      
 -    The <compartment> 'x' has no discernable units.\r\n        \r\n    
 -   - In situations where a mathematical expression refers to a compartment, species or parameter, it is necessary to know the units of the object to establish unit consistency. In models where the units of an object have not been declared, libSBML does not yet have the functionality to accurately verify the consistency of the units in mathematical expressions referring to that object. \r\n         The units of the <compartment> 'r' cannot be fully checked. Unit consistency reported as either no errors or further unit errors related to this object may not be accurate.\r\n        \r\n   
 -    - If neither the attribute 'units' nor the attribute 'spatialDimensions' on a Compartment object is set, the unit associated with that compartment's size is undefined.\r\n        Reference: L3V1 Section 4.5\r\n    
 -      The <compartment> 'r' has no discernable units.\r\n        \r\n     
 -  - In situations where a mathematical expression refers to a compartment, species or parameter, it is necessary to know the units of the object to establish unit consistency. In models where the units of an object have not been declared, libSBML does not yet have the functionality to accurately verify the consistency of the units in mathematical expressions referring to that object. \r\n         The units of the <compartment> 'm' cannot be fully checked. Unit consistency reported as either no errors or further unit errors related to this object may not be accurate.\r\n      
 -   \r\n      - If neither the attribute 'units' nor the attribute 'spatialDimensions' on a Compartment object is set, the unit associated with that compartment's size is undefined.\r\n        Reference: L3V1 Section 4.5\r\n  
 -        The <compartment> 'm' has no discernable units.\r\n        \r\n      - In situations where a mathematical expression refers to a compartment, species or parameter, it is necessary to know the units of the object to establish unit consistency. In models where the units of an object have not been declared, libSBML does not yet have the functionality to accurately verify the consistency of the units in mathematical expressions referring to that object. \r\n       
 -   The units of the <compartment> 'mm' cannot be fully checked. Unit consistency reported as either no errors or further unit errors related to this object may not be accurate.\r\n        \r\n      - If neither the attribute 'units' nor the attribute 'spatialDimensions' on a Compartment object is set, the unit associated with that compartment's size is undefined.\r\n        Reference: L3V1 Section 4.5\r\n         The <compartment> 'mm' has no discernable units.\r\n        \r\n     
 -  - In situations where a mathematical expression refers to a compartment, species or parameter, it is necessary to know the units of the object to establish unit consistency. In models where the units of an object have not been declared, libSBML does not yet have the functionality to accurately verify the consistency of the units in mathematical expressions referring to that object. \r\n 
```

**Comment by jonrkarr** [comment]
The logs are largely coming from libSBML. 13mb doesn't seem like a lot. I don't think its unreasonable to support logs of this size.

**Comment by jonrkarr** [comment]
I reduced the size of logs that simulation tools generate. For flux balance and MASS models, the logs should now be much smaller and more easily read by humans.
