### ISSUE TITLE
Combine API error 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4265]
Stackdriver Error Reporting error detail

AttributeError: 'SedShadedArea' object has no attribute 'getLogY'
https://console.cloud.google.com/errors/CJGlwMT995K17wE?project=biosimulations&src=VESPA&time=P30D

**Comment by jonrkarr** [comment]
This is from a SED-ML L1V4 document. It looks like SED-ML L1V4 made an attribute polymorphic.

**Comment by jonrkarr** [comment]
Underlying issue will be addressed with biosimulators/Biosimulators_utils#100

**Comment by jonrkarr** [comment]
Can close once this package is bumped to biosimulators-utils 0.1.162
