### ISSUE TITLE
🐛: Smoldyn Simulation failed

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4281]
### Location

runBiosimulations

### What happened?

Another x11 related error on smoldyn

### What made it happen?

Running examples (5 of each)

### Version

Production (Deployed on a .org domain)

### Relevant log output

```shell
Thank you for using runBioSimulations!

================================================ Loading Singularity ================================================

========================================== Downloading COMBINE/OMEX archive =========================================
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   139  100   139    0     0    483      0 --:--:-- --:--:-- --:--:--   482
100 18714  100 18714    0     0  48384      0 --:--:-- --:--:-- --:--:-- 48384

=========================================== Executing COMBINE/OMEX archive ==========================================
INFO:    Using cached SIF image
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
srun: error: xanadu-62: task 0: Exited with exit code 1
srun: Terminating job step 4265757.1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
This seems to be a permsissions issue. Seem that /tmp/.X11-unix may be only accessible to root, or just '/tmp` itself

**Comment by jonrkarr** [comment]
We're mapping container:`/tmp` to host:`/local`. In retrospect, we probably want to map container:`/tmp` to host:`/local/{unique-directory}`. This would guarantee each container gets a separate space in the filesystem.
