### ISSUE TITLE
The SSH connection for refreshing simulator Docker images gets stale

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4304]
Image refreshing is not working reliably

Example:
```json
{
  "simulator": "pyneuroml",
  "version": "0.5.20"
}
```

**Comment by bilalshaikh42** [comment]
I have not looked at this in a long time. Was the sbatch script for this updated along with the other changes we made to the singularity configuration? I'll look at the HPC job and logs and see what could be the issue

**Comment by jonrkarr** [comment]
Its working, but not consistently. That leads me to think its the SSH connection.

**Comment by bilalshaikh42** [comment]
By not working, do you mean the image is not updated as it should be? Or there is some error? I believe due to the cache of the singularity build, sometimes multiple images being built at the same time can cause a cache conflict that  prevents the build from completing

**Comment by bilalshaikh42** [comment]
~~An issue with the SSH connection would cause a clear error in the logs (I don't see any currently)~~

I was looking at the dev deployment. The prod has ssh errors

**Comment by jonrkarr** [comment]
Sometimes the endpoint succeeds. Sometimes I get a 500 error.

**Comment by bilalshaikh42** [comment]
Ah okay. I'll investigate further

**Comment by jonrkarr** [comment]
This is what I see in the log
```
{
  "error": [
    {
      "status": "500",
      "title": "Internal Server Error",
      "detail": "An unexpected error occurred",
      "meta": {
        "time": 1645577583889,
        "url": "/images/refresh"
      }
    }
  ]
}
```

**Comment by jonrkarr** [comment]
I haven't looked at the HPC jobs. I don't have any reason to think that isn't working.

**Comment by bilalshaikh42** [comment]
Yup, I was looking at the dev. This is caused bc the SSH connection gets stale after a long time of no use (#4099). For the simulation related calls, this is now handled by the queues retrying. I did not account for this for the image updates. We can either add a queue for these as well, or since this is internal, just do the retries on the client side. When the ssh connection errors, it reconnects so that it is ready for the next retry

**Comment by bilalshaikh42** [comment]
```
[Nest] 1  - 02/23/2022, 12:53:03 AM   DEBUG [SshService] Executing command
28
[Nest] 1  - 02/23/2022, 12:53:03 AM   ERROR [SshService] Connection Error: Error: read ECONNRESET
27
[Nest] 1  - 02/23/2022, 12:53:03 AM     LOG [SshService] Retrying SSH connection
26
[Nest] 1  - 02/23/2022, 12:53:03 AM   ERROR [SshService] Error: No response from server
25
[Nest] 1  - 02/23/2022, 12:53:03 AM   ERROR [SshService] Stream is null
24
[Nest] 1  - 02/23/2022, 12:53:03 AM   ERROR [RpcExceptionsHandler] No response from server
23
Error: No response from server
22
    at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:764:19)
21
    at Socket.emit (node:events:520:28)
20
    at Socket.emit (node:domain:475:12)
19
    at TCP.<anonymous> (node:net:687:12)
18
[Nest] 1  - 02/23/2022, 12:53:03 AM   DEBUG [SshService] Initializing connection
17
[Nest] 1  - 02/23/2022, 12:53:04 AM   DEBUG [SshService] Connection ready
```
As you can see, the connection failed, but is re initialized, so new calls now will work. This explains the inconsistent behavior. 
I think the best option will be to just add a queue for this, because worst case, you could hit every replica on retires until you are guaranteed to hit a replica with a valid connection

**Comment by jonrkarr** [comment]
However you want to manage it is fine. A queue seems reasonable.

**Comment by jonrkarr** [comment]
The Sbatch script is working fine. #4305 organizes the scripts and logs a bit. The issue seems to be the SSH connection.

**Comment by bilalshaikh42** [comment]
I don't think the attached PR will solve this issue. The init connection is a async stream so the retired command will be called before the initialization has completed

**Comment by jonrkarr** [comment]
The connections still go stale

**Comment by jonrkarr** [comment]
@bilalshaikh42 please fix this. Currently I have to manually refresh each new version of each simulation tool.

**Comment by bilalshaikh42** [comment]
Sorry, somehow missed this was reopened. 

Will do
