### ISSUE TITLE
dispatch-service needs to be more reliable for testing in deployment workflow

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4342]
Tests haven't been reliable starting with 9.11.3 (see run-5352951560) which did not make any relevant changes.

**Comment by bilalshaikh42** [comment]
There must have been some change causing this, as the timeout is quite large. There could be an issue with the deployment, in which  case that should be addressed before promoting to prod

**Comment by jonrkarr** [comment]
Collapsing multiple similar issues into #4353.
