### ISSUE TITLE
Production deploys version in advance of what's been released to it

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#4352]
https://deployment.biosimulations.org/applications/biosimulations-prod shows v9.13.1 even though this hasn't been released. Critically, this could be out of sync with the frontend. Not sure if this comes from deleting the HSDS and resyncing.

**Comment by bilalshaikh42** [comment]
I am not seeing the issue. 

The message on the top is simply the latest commit message of the git repo that has been synced. 
The message states that dev was updated to 9.13.1. The actual version of the deployed pods in prod is older
