### ISSUE TITLE
🐛:  Tasks for CellML models do not contain language abbreviation field

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4522]
### Location

BioSimulations API

### What happened?

When getting project summaries, the task summaries do not contain the "acronym" field for cell-ml models

### What made it happen?

This is potentially happening either in the API endpoint for the summaries or is due to combine-API not returning the information. I don't recall exactly where this information is set. 

 

### Version

Production (Deployed on a .org domain)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
This should be fixed by #4524.
Rather than loading the data from JSON file which is going to of type "any" , it might be useful to more precisely define the types and data in a regular typescript file.  The code also uses "as" quite a bit which can be removed to make it more robust.

@jonrkarr is this information generated by hand or does it update with the ontology updates? If it is not automatically updated, its trivial to simply define it in typescript instead.

**Comment by jonrkarr** [comment]
CellML doesn't have a longer name. 

This information is hard-coded. At least for now, it can't be read from EDAM.

**Comment by bilalshaikh42** [comment]
Yup, the reason for the acronym field not being present makes sense, but I was just using it as default to display as labels on the chart.  I thought the table component was also doing this, but it must have accounted for this since it displays "CellML" correctly.

**Comment by jonrkarr** [comment]
You should display the acronym || name.
