### ISSUE TITLE
🐛: Simulation Run module not loading on runBioSimulations

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#4547]
### Location

runBiosimulations

### What happened?

An error message is displayed when attempting to load the simulation run page

### What made it happen?

1. Go to https://run.biosimulations.dev
2. Click on "Run a simulation"
3. Observe the error

### Version

Development (Deployed on a .dev domain)

### Relevant log output

```shell
error-handler.ts:32 Error: Uncaught (in promise): ReferenceError: Cannot access 'SimulationsModule' before initialization
ReferenceError: Cannot access 'SimulationsModule' before initialization
    at Module.SimulationsModule (simulations-routing.module.ts:132:25)
    at app.module.ts:33:93
    at _ZoneDelegate.invoke (zone.js:372:1)
    at Object.onInvoke (core.mjs:25608:1)
    at _ZoneDelegate.invoke (zone.js:371:1)
    at Zone.run (zone.js:134:1)
    at zone.js:1275:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at TaskTrackingZoneSpec.onInvokeTask (task-tracking.js:73:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at resolvePromise (zone.js:1211:1)
    at resolvePromise (zone.js:1165:1)
    at zone.js:1278:1
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at TaskTrackingZoneSpec.onInvokeTask (task-tracking.js:73:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Object.onInvokeTask (core.mjs:25595:1)
    at _ZoneDelegate.invokeTask (zone.js:405:1)
    at Zone.runTask (zone.js:178:1)
    at drainMicroTaskQueue (zone.js:585:1)
handleError	@	error-handler.ts:32
next	@	core.mjs:26174
next	@	Subscriber.js:91
_next	@	Subscriber.js:60
next	@	Subscriber.js:31
(anonymous)	@	Subject.js:34
errorContext	@	errorContext.js:19
next	@	Subject.js:27
emit	@	core.mjs:22483
(anonymous)	@	core.mjs:25634
invoke	@	zone.js:372
run	@	zone.js:134
runOutsideAngular	@	core.mjs:25507
onHandleError	@	core.mjs:25634
handleError	@	zone.js:376
runGuarded	@	zone.js:147
api.microtaskDrainDone	@	zone.js:1072
drainMicroTaskQueue	@	zone.js:592
invokeTask	@	zone.js:491
invokeTask	@	zone.js:1648
globalCallback	@	zone.js:1679
globalZoneAwareCallback	@	zone.js:1712
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bilalshaikh42** [comment]
@jonrkarr Could use some help with this one. 
The last deployment that worked was deployed [ May 26th at 7:54 pm](https://628f2299384877291ce62b81--run-biosimulations-dev.netlify.app/)
The first deployment that shows this error was deployed[ May 27th at 7:59 pm](https://629165d1b0f7b613a94a9205--run-biosimulations-dev.netlify.app/)

This probably corresponds to release [v9.16.0](https://github.com/biosimulations/biosimulations/releases/tag/v9.16.0) but there is nothing in that release that seems like it could cause issues other than the addition of the thi.ng/color library

**Comment by jonrkarr** [comment]
I'd examine changes to versions of dependencies as nothing else relevant would have changed between May 26 and 27.

**Comment by bilalshaikh42** [comment]
yup. going through git bisect to try to pin down the issue. It's tricky due to the build also being cached. But I am pretty sure now that v9.16.0 was the first release with the issue and v9.15.1 was good

**Comment by bilalshaikh42** [comment]
Looks like it is indeed using @thi.ng/color (or at least commit) causing the issue. I am confused though since it shouldn't impact the dispatch app, just the platform. I would have thought it wouldn't even get included in the final bundle.

```
ac226d95935fc020ca19379f6e2a8b435fd690db is the first bad commit
commit ac226d95935fc020ca19379f6e2a8b435fd690db
Author: Jonathan Karr <jonrkarr@gmail.com>
Date:   Fri May 27 10:40:47 2022 -0400

    fix(platform): applied our color palette to summary charts

 declarations.d.ts                                  |     1 -
 .../summary-page/src/lib/declarations.d.ts         |     1 -
 .../src/lib/palette-service/palette.service.ts     |    23 +-
 package-lock.json                                  | 37274 +++++++++++--------
 package.json                                       |     2 +-
 5 files changed, 22177 insertions(+), 15124 deletions(-)
```

**Comment by jonrkarr** [comment]
This is when i had trouble resolving a set of versions of dependencies. Did you try rebuilding the package lock?

**Comment by bilalshaikh42** [comment]
This seems to be caused by thi.ng/color depending on buffer.js, which in turn expects that "global" is defined. This was removed from angular back in version 6. 

However, there is a workaround that seems to fix the issue 
https://github.com/angular/angular-cli/issues/9827#issuecomment-386154063
