### ISSUE TITLE
Log page left scrollbar problems

### ISSUE THREAD

**Issue by luciansmith** [reproducible-biomedical-modeling/CRBM-Viz#4761]
https://biosimulations.org/runs/64ef97a728f96276a163a98e

![image](https://github.com/biosimulations/biosimulations/assets/1736150/6f3c2509-68d1-455d-97a6-80abd0827360)

![image](https://github.com/biosimulations/biosimulations/assets/1736150/ac6fedd8-4175-4e1e-b437-f99216419823)

**Comment by AlexPatrie** [comment]
Fixed in #4770
