### ISSUE TITLE
Too much whitespace in log tab

### ISSUE THREAD

**Issue by luciansmith** [reproducible-biomedical-modeling/CRBM-Viz#4763]
The log tab on pages like https://biosimulations.org/runs/64ef9aee28f96276a163d941 shouldn't have this much whitespace:

![image](https://github.com/biosimulations/biosimulations/assets/1736150/9dbd1553-3010-410c-85f8-acfd5c50de70)

**Comment by AlexPatrie** [comment]
Fixed with #4770
