### ISSUE TITLE
Run tabs all different widths

### ISSUE THREAD

**Issue by luciansmith** [reproducible-biomedical-modeling/CRBM-Viz#4764]
Many of the tabs on pages like https://biosimulations.org/runs/64ef9aee28f96276a163d941 are different widths:

![image](https://github.com/biosimulations/biosimulations/assets/1736150/17a66c79-c741-4d2d-ba93-c7a8bbfbb91c)

![image](https://github.com/biosimulations/biosimulations/assets/1736150/bb33bd05-6f33-4771-8594-5797245f322f)

![image](https://github.com/biosimulations/biosimulations/assets/1736150/0dd93d13-95be-478a-9103-ba4500e0f70f)

![image](https://github.com/biosimulations/biosimulations/assets/1736150/3a00f8e4-a8f8-455c-ad3d-f383bdcdef3f)

![image](https://github.com/biosimulations/biosimulations/assets/1736150/11704588-15dc-458b-b762-777e05eb2c7b)

**Comment by AlexPatrie** [comment]
Fixed with #4770.
