### ISSUE TITLE
Log files misaligned to not show everything

### ISSUE THREAD

**Issue by luciansmith** [reproducible-biomedical-modeling/CRBM-Viz#4766]
https://run.biosimulations.org/runs/64e5319b548ceb84f3ad843c#tab=log

![image](https://github.com/biosimulations/biosimulations/assets/1736150/0f6e513e-135e-49c6-9ab2-5466ab1a273e)

**Comment by luciansmith** [comment]
(note no horizontal scroll bar)

**Comment by AlexPatrie** [comment]
Fixed with #4770.
