### ISSUE TITLE
'run a new simulation' page needs to be redesigned

### ISSUE THREAD

**Issue by luciansmith** [reproducible-biomedical-modeling/CRBM-Viz#4769]
https://run.biosimulations.org/runs/new

The old page and the new page have the same problems; this is a proposed improvement, not a new thing introduced by the redesign.

Basically, there's entirely too much space devoted to options that nobody will usually care about.  There are exactly two things that the user should be asked about, and they should be at the very top:

* The OMEX file itself
* What simulator they want to use for it.

That's it!  

The 'Capabilities required' section is auto-filled when you submit the OMEX file, and as far as I know can't be changed anyway, nor should it be.

The 'Simulation tool' section should pull up the appropriate simulators to the top of the list, or just drop the other ones entirely.  The code here sometimes gets it wrong as to what simulators can simulate what (see #4753), but as-is, it doesn't let you select the greyed-out simulators anyway.  Don't list the greyed-out simulators at all; just let the user choose among the allowed ones.

The 'Commercial solvers' section should only appear if a simulator was chosen that might need it.  Even then, it should be a small checkbox with a pop-up explanation; not something that takes 1/4 of the page.

'Computational Resources' should normally be hidden, and only expanded if requested.  I've never once needed to change these.

'Metadata':  While you could allow the user to fill in a name here, it shouldn't be required.  By default, just assign an arbitrary unique name, perhaps 'timestamp/OMEX filename'.  

Notifications:  Another section that can normally be skipped.  Also, if a user fills out their email address, that should be consent enough; they shouldn't need to additionally check the 'I am OK receiving an email' box.  Just tell them (maybe in a popup) that the address will only be used to email them a single notification when the simulation is complete.  Also, I would tie this to the user's account, and let them set a default send/don't_send option so they don't have to select it every time if they want it.

The 'Run' button shouldn't be only at the bottom; it should be accessible from the top where you can select your two main options.

**Comment by AlexPatrie** [comment]
This is very valuable feedback. I completely agree with you. The granularity of simulation specification should not be required to be explicitly laid out by the user for each simulation. From the perspective of user journey, this is potentially a huge turn off if something like 'Computational Resources' is not easily digested by the user. I will be creating a separate PR for this concern.
