### ISSUE TITLE
Auto-expand all 'details' information for projects

### ISSUE THREAD

**Issue by luciansmith** [reproducible-biomedical-modeling/CRBM-Viz#4771]
Right now, two of the five categories are auto-expanded when you click on 'details':

![image](https://github.com/biosimulations/biosimulations/assets/1736150/cde60e12-e155-410d-864c-cf35991177be)

However, none of the exposed information is particularly interesting (IMO).  I would put 'Identifiers, citations, and license' at the top, and expand it, then the 'Methods and Tools', expanded, then the Model/simulation, expanded.  

Finally, I'd put  'simulation run' and 'provenance' at the bottom, and probably go ahead and expand them?  But if you like it a bit more compact, then those are the ones I would leave collapsed.

![image](https://github.com/biosimulations/biosimulations/assets/1736150/0d563caa-a01f-4193-a2b2-4c781ad3c90d)

**Comment by AlexPatrie** [comment]
I felt the same way about this. I selected the pre-opened panels based on the wishes of the team here at UConn. I would like to keep some panels closed on render to both keep the compact look and also prompt the user to interact with this reactive set of components. Personally, I would like to keep only `Methods & tools` and `Simulation run` panels open as I believe them to be the most informative in regard to the nature of the simulation itself.
