### ISSUE TITLE
move 're-run' outside of the box

### ISSUE THREAD

**Issue by luciansmith** [reproducible-biomedical-modeling/CRBM-Viz#4772]
Right now, the 'customize and re-run' button is inside the box in the right frame, which puts a tab menu below it, which I think is weird:

![image](https://github.com/biosimulations/biosimulations/assets/1736150/e6e4a052-67c0-472d-8e1c-ccf8b1be65f5)

Instead, I would put that button above and to the right of that column of information, and then the tabs for the box would be at the top, where people expect them to be.

**Comment by AlexPatrie** [comment]
I temporarily removed this button as it simply displays an 'under dev' message currently. I am currently developing this functionality and will re-implement this button at full-functionality.
