### ISSUE TITLE
Kubernetes ingress services need HTTPS

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#685]
The backend apis are served at 

http://34.120.108.199/
http://34.120.61.32/

We need to either create our own ssl certificates (though let's encrypt?) or use google's service to enable https. 

Google managed instructions: https://cloud.google.com/kubernetes-engine/docs/how-to/managed-certs

@mpw6  Could you advise on how to set this up both on google cloud and also what we would need to do on the self hosted cluster?

**Comment by gmarupilla** [comment]
There's already a let's encrypt based service named "certbot" which is completely free, it also has auto-update feature which runs every 3 months (since let's encrypt certificate is valid only for 90 days).

But an IP cannot become https, only domain/subdomain can, maybe we can serve them at api.biosimulations.org?

**Comment by bilalshaikh42** [comment]
Yes, of course I intended to attach a domain to it. I will forward
api.biosimulations.org and accounts.biosimulations.org to the two apis.

Do you have access to the certificate? Lets coordinate how to share the
certificate over slack.

**Comment by bilalshaikh42** [comment]
Resolved on google cloud. Lets discuss getting ssl on the cluster at the next meeting

**Comment by gmarupilla** [comment]
I don't think we need to share the certificates. I haven't really used certbot as such, I just read an article about how to setup SSL for free. Certbot website itself has really good documentation on how to set it up. 

I'm not sure how it will work among clusters (assuming it's K8 cluster that we're talking about).

I just think if we're to go forward with let's encrypt, certbot can play an important role to manage/reissue certificates. But I don't know the steps to do that.

**Comment by bilalshaikh42** [comment]
https://cert-manager.io/ can be use to connect the cluster to the lets encrypt provider
