### ISSUE TITLE
Registration page should display links to the terms of service and privacy policy

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#729]
The registration page looks great!

One comment, the registration page should either display the terms of service and privacy policy or provide links to them. Whichever you choose, it should be consistent with the Code of Conduct as well.

**Comment by bilalshaikh42** [comment]
The privacy policy and terms of service should show up as soon as they are created in the repository. 
Currently, the files are located [here](https://raw.githubusercontent.com/reproducible-biomedical-modeling/Biosimulations/master/PRIVACY_POLICY.md) and [here](https://raw.githubusercontent.com/reproducible-biomedical-modeling/Biosimulations/master/TERMS_OF_SERVICE.md). 

The registration page simply pulls from that url.  Once #573  is closed, they should show up
