### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#773]
The current CI pipeline is not working due to errors in the dev branch. I merged in some pull requests before they were fully ready to speed up some of the major changes. We should adress these before moving forward. 

Biosimulations-dispatch and biosimulations-frontend do not build
Biosimulations-api does not pass tests. 

@gmarupilla  Can you get the dispatch package building and passing tests? I will work on frontend and api

**Comment by gmarupilla** [comment]
Yeah, I'm already on it.

**Comment by bilalshaikh42** [comment]
Resolved. Fixing the testing for biosimulations-frontend is still pending.
