### ISSUE TITLE
Create an API to run simulations

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#782]
Due to requirements of NAR Webserver issue, we need an API that is not restricted to users with accounts. 
The "dispatch" portion of the system can meet this requirement. The API should meet the following base requirements (work in progress): 

1. Have routes to accept a simulation through an OMEX archive.
   a. Generate a unique id for this run
   b. Save the needed files somewhere (db/fs/hpc)
   c. Send a message to the dispatch service about running the simulations 
   d. Return to the user the id of the dispatched simulation

2. Have a route to get the results of a simulation run based on the  id provided
 
Later enhancements
----------------------------------------------------------------------------------------

3.  Have a route to run a simulation based on the Biosimulations ID

4  Allow users to optionally login- get a higher priority dispatch/save to a more persistent id

**Comment by gmarupilla** [comment]
Do we need to use Material Design for dispatch-frontend or we can use plain bootstrap for this one?

**Comment by jonrkarr** [comment]
Feel free to use whatever you like. For simpler projects such as this, I
think bootstrap and Zurb Foundation are good choices.

**Comment by bilalshaikh42** [comment]
I think it would be better to use the common UI elements defined in the monorepo. 
This way, we will have a consistent look at feel across all the applications.   You can take a look at the login-frontend app to see how the UI library was used and can add your own ui components to it.

**Comment by jonrkarr** [comment]
Using common UI elements would be ideal. The would promote consistency and reuse. However, I think this may require more work. At least to start, I think bootstrap or Zurb would be easier to use. We can achieve a similar graphical style by using the same CSS rules. When we have more time, we could re-implement this frontend using Angular.

**Comment by bilalshaikh42** [comment]
The nx system has already created the angular app skeleton and build tools.
But if it is easier to make the front end without angular, that is fine too
