### ISSUE TITLE
How to render description on top level resources

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#792]
The top level resources field contains a description field that can be set by the author. 
The models imported from biomodels use html as a part of this description.  The current front end assumes that the field will just be free flowing text and displays it as a paragraph.

A few issues that need to be discussed

1) The text needs to be sanitized before being rendered to prevent malicious scripts

2) Should we accept HTML? Can we standardize this to use Common Mark markdown? Can we render either markdown or html? (this is being done on the login fronted to show the licenses)

3) Can users edit their descriptions using a markdown editor? 

4) Should we have some sort of validation to help users confirm that they are sending correct html/markdown? This could be a warning rather than an error on the API.

**Comment by jonrkarr** [comment]
For now, I think you can stick with plain text. You can use a node package to sanitize the text when displaying it inside the app, if Angular doesn't automatically do this.

Going forward. markdown (Common or GitHub-flavored) would be good. You can use a node package to validate and render the text.

**Comment by bilalshaikh42** [comment]
The ngx-markdown package already in use can render then HTML just as well as Markdown. It also provides sanitation and security config options.  We can add a tab to the textbox to preview markdown as users are typing. 
Later, we can add some formatting elements to the UI
