### ISSUE TITLE
Framework IRIs for existing models need to be updated

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#879]
The IRI field for the Framework object in the Biomodels imported models points to a link on the Biomodels website which has moved.
For example, the Non-spatial Continuous Framework has an iri of "http://biomodels.net/SBO/SBO_0000293" which gives a 404. The IRI  http://www.ebi.ac.uk/sbo/main/display?nodeId=294 might be a replacement

**Comment by jonrkarr** [comment]
I know these IRIs don't work as URLs. I'm not sure whether they were ever intended to work as URLs. Nevertheless, I think these are considered the official IRIs. For example, this the EBI's ontology service shows these IRIs. See [example](https://www.ebi.ac.uk/ols/ontologies/sbo/terms?iri=http%3A%2F%2Fbiomodels.net%2FSBO%2FSBO_0000027&viewMode=All&siblings=false).

http://biomodels.net/SBO/ has always forwarded to http://www.ebi.ac.uk/sbo. I think this the correct IRI pattern
```
http://www.ebi.ac.uk/sbo/main/SBO:0000027
```

Alternatively, this URL pattern could be used to retrieve ontology terms based on their IRI: 
```
https://www.ebi.ac.uk/ols/ontologies/sbo/terms?iri=http://biomodels.net/SBO/SBO_0000293
```

**Comment by jonrkarr** [comment]
The first solution (https://www.ebi.ac.uk/sbo/main/SBO:0000027) is probably the simplest.

I updated this in Biosimulations-utils.
