### ISSUE TITLE
Tests are failing 

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#9]
Need to write tests for each component

**Comment by bilalshaikh42** [comment]
@gmarupilla Could you work on this as well? We need to get every test passing atleast for the unit tests. As we add more components it will get harder to manage so we should get this done before any further work

**Comment by gmarupilla** [comment]
Yeah! Sure.

**Comment by gmarupilla** [comment]
I looked into it. The problem with writing tests right now is that the requirement is not very concrete as of now. If i write tests right now, they'll have to be changed again once we start developing according to OAS file. What do you think?

**Comment by bilalshaikh42** [comment]
We should definitely have the tests set up even though the spec is not finalized. 

Firstly for unit tests, the majority of the test cases will not be dependent on the structure of objects but tests more basic features like ensuring that a list is properly populated or that the links and routing work. The ones that do rely on the objects _Should_  fail if the spec changes so that we know that the front end needs updating.
 
Secondly, the e2e integration tests should not be dependent on the spec at all, but instead ensure that the site is working, regardless of what the api is sending out. Is a spec change breaks the e2e tests then that is a sign that the site needs to be adapted to the new spec, not that the tests must be changed.

**Comment by bilalshaikh42** [comment]
@gmarupilla 
All the tests have been fixed except for 2, the vega-viewer component and the file-edit component. 
Both are giving an error about a parameter being null. For both components, the parameter is set using an HTTP Request. 
We need to follow the below directions to mock the HTTPS request and give back a test parameter for the components to render. 

https://blog.angulartraining.com/how-to-write-unit-tests-for-angular-code-that-uses-the-httpclient-429fa782eb15

**Comment by bilalshaikh42** [comment]
fixed partially by #35 
New issues opened for individual tests failing
