### ISSUE TITLE
Footer extends past page on small screens

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#92]
The footer will extend to the right of the viewport on a small screen, creating a scroll bar. The icons are displayed over a blank background. 
This can probably be fixed by enabling wrapping in the flex container but will need to replace the current spacing hack with a better method

**Comment by jonrkarr** [comment]
Taken care of in layout-style branch

**Comment by bilalshaikh42** [comment]
Merged in #115
