### ISSUE TITLE
On route changes, scroll to top of page

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#980]
Currently, the application doesn't scroll all the way to the top of the page on route changes. Setting `scrollPositionRestoration='enabled'` doesn't seem to be sufficient. See also https://angular.io/api/router/ExtraOptions#scrollPositionRestoration

**Comment by bilalshaikh42** [comment]
A potentially useful resource 
https://indepth.dev/demystifying-angular-router-what-is-routerscroller-and-why-is-it-useful-2/

**Comment by jonrkarr** [comment]
Addressed in `dev-simulators-2` branch.
