### ISSUE TITLE
How should simulation data be stored and retrieved?

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#984]
Here is a prebuilt rest API for viewing results in hdf5
https://github.com/HDFGroup/h5serv

**Comment by jonrkarr** [comment]
For now, we're asking simulation programs to store results in CSV format.

The platform can convert this to HDF5. h5serv seems very useful. In particular, it supports selection. But, its functionality seems pretty basic. Rather than trying to fork and expand it, it might be easier to implement the subset of features we need ourselves.

**Comment by bilalshaikh42** [comment]
The issue in particular will be with larger simulations. While they can output there results as csv, the dispatch api may not be able to query the data or return it to the frontend. Perhaps a future pipeline can take data above a certain size and process it

**Comment by jonrkarr** [comment]
I agree that CSV is problematic for simulations that produce large results (e.g., long simulations and/or simulations with many outputs). Long-term, we need to address this. But, we don't need to address this to provide basic visualization capabilities for runBioSimulations. For now, we need to focus on just the most critical features.

We discussed this issue of large results a few weeks ago. My recollection is that we agreed to place a limit on the size of results which can be displayed by the runBioSimulations visualization. More specifically, we agreed to place a limit on the size of results that the API can return. If a user requests results greater than our limit, they should get an error that says the results are too large, recommends they use another tool such as matplotlib, and says we aim to work on this issue going forward. This allows us to get a fully working (albeit missing a some features needed for specific kinds of simulations) application that people can begin to use before we can deal with this issue. 

Getting an app out to the community will likely help a lot with getting traction among the community. This should make it easier for us to get other people to help us (e.g., with creating containers or importing models from other databases).

**Comment by moraru** [comment]
I agree.  For most simulations in the Biomodels database realm of models size should not be a problem.  Where size is such that it is a problem, our viz tools would probably not be that appropriate anyway.

That being said, providing an export/download capability early on (perhaps from the beginning), which could be hdf5 or nrrd, both easy to implement, I think would be good.

Ion

**Comment by jonrkarr** [comment]
A link to export/download data is covered by #1071. The platform app will need to provide a similar export/download link.

For now, I think CSV is sufficient. Going forward, we could enable results to be downloaded in multiple formats (tsv, HDF, zarr, etc.). I think we can leave this to the future because this doesn't seem essential to building a minimal application that the community can start using.

**Comment by bilalshaikh42** [comment]
We have stored simulation data as CSV on the HPC. The dispatch  service reads this and saves the data to the Mongo database.
The images are being updated to use HDF. 
This HDF file can be stored on the HPC file system, onto the database using Gridfs, or some form of object storage. The dispatch service will be updated to then read HDF instead of CSV

**Comment by moraru** [comment]
A little confused – I thought we don’t move to HDF now, but only after paper submission inquiry?

**Comment by jonrkarr** [comment]
Correct, Bilal is setting up the API to accept CSV files. He's designing this in such a way that it will be easy to switch to HDF. For example, CSV files are expected to be at the same location as they will be in HDF5 files. The row/column structure of the CSV files is the same as what the HDF5 will have.

Simultaneously, I'm making the images produce CSV (as well as HDF). When we're ready to switch the API to HDF, I'll turn off CSV output in the images.

HDF5 will have several advantages:
- Support multi-dimensional results (e.g., results spatial simulations)
- Explicit data types (e.g., for logical simulations)
- More support for annotation of rows and columns
- Bundling of multiple reports into a single file
- More efficient storage with compression
- Much more efficient retrieval of individual chunks (subsets of rows/columns)

Note, there is a decent program [HDFView](https://www.hdfgroup.org/downloads/hdfview/) for viewing HDF5 files.

**Comment by moraru** [comment]
OK, got it.

**Comment by moraru** [comment]
As you know,I was always a fan of HDF5, just wasn't sure if there was a change to the timeline.
